org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false



minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
neo_version=47.1.65
neo_version_range=[47.1,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1


## Mod Properties

mod_id=prehistoricfauna
mod_name=Prehistoric Fauna
mod_license=All Rights Reserved
mod_version=2.3.0
mod_group_id=superlord.prehistoricfauna
mod_authors=superlord9362, Corgi Taco, RafaMv, AlexThe668, cappin
mod_description=Travel to the past to discover worlds time forgot. Bring back animals long extinct, or join their world.
pack_format_number=15
