modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
[[mods]]
modId="prehistoricfauna"
version="2.3.0"
displayName="Prehistoric Fauna"
credits="AGSuko, Antlion, Bastion, Baular, Coda, Corgi Taco, Obsolerus, RafaMv, Ralof, Seal, superlord9362, Weastian"
authors="${mod_authors}"
description='''
${mod_description}
'''
[[dependencies.prehistoricfauna]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.prehistoricfauna]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    