modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
[[mods]]
modId="prehistoricfauna"
version="2.4.0"
displayName="Prehistoric Fauna"
credits="AGSuko, Antlion, Baular, Coda, Corgi Taco, Definitely not Dilophosaurus, GibblyGjabble, Gneiss Name, Jen, K3pxthereemonster, Mayonnaise Eater, Obsolerus, RafaMv, Ralof, Seal, Sleepy Spino, superlord9362, Weastian"
authors="superlord9362, Corgi Taco, RafaMv, Alexthe668, cappin"
description='''
Travel to the past to discover worlds time forgot. Bring back animals long extinct, or join their world.
'''
[[dependencies.prehistoricfauna]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.prehistoricfauna]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    