package superlord.prehistoricfauna.init;

import net.minecraft.block.Block;
import net.minecraft.block.DoublePlantBlock;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.FenceGateBlock;
import net.minecraft.block.FlowerPotBlock;
import net.minecraft.block.LeavesBlock;
import net.minecraft.block.LogBlock;
import net.minecraft.block.PressurePlateBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.RenderTypeLookup;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.fml.loading.FMLEnvironment;
import superlord.prehistoricfauna.PrehistoricFauna;
import superlord.prehistoricfauna.PrehistoricFauna.PFEntities;
import superlord.prehistoricfauna.PrehistoricFauna.PFPlants;
import superlord.prehistoricfauna.PrehistoricFauna.PFWood;
import superlord.prehistoricfauna.block.AnkylosaurusEggBlock;
import superlord.prehistoricfauna.block.MossBlock;
import superlord.prehistoricfauna.block.MossyDirtBlock;
import superlord.prehistoricfauna.block.PrehistoricButtonBlock;
import superlord.prehistoricfauna.block.PrehistoricDoorBlock;
import superlord.prehistoricfauna.block.PrehistoricPlant;
import superlord.prehistoricfauna.block.PrehistoricPlantBlock;
import superlord.prehistoricfauna.block.PrehistoricPressurePlateBlock;
import superlord.prehistoricfauna.block.PrehistoricSaplingBlock;
import superlord.prehistoricfauna.block.PrehistoricStairsBlock;
import superlord.prehistoricfauna.block.PrehistoricTrapDoorBlock;
import superlord.prehistoricfauna.block.ThescelosaurusEggBlock;
import superlord.prehistoricfauna.block.TriceratopsEggBlock;
import superlord.prehistoricfauna.block.TyrannosaurusEggBlock;
import superlord.prehistoricfauna.world.feature.AraucariaTree;
import superlord.prehistoricfauna.world.feature.CypressTree;
import superlord.prehistoricfauna.world.feature.MetasequoiaTree;

@Mod.EventBusSubscriber(modid = PrehistoricFauna.MODID, bus = Bus.MOD)
public class BlockInit {
	
	public static final Block HORSETAIL = new PrehistoricPlant(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("horsetail");
	public static final Block OSMUNDA = new PrehistoricPlant(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("osmunda");
	public static final Block DOUBLE_HORSETAIL = new DoublePlantBlock(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("double_horsetail");
	public static final Block DOUBLE_OSMUNDA = new DoublePlantBlock(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("double_osmunda");
	public static final Block CLUBMOSS = new PrehistoricPlantBlock(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("clubmoss");
	public static final Block MARCHANTIA = new PrehistoricPlantBlock(Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("marchantia");
	public static final Block MOSS = new MossBlock(Block.Properties.create(Material.PLANTS).hardnessAndResistance(0.2F).sound(SoundType.PLANT)).setRegistryName("moss");
	public static final Block METASEQUOIA_PLANKS = new Block(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_planks");
	public static final Block METASEQUOIA_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_log");
	public static final Block METASEQUOIA_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()).setRegistryName("metasequoia_leaves");
	public static final Block METASEQUOIA_SAPLING = new PrehistoricSaplingBlock(new MetasequoiaTree(), Block.Properties.create(Material.PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("metasequoia_sapling");
	public static final Block METASEQUOIA_LOG_STRIPPED = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_log_stripped");
	public static final Block METASEQUOIA_WOOD = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_wood");
	public static final Block STRIPPED_METASEQUOIA_WOOD = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_metasequoia_wood");
	public static final Block ARAUCARIA_PLANKS = new Block(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("araucaria_planks");
	public static final Block ARAUCARIA_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("araucaria_log");
	public static final Block ARAUCARIA_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()).setRegistryName("araucaria_leaves");
	public static final Block ARAUCARIA_SAPLING = new PrehistoricSaplingBlock(new AraucariaTree(), Block.Properties.create(Material.PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("araucaria_sapling");
	public static final Block STRIPPED_ARAUCARIA_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_araucaria_log");
	public static final Block ARAUCARIA_WOOD = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("araucaria_wood");
	public static final Block STRIPPED_ARAUCARIA_WOOD = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_araucaria_wood");
	public static final Block METASEQUOIA_SLAB = new SlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_slab");
	public static final Block ARAUCARIA_SLAB = new SlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("araucaria_slab");
	public static final Block METASEQUOIA_STAIRS = new PrehistoricStairsBlock(METASEQUOIA_PLANKS.getDefaultState(), Block.Properties.from(METASEQUOIA_PLANKS)).setRegistryName("metasequoia_stairs");
	public static final Block ARAUCARIA_STAIRS = new PrehistoricStairsBlock(ARAUCARIA_PLANKS.getDefaultState(), Block.Properties.from(ARAUCARIA_PLANKS)).setRegistryName("araucaria_stairs");
	public static final Block METASEQUOIA_FENCE = new FenceBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_fence");
	public static final Block ARAUCARIA_FENCE = new FenceBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("araucaria_fence");
	public static final Block METASEQUOIA_FENCE_GATE = new FenceGateBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("metasequoia_fence_gate");
	public static final Block ARAUCARIA_FENCE_GATE = new FenceGateBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("araucaria_fence_gate");
	public static final Block METASEQUOIA_BUTTON = new PrehistoricButtonBlock(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)).setRegistryName("metasequoia_button");
	public static final Block ARAUCARIA_BUTTON = new PrehistoricButtonBlock(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)).setRegistryName("araucaria_button");
	public static final Block METASEQUOIA_DOOR = new PrehistoricDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid()).setRegistryName("metasequoia_door");
	public static final Block ARAUCARIA_DOOR = new PrehistoricDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid()).setRegistryName("araucaria_door");
	public static final Block METASEQUOIA_PRESSURE_PLATE = new PrehistoricPressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)).setRegistryName("metasequoia_pressure_plate");
	public static final Block ARAUCARIA_PRESSURE_PLATE = new PrehistoricPressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)).setRegistryName("araucaria_pressure_plate");
	public static final Block METASEQUOIA_TRAPDOOR = new PrehistoricTrapDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid()).setRegistryName("metasequoia_trapdoor");
	public static final Block ARAUCARIA_TRAPDOOR = new PrehistoricTrapDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid()).setRegistryName("araucaria_trapdoor");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_METASEQUOIA_SAPLING = new FlowerPotBlock(METASEQUOIA_SAPLING, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_metasequoia_sapling");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_ARAUCARIA_SAPLING = new FlowerPotBlock(ARAUCARIA_SAPLING, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_araucaria_sapling");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_HORSETAIL = new FlowerPotBlock(HORSETAIL, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_horsetail");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_OSMUNDA = new FlowerPotBlock(OSMUNDA, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_osmunda");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_CLUBMOSS = new FlowerPotBlock(CLUBMOSS, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_clubmoss");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_MARCHANTIA = new FlowerPotBlock(MARCHANTIA, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_marchantia");
	public static final Block MOSSY_DIRT = new MossyDirtBlock(Block.Properties.create(Material.ORGANIC).hardnessAndResistance(0.6F).sound(SoundType.PLANT)).setRegistryName("mossy_dirt");
	public static final Block THESCELOSAURUS_EGG = new ThescelosaurusEggBlock(Block.Properties.create(Material.DRAGON_EGG, MaterialColor.SAND).hardnessAndResistance(0.5F).sound(SoundType.METAL).tickRandomly().notSolid()).setRegistryName("thescelosaurus_egg");
	public static final Block TRICERATOPS_EGG = new TriceratopsEggBlock(Block.Properties.create(Material.DRAGON_EGG, MaterialColor.SAND).hardnessAndResistance(0.5F).sound(SoundType.METAL).tickRandomly().notSolid()).setRegistryName("triceratops_egg");
	public static final Block ANKYLOSAURUS_EGG = new AnkylosaurusEggBlock(Block.Properties.create(Material.DRAGON_EGG, MaterialColor.SAND).hardnessAndResistance(0.5F).sound(SoundType.METAL).tickRandomly().notSolid()).setRegistryName("ankylosaurus_egg");
	public static final Block TYRANNOSAURUS_EGG = new TyrannosaurusEggBlock(Block.Properties.create(Material.DRAGON_EGG, MaterialColor.SAND).hardnessAndResistance(0.5F).sound(SoundType.METAL).tickRandomly().notSolid()).setRegistryName("tyrannosaurus_egg");
	public static final Block CYPRESS_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("cypress_log");
	public static final Block CYPRESS_PLANKS = new Block(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("cypress_planks");
	public static final Block STRIPPED_CYPRESS_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_cypress_log");
	public static final Block CYPRESS_WOOD = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("cypress_wood");
	public static final Block STRIPPED_CYPRESS_WOOD = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName("stripped_cypress_wood");
	public static final Block CYPRESS_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT).notSolid()).setRegistryName("cypress_leaves");
	public static final Block CYPRESS_STAIRS = new PrehistoricStairsBlock(CYPRESS_PLANKS.getDefaultState(), Block.Properties.from(CYPRESS_PLANKS)).setRegistryName("cypress_stairs");
	public static final Block CYPRESS_DOOR = new PrehistoricDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid()).setRegistryName("cypress_door");
	public static final Block CYPRESS_PRESSURE_PLATE = new PrehistoricPressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)).setRegistryName("cypress_pressure_plate");
	public static final Block CYPRESS_FENCE = new FenceBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("cypress_fence");
	public static final Block CYPRESS_TRAPDOOR = new PrehistoricTrapDoorBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(3.0F).sound(SoundType.WOOD).notSolid()).setRegistryName("cypress_trapdoor");
	public static final Block CYPRESS_FENCE_GATE = new FenceGateBlock(Block.Properties.create(Material.WOOD, MaterialColor.OBSIDIAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("cypress_fence_gate");
	public static final Block CYPRESS_BUTTON = new PrehistoricButtonBlock(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().hardnessAndResistance(0.5F).sound(SoundType.WOOD)).setRegistryName("cypress_button");
	public static final Block CYPRESS_SLAB = new SlabBlock(Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("cypress_slab");
	public static final Block CYPRESS_SAPLING = new PrehistoricSaplingBlock(new CypressTree(), Block.Properties.create(Material.PLANTS).doesNotBlockMovement().tickRandomly().hardnessAndResistance(0).sound(SoundType.PLANT)).setRegistryName("cypress_sapling");
	@SuppressWarnings("deprecation")
	public static final Block POTTED_CYPRESS_SAPLING = new FlowerPotBlock(CYPRESS_SAPLING, Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0).notSolid()).setRegistryName("potted_cypress_sapling");
	
	@SubscribeEvent
	public static void registerBlocks(final RegistryEvent.Register<Block> event) {
		event.getRegistry().register(HORSETAIL);
		event.getRegistry().register(OSMUNDA);
		event.getRegistry().register(DOUBLE_HORSETAIL);
		event.getRegistry().register(DOUBLE_OSMUNDA);
		event.getRegistry().register(CLUBMOSS);
		event.getRegistry().register(MARCHANTIA);
		event.getRegistry().register(MOSS);
		event.getRegistry().register(METASEQUOIA_LEAVES);
		event.getRegistry().register(METASEQUOIA_LOG);
		event.getRegistry().register(METASEQUOIA_PLANKS);
		event.getRegistry().register(METASEQUOIA_SAPLING);
		event.getRegistry().register(METASEQUOIA_LOG_STRIPPED);
		event.getRegistry().register(METASEQUOIA_WOOD);
		event.getRegistry().register(STRIPPED_METASEQUOIA_WOOD);
		event.getRegistry().register(ARAUCARIA_LEAVES);
		event.getRegistry().register(ARAUCARIA_LOG);
		event.getRegistry().register(ARAUCARIA_PLANKS);
		event.getRegistry().register(ARAUCARIA_SAPLING);
		event.getRegistry().register(STRIPPED_ARAUCARIA_LOG);
		event.getRegistry().register(ARAUCARIA_WOOD);
		event.getRegistry().register(STRIPPED_ARAUCARIA_WOOD);
		event.getRegistry().register(ARAUCARIA_BUTTON);
		event.getRegistry().register(ARAUCARIA_DOOR);
		event.getRegistry().register(ARAUCARIA_FENCE);
		event.getRegistry().register(ARAUCARIA_FENCE_GATE);
		event.getRegistry().register(ARAUCARIA_PRESSURE_PLATE);
		event.getRegistry().register(ARAUCARIA_SLAB);
		event.getRegistry().register(ARAUCARIA_STAIRS);
		event.getRegistry().register(ARAUCARIA_TRAPDOOR);
		event.getRegistry().register(METASEQUOIA_BUTTON);
		event.getRegistry().register(METASEQUOIA_DOOR);
		event.getRegistry().register(METASEQUOIA_FENCE);
		event.getRegistry().register(METASEQUOIA_FENCE_GATE);
		event.getRegistry().register(METASEQUOIA_PRESSURE_PLATE);
		event.getRegistry().register(METASEQUOIA_SLAB);
		event.getRegistry().register(METASEQUOIA_STAIRS);
		event.getRegistry().register(METASEQUOIA_TRAPDOOR);
		event.getRegistry().register(POTTED_ARAUCARIA_SAPLING);
		event.getRegistry().register(POTTED_METASEQUOIA_SAPLING);
		event.getRegistry().register(POTTED_CLUBMOSS);
		event.getRegistry().register(POTTED_HORSETAIL);
		event.getRegistry().register(POTTED_MARCHANTIA);
		event.getRegistry().register(POTTED_OSMUNDA);
		event.getRegistry().register(MOSSY_DIRT);
		event.getRegistry().register(THESCELOSAURUS_EGG);
		event.getRegistry().register(TRICERATOPS_EGG);
		event.getRegistry().register(TYRANNOSAURUS_EGG);
		event.getRegistry().register(ANKYLOSAURUS_EGG);
		event.getRegistry().register(CYPRESS_LOG);
		event.getRegistry().register(CYPRESS_BUTTON);
		event.getRegistry().register(CYPRESS_DOOR);
		event.getRegistry().register(CYPRESS_FENCE);
		event.getRegistry().register(CYPRESS_FENCE_GATE);
		event.getRegistry().register(CYPRESS_LEAVES);
		event.getRegistry().register(CYPRESS_PLANKS);
		event.getRegistry().register(CYPRESS_PRESSURE_PLATE);
		event.getRegistry().register(CYPRESS_SAPLING);
		event.getRegistry().register(CYPRESS_SLAB);
		event.getRegistry().register(CYPRESS_STAIRS);
		event.getRegistry().register(CYPRESS_TRAPDOOR);
		event.getRegistry().register(CYPRESS_WOOD);
		event.getRegistry().register(STRIPPED_CYPRESS_LOG);
		event.getRegistry().register(STRIPPED_CYPRESS_WOOD);
		event.getRegistry().register(POTTED_CYPRESS_SAPLING);
		if (FMLEnvironment.dist == Dist.CLIENT) {
			RenderType cutoutRenderType = RenderType.getCutout();
			RenderType mippedRenderType = RenderType.getCutoutMipped();
			
			RenderTypeLookup.setRenderLayer(HORSETAIL, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(OSMUNDA, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(DOUBLE_HORSETAIL, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(DOUBLE_OSMUNDA, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(CLUBMOSS, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(MARCHANTIA, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(METASEQUOIA_SAPLING, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(METASEQUOIA_LEAVES, mippedRenderType);
			RenderTypeLookup.setRenderLayer(ARAUCARIA_SAPLING, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(ARAUCARIA_LEAVES, mippedRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_ARAUCARIA_SAPLING, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_METASEQUOIA_SAPLING, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_CLUBMOSS, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_HORSETAIL, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_MARCHANTIA, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_OSMUNDA, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(ARAUCARIA_DOOR, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(METASEQUOIA_DOOR, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(ARAUCARIA_TRAPDOOR, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(METASEQUOIA_TRAPDOOR, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(CYPRESS_SAPLING, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(CYPRESS_LEAVES, mippedRenderType);
			RenderTypeLookup.setRenderLayer(POTTED_CYPRESS_SAPLING, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(CYPRESS_DOOR, cutoutRenderType);
			RenderTypeLookup.setRenderLayer(CYPRESS_TRAPDOOR, cutoutRenderType);
		}
	}
	
	@SubscribeEvent
	public static void registerBlockItems(final RegistryEvent.Register<Item> event) {
		event.getRegistry().register(new BlockItem(HORSETAIL, new Item.Properties().group(PFPlants.instance)).setRegistryName("horsetail"));
		event.getRegistry().register(new BlockItem(OSMUNDA, new Item.Properties().group(PFPlants.instance)).setRegistryName("osmunda"));
		event.getRegistry().register(new BlockItem(DOUBLE_HORSETAIL, new Item.Properties().group(PFPlants.instance)).setRegistryName("double_horsetail"));
		event.getRegistry().register(new BlockItem(DOUBLE_OSMUNDA, new Item.Properties().group(PFPlants.instance)).setRegistryName("double_osmunda"));
		event.getRegistry().register(new BlockItem(CLUBMOSS, new Item.Properties().group(PFPlants.instance)).setRegistryName("clubmoss"));
		event.getRegistry().register(new BlockItem(MARCHANTIA, new Item.Properties().group(PFPlants.instance)).setRegistryName("marchantia"));
		event.getRegistry().register(new BlockItem(MOSS, new Item.Properties().group(PFPlants.instance)).setRegistryName("moss"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_LEAVES, new Item.Properties().group(PFPlants.instance)).setRegistryName("metasequoia_leaves"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_LOG, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_log"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_PLANKS, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_planks"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_SAPLING, new Item.Properties().group(PFPlants.instance)).setRegistryName("metasequoia_sapling"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_LOG_STRIPPED, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_log_stripped"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_WOOD, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_wood"));
		event.getRegistry().register(new BlockItem(STRIPPED_METASEQUOIA_WOOD, new Item.Properties().group(PFWood.instance)).setRegistryName("stripped_metasequoia_wood"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_LEAVES, new Item.Properties().group(PFPlants.instance)).setRegistryName("araucaria_leaves"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_LOG, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_log"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_PLANKS, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_planks"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_SAPLING, new Item.Properties().group(PFPlants.instance)).setRegistryName("araucaria_sapling"));
		event.getRegistry().register(new BlockItem(STRIPPED_ARAUCARIA_LOG, new Item.Properties().group(PFWood.instance)).setRegistryName("stripped_araucaria_log"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_WOOD, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_wood"));
		event.getRegistry().register(new BlockItem(STRIPPED_ARAUCARIA_WOOD, new Item.Properties().group(PFWood.instance)).setRegistryName("stripped_araucaria_wood"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_BUTTON, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_button"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_DOOR, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_door"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_FENCE, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_fence"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_FENCE_GATE, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_fence_gate"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_PRESSURE_PLATE, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_pressure_plate"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_SLAB, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_slab"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_STAIRS, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_stairs"));
		event.getRegistry().register(new BlockItem(ARAUCARIA_TRAPDOOR, new Item.Properties().group(PFWood.instance)).setRegistryName("araucaria_trapdoor"));
		event.getRegistry().register(new BlockItem(POTTED_ARAUCARIA_SAPLING, new Item.Properties()).setRegistryName("potted_araucaria_sapling"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_BUTTON, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_button"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_DOOR, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_door"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_FENCE, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_fence"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_FENCE_GATE, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_fence_gate"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_PRESSURE_PLATE, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_pressure_plate"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_SLAB, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_slab"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_STAIRS, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_stairs"));
		event.getRegistry().register(new BlockItem(METASEQUOIA_TRAPDOOR, new Item.Properties().group(PFWood.instance)).setRegistryName("metasequoia_trapdoor"));
		event.getRegistry().register(new BlockItem(POTTED_METASEQUOIA_SAPLING, new Item.Properties()).setRegistryName("potted_metasequoia_sapling"));
		event.getRegistry().register(new BlockItem(POTTED_CLUBMOSS, new Item.Properties()).setRegistryName("potted_clubmoss"));
		event.getRegistry().register(new BlockItem(POTTED_HORSETAIL, new Item.Properties()).setRegistryName("potted_horsetail"));
		event.getRegistry().register(new BlockItem(POTTED_MARCHANTIA, new Item.Properties()).setRegistryName("potted_marchantia"));
		event.getRegistry().register(new BlockItem(POTTED_OSMUNDA, new Item.Properties()).setRegistryName("potted_osmunda"));
		event.getRegistry().register(new BlockItem(MOSSY_DIRT, new Item.Properties().group(PFPlants.instance)).setRegistryName("mossy_dirt"));
		event.getRegistry().register(new BlockItem(THESCELOSAURUS_EGG, new Item.Properties().group(PFEntities.instance)).setRegistryName("thescelosaurus_egg"));
		event.getRegistry().register(new BlockItem(TRICERATOPS_EGG, new Item.Properties().group(PFEntities.instance)).setRegistryName("triceratops_egg"));
		event.getRegistry().register(new BlockItem(ANKYLOSAURUS_EGG, new Item.Properties().group(PFEntities.instance)).setRegistryName("ankylosaurus_egg"));
		event.getRegistry().register(new BlockItem(TYRANNOSAURUS_EGG, new Item.Properties().group(PFEntities.instance)).setRegistryName("tyrannosaurus_egg"));
		event.getRegistry().register(new BlockItem(CYPRESS_LEAVES, new Item.Properties().group(PFPlants.instance)).setRegistryName("cypress_leaves"));
		event.getRegistry().register(new BlockItem(CYPRESS_LOG, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_log"));
		event.getRegistry().register(new BlockItem(CYPRESS_PLANKS, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_planks"));
		event.getRegistry().register(new BlockItem(CYPRESS_SAPLING, new Item.Properties().group(PFPlants.instance)).setRegistryName("cypress_sapling"));
		event.getRegistry().register(new BlockItem(STRIPPED_CYPRESS_LOG, new Item.Properties().group(PFWood.instance)).setRegistryName("stripped_cypress_log"));
		event.getRegistry().register(new BlockItem(CYPRESS_WOOD, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_wood"));
		event.getRegistry().register(new BlockItem(STRIPPED_CYPRESS_WOOD, new Item.Properties().group(PFWood.instance)).setRegistryName("stripped_cypress_wood"));
		event.getRegistry().register(new BlockItem(CYPRESS_BUTTON, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_button"));
		event.getRegistry().register(new BlockItem(CYPRESS_DOOR, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_door"));
		event.getRegistry().register(new BlockItem(CYPRESS_FENCE, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_fence"));
		event.getRegistry().register(new BlockItem(CYPRESS_FENCE_GATE, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_fence_gate"));
		event.getRegistry().register(new BlockItem(CYPRESS_PRESSURE_PLATE, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_pressure_plate"));
		event.getRegistry().register(new BlockItem(CYPRESS_SLAB, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_slab"));
		event.getRegistry().register(new BlockItem(CYPRESS_STAIRS, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_stairs"));
		event.getRegistry().register(new BlockItem(CYPRESS_TRAPDOOR, new Item.Properties().group(PFWood.instance)).setRegistryName("cypress_trapdoor"));
		event.getRegistry().register(new BlockItem(POTTED_CYPRESS_SAPLING, new Item.Properties()).setRegistryName("potted_cypress_sapling"));
	}
	
}
