package superlord.prehistoricfauna.init;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import superlord.prehistoricfauna.PrehistoricFauna;
import superlord.prehistoricfauna.common.entity.PFBoat;
import superlord.prehistoricfauna.common.entity.PFChestBoat;
import superlord.prehistoricfauna.common.entity.PFRaft;
import superlord.prehistoricfauna.common.entity.Paleopainting;
import superlord.prehistoricfauna.common.entity.WallFossil;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Aepyornithomimus;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Byronosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Citipati;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.DermestidBeetle;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Gobiulus;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Goyocephale;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Halszkaraptor;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Kol;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Oviraptor;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Pinacosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Plesiohadros;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Protoceratops;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Telmasaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Udanoceratops;
import superlord.prehistoricfauna.common.entity.cretaceous.djadochta.Velociraptor;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Ankylosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Anzu;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Basilemys;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Brachychampsa;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Cephaloleichnites;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Dakotaraptor;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Didelphodon;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Edmontosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Ornithomimus;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Pachycephalosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Palaeosaniwa;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Thescelosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Triceratops;
import superlord.prehistoricfauna.common.entity.cretaceous.hellcreek.Tyrannosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Apoclion;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Beipiaosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Changyuraptor;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Cretaraneus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Dilong;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Dongbeititan;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Incisivosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Jinzhousaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Liaonemobius;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Liaoningosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Psittacosaurus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Repenomamus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Ruixinia;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Sinosauropteryx;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Yutyrannus;
import superlord.prehistoricfauna.common.entity.cretaceous.yixian.Zhenyuanlong;
import superlord.prehistoricfauna.common.entity.fish.Acipenser;
import superlord.prehistoricfauna.common.entity.fish.Arganodus;
import superlord.prehistoricfauna.common.entity.fish.ArganodusCocoon;
import superlord.prehistoricfauna.common.entity.fish.Ceratodus;
import superlord.prehistoricfauna.common.entity.fish.CeratodusCocoon;
import superlord.prehistoricfauna.common.entity.fish.Chinlea;
import superlord.prehistoricfauna.common.entity.fish.Chungkingichthys;
import superlord.prehistoricfauna.common.entity.fish.Cyclurus;
import superlord.prehistoricfauna.common.entity.fish.Gar;
import superlord.prehistoricfauna.common.entity.fish.Harenaichthys;
import superlord.prehistoricfauna.common.entity.fish.Lepidotes;
import superlord.prehistoricfauna.common.entity.fish.Lonchidion;
import superlord.prehistoricfauna.common.entity.fish.Melvius;
import superlord.prehistoricfauna.common.entity.fish.Mooreodontus;
import superlord.prehistoricfauna.common.entity.fish.Morrolepis;
import superlord.prehistoricfauna.common.entity.fish.Myledaphus;
import superlord.prehistoricfauna.common.entity.fish.Ophiopsis;
import superlord.prehistoricfauna.common.entity.fish.Parapsephurus;
import superlord.prehistoricfauna.common.entity.fish.Potamoceratodus;
import superlord.prehistoricfauna.common.entity.fish.PotamoceratodusCocoon;
import superlord.prehistoricfauna.common.entity.fish.Protopsephurus;
import superlord.prehistoricfauna.common.entity.fish.Saurichthys;
import superlord.prehistoricfauna.common.entity.fish.Sinamia;
import superlord.prehistoricfauna.common.entity.fish.Yanosteus;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.AnkylosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.AnkylosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.AnzuSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.AnzuSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.DongbeititanSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.DongbeititanSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.GoyocephaleSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.GoyocephaleSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.LiaoningosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.LiaoningosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.PlesiohadrosSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.PlesiohadrosSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.ProtoceratopsSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.ProtoceratopsSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.PsittacosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.PsittacosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.TriceratopsSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.TriceratopsSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.TyrannosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.TyrannosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.VelociraptorSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.VelociraptorSkull;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.YutyrannusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.cretaceous.YutyrannusSkull;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.AllosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.AllosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.CeratosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.CeratosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.DilophosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.DilophosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.SarahsaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.SarahsaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.ScelidosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.ScelidosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.StegosaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.jurassic.StegosaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.triassic.CoelophysisSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.triassic.CoelophysisSkull;
import superlord.prehistoricfauna.common.entity.fossil.triassic.DesmatosuchusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.triassic.DesmatosuchusSkull;
import superlord.prehistoricfauna.common.entity.fossil.triassic.HerrerasaurusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.triassic.HerrerasaurusSkull;
import superlord.prehistoricfauna.common.entity.fossil.triassic.IschigualastiaSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.triassic.IschigualastiaSkull;
import superlord.prehistoricfauna.common.entity.fossil.triassic.PostosuchusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.triassic.PostosuchusSkull;
import superlord.prehistoricfauna.common.entity.fossil.triassic.SaurosuchusSkeleton;
import superlord.prehistoricfauna.common.entity.fossil.triassic.SaurosuchusSkull;
import superlord.prehistoricfauna.common.entity.henos.CaveSentinel;
import superlord.prehistoricfauna.common.entity.henos.CorruptedTheropod;
import superlord.prehistoricfauna.common.entity.henos.Henos;
import superlord.prehistoricfauna.common.entity.henos.LandSentinel;
import superlord.prehistoricfauna.common.entity.item.FermentedGinkgoBerry;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Calsoyasuchus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Dilophosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Diplichnites;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Kayentachelys;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Kayentasuchus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Kayentatherium;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Kayentavenator;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Megapnosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Octopodichnus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Paleohelcura;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Sarahsaurus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Scelidosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.kayenta.Scutellosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Alcovasaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Allosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Camarasaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Camptosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Ceratosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Cylindricum;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Diablophis;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Dryosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Eilenodon;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Eopolis;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Gargoyleosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Hesperornithoides;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Macelognathus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Parapleurites;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Stegosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Tanycolagreus;
import superlord.prehistoricfauna.common.entity.jurassic.morrison.Torvosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Aboilus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Agilisaurus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Bashanosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Chuandongocoelurus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Cicadocoris;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Gigantspinosaurus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Mesoforficula;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Rhipidoblattina;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Yandusaurus;
import superlord.prehistoricfauna.common.entity.jurassic.shaximiao.Yangchuanosaurus;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Coelophysis;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Desmatosuchus;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Placerias;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Poposaurus;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Postosuchus;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Trilophosaurus;
import superlord.prehistoricfauna.common.entity.triassic.chinle.Typothorax;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Chromogisaurus;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Exaeretodon;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Herrerasaurus;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Hyperodapedon;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Ischigualastia;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Saurosuchus;
import superlord.prehistoricfauna.common.entity.triassic.ischigualasto.Sillosuchus;

public class PFEntities {
	
	public static final DeferredRegister<EntityType<?>> REGISTER = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, PrehistoricFauna.MOD_ID);
	
	public static final RegistryObject<EntityType<GoyocephaleSkull>> GOYOCEPHALE_SKULL = REGISTER.register("goyocephale_skull", () -> EntityType.Builder.<GoyocephaleSkull>of(GoyocephaleSkull::new, MobCategory.MISC).sized(0.8125F, 0.8125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "goyocephale_skull").toString()));
	public static final RegistryObject<EntityType<PlesiohadrosSkull>> PLESIOHADROS_SKULL = REGISTER.register("plesiohadros_skull", () -> EntityType.Builder.<PlesiohadrosSkull>of(PlesiohadrosSkull::new, MobCategory.MISC).sized(0.8125F, 0.8125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "plesiohadros_skull").toString()));
	public static final RegistryObject<EntityType<ProtoceratopsSkull>> PROTOCERATOPS_SKULL = REGISTER.register("protoceratops_skull", () -> EntityType.Builder.<ProtoceratopsSkull>of(ProtoceratopsSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "protoceratops_skull").toString()));
	public static final RegistryObject<EntityType<VelociraptorSkull>> VELOCIRAPTOR_SKULL = REGISTER.register("velociraptor_skull", () -> EntityType.Builder.<VelociraptorSkull>of(VelociraptorSkull::new, MobCategory.MISC).sized(0.4375F, 0.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "velociraptor_skull").toString()));
	public static final RegistryObject<EntityType<AnkylosaurusSkull>> ANKYLOSAURUS_SKULL = REGISTER.register("ankylosaurus_skull", () -> EntityType.Builder.<AnkylosaurusSkull>of(AnkylosaurusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ankylosaurus_skull").toString()));
	public static final RegistryObject<EntityType<AnzuSkull>> ANZU_SKULL = REGISTER.register("anzu_skull", () -> EntityType.Builder.<AnzuSkull>of(AnzuSkull::new, MobCategory.MISC).sized(0.375F, 0.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "anzu_skull").toString()));
	public static final RegistryObject<EntityType<TriceratopsSkull>> TRICERATOPS_SKULL = REGISTER.register("triceratops_skull", () -> EntityType.Builder.<TriceratopsSkull>of(TriceratopsSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "triceratops_skull").toString()));
	public static final RegistryObject<EntityType<TyrannosaurusSkull>> TYRANNOSAURUS_SKULL = REGISTER.register("tyrannosaurus_skull", () -> EntityType.Builder.<TyrannosaurusSkull>of(TyrannosaurusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "tyrannosaurus_skull").toString()));
	public static final RegistryObject<EntityType<DongbeititanSkull>> DONGBEITITAN_SKULL = REGISTER.register("dongbeititan_skull", () -> EntityType.Builder.<DongbeititanSkull>of(DongbeititanSkull::new, MobCategory.MISC).sized(0.5F, 0.625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dongbeititan_skull").toString()));
	public static final RegistryObject<EntityType<LiaoningosaurusSkull>> LIAONINGOSAURUS_SKULL = REGISTER.register("liaoningosaurus_skull", () -> EntityType.Builder.<LiaoningosaurusSkull>of(LiaoningosaurusSkull::new, MobCategory.MISC).sized(0.375F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "liaoningosaurus_skull").toString()));
	public static final RegistryObject<EntityType<PsittacosaurusSkull>> PSITTACOSAURUS_SKULL = REGISTER.register("psittacosaurus_skull", () -> EntityType.Builder.<PsittacosaurusSkull>of(PsittacosaurusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "psittacosaurus_skull").toString()));
	public static final RegistryObject<EntityType<YutyrannusSkull>> YUTYRANNUS_SKULL = REGISTER.register("yutyrannus_skull", () -> EntityType.Builder.<YutyrannusSkull>of(YutyrannusSkull::new, MobCategory.MISC).sized(1, 1).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "yutyrannus_skull").toString()));
	public static final RegistryObject<EntityType<DilophosaurusSkull>> DILOPHOSAURUS_SKULL = REGISTER.register("dilophosaurus_skull", () -> EntityType.Builder.<DilophosaurusSkull>of(DilophosaurusSkull::new, MobCategory.MISC).sized(0.875F, 0.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dilophosaurus_skull").toString()));
	public static final RegistryObject<EntityType<SarahsaurusSkull>> SARAHSAURUS_SKULL = REGISTER.register("sarahsaurus_skull", () -> EntityType.Builder.<SarahsaurusSkull>of(SarahsaurusSkull::new, MobCategory.MISC).sized(0.4375F, 0.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sarahsaurus_skull").toString()));
	public static final RegistryObject<EntityType<ScelidosaurusSkull>> SCELIDOSAURUS_SKULL = REGISTER.register("scelidosaurus_skull", () -> EntityType.Builder.<ScelidosaurusSkull>of(ScelidosaurusSkull::new, MobCategory.MISC).sized(0.5625F, 0.5625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "scelidosaurus_skull").toString()));
	public static final RegistryObject<EntityType<AllosaurusSkull>> ALLOSAURUS_SKULL = REGISTER.register("allosaurus_skull", () -> EntityType.Builder.<AllosaurusSkull>of(AllosaurusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "allosaurus_skull").toString()));
	public static final RegistryObject<EntityType<CeratosaurusSkull>> CERATOSAURUS_SKULL = REGISTER.register("ceratosaurus_skull", () -> EntityType.Builder.<CeratosaurusSkull>of(CeratosaurusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ceratosaurus_skull").toString()));
	public static final RegistryObject<EntityType<StegosaurusSkull>> STEGOSAURUS_SKULL = REGISTER.register("stegosaurus_skull", () -> EntityType.Builder.<StegosaurusSkull>of(StegosaurusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "stegosaurus_skull").toString()));
	public static final RegistryObject<EntityType<CoelophysisSkull>> COELOPHYSIS_SKULL = REGISTER.register("coelophysis_skull", () -> EntityType.Builder.<CoelophysisSkull>of(CoelophysisSkull::new, MobCategory.MISC).sized(0.4375F, 0.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "coelophysis_skull").toString()));
	public static final RegistryObject<EntityType<DesmatosuchusSkull>> DESMATOSUCHUS_SKULL = REGISTER.register("desmatosuchus_skull", () -> EntityType.Builder.<DesmatosuchusSkull>of(DesmatosuchusSkull::new, MobCategory.MISC).sized(0.4375F, 0.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "desmatosuchus_skull").toString()));
	public static final RegistryObject<EntityType<PostosuchusSkull>> POSTOSUCHUS_SKULL = REGISTER.register("postosuchus_skull", () -> EntityType.Builder.<PostosuchusSkull>of(PostosuchusSkull::new, MobCategory.MISC).sized(0.75F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "postosuchus_skull").toString()));
	public static final RegistryObject<EntityType<HerrerasaurusSkull>> HERRERASAURUS_SKULL = REGISTER.register("herrerasaurus_skull", () -> EntityType.Builder.<HerrerasaurusSkull>of(HerrerasaurusSkull::new, MobCategory.MISC).sized(0.6875F, 0.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "herrerasaurus_skull").toString()));
	public static final RegistryObject<EntityType<IschigualastiaSkull>> ISCHIGUALASTIA_SKULL = REGISTER.register("ischigualastia_skull", () -> EntityType.Builder.<IschigualastiaSkull>of(IschigualastiaSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ischigualastia_skull").toString()));
	public static final RegistryObject<EntityType<SaurosuchusSkull>> SAUROSUCHUS_SKULL = REGISTER.register("saurosuchus_skull", () -> EntityType.Builder.<SaurosuchusSkull>of(SaurosuchusSkull::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "saurosuchus_skull").toString()));

	public static final RegistryObject<EntityType<GoyocephaleSkeleton>> GOYOCEPHALE_SKELETON = REGISTER.register("goyocephale_skeleton", () -> EntityType.Builder.<GoyocephaleSkeleton>of(GoyocephaleSkeleton::new, MobCategory.MISC).sized(0.6F, 0.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "goyocephale_skeleton").toString()));
	public static final RegistryObject<EntityType<PlesiohadrosSkeleton>> PLESIOHADROS_SKELETON = REGISTER.register("plesiohadros_skeleton", () -> EntityType.Builder.<PlesiohadrosSkeleton>of(PlesiohadrosSkeleton::new, MobCategory.MISC).sized(1.5F, 2.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "plesiohadros_skeleton").toString()));
	public static final RegistryObject<EntityType<ProtoceratopsSkeleton>> PROTOCERATOPS_SKELETON = REGISTER.register("protoceratops_skeleton", () -> EntityType.Builder.<ProtoceratopsSkeleton>of(ProtoceratopsSkeleton::new, MobCategory.MISC).sized(0.8125F, 0.8125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "protoceratops_skeleton").toString()));
	public static final RegistryObject<EntityType<VelociraptorSkeleton>> VELOCIRAPTOR_SKELETON = REGISTER.register("velociraptor_skeleton", () -> EntityType.Builder.<VelociraptorSkeleton>of(VelociraptorSkeleton::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "velociraptor_skeleton").toString()));
	public static final RegistryObject<EntityType<AnkylosaurusSkeleton>> ANKYLOSAURUS_SKELETON = REGISTER.register("ankylosaurus_skeleton", () -> EntityType.Builder.<AnkylosaurusSkeleton>of(AnkylosaurusSkeleton::new, MobCategory.MISC).sized(2.0F, 2.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ankylosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<AnzuSkeleton>> ANZU_SKELETON = REGISTER.register("anzu_skeleton", () -> EntityType.Builder.<AnzuSkeleton>of(AnzuSkeleton::new, MobCategory.MISC).sized(0.875F, 2.3125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "anzu_skeleton").toString()));
	public static final RegistryObject<EntityType<TriceratopsSkeleton>> TRICERATOPS_SKELETON = REGISTER.register("triceratops_skeleton", () -> EntityType.Builder.<TriceratopsSkeleton>of(TriceratopsSkeleton::new, MobCategory.MISC).sized(2.0F, 2.6F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "triceratops_skeleton").toString()));
	public static final RegistryObject<EntityType<TyrannosaurusSkeleton>> TYRANNOSAURUS_SKELETON = REGISTER.register("tyrannosaurus_skeleton", () -> EntityType.Builder.<TyrannosaurusSkeleton>of(TyrannosaurusSkeleton::new, MobCategory.MISC).sized(2.0F, 3.9F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "tyrannosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<DongbeititanSkeleton>> DONGBEITITAN_SKELETON = REGISTER.register("dongbeititan_skeleton", () -> EntityType.Builder.<DongbeititanSkeleton>of(DongbeititanSkeleton::new, MobCategory.MISC).sized(2.25F, 3.125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dongbeititan_skeleton").toString()));
	public static final RegistryObject<EntityType<LiaoningosaurusSkeleton>> LIAONINGOSAURUS_SKELETON = REGISTER.register("liaoningosaurus_skeleton", () -> EntityType.Builder.<LiaoningosaurusSkeleton>of(LiaoningosaurusSkeleton::new, MobCategory.MISC).sized(1, 0.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "liaoningosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<PsittacosaurusSkeleton>> PSITTACOSAURUS_SKELETON = REGISTER.register("psittacosaurus_skeleton", () -> EntityType.Builder.<PsittacosaurusSkeleton>of(PsittacosaurusSkeleton::new, MobCategory.MISC).sized(0.5F, 0.9375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "psittacosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<YutyrannusSkeleton>> YUTYRANNUS_SKELETON = REGISTER.register("yutyrannus_skeleton", () -> EntityType.Builder.<YutyrannusSkeleton>of(YutyrannusSkeleton::new, MobCategory.MISC).sized(1, 2.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "yutyrannus_skeleton").toString()));
	public static final RegistryObject<EntityType<DilophosaurusSkeleton>> DILOPHOSAURUS_SKELETON = REGISTER.register("dilophosaurus_skeleton", () -> EntityType.Builder.<DilophosaurusSkeleton>of(DilophosaurusSkeleton::new, MobCategory.MISC).sized(1.0F, 2.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dilophosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<SarahsaurusSkeleton>> SARAHSAURUS_SKELETON = REGISTER.register("sarahsaurus_skeleton", () -> EntityType.Builder.<SarahsaurusSkeleton>of(SarahsaurusSkeleton::new, MobCategory.MISC).sized(1.0F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sarahsaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<ScelidosaurusSkeleton>> SCELIDOSAURUS_SKELETON = REGISTER.register("scelidosaurus_skeleton", () -> EntityType.Builder.<ScelidosaurusSkeleton>of(ScelidosaurusSkeleton::new, MobCategory.MISC).sized(1.0F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "scelidosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<AllosaurusSkeleton>> ALLOSAURUS_SKELETON = REGISTER.register("allosaurus_skeleton", () -> EntityType.Builder.<AllosaurusSkeleton>of(AllosaurusSkeleton::new, MobCategory.MISC).sized(1.25F, 2.8125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "allosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<CeratosaurusSkeleton>> CERATOSAURUS_SKELETON = REGISTER.register("ceratosaurus_skeleton", () -> EntityType.Builder.<CeratosaurusSkeleton>of(CeratosaurusSkeleton::new, MobCategory.MISC).sized(0.875F, 2.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ceratosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<StegosaurusSkeleton>> STEGOSAURUS_SKELETON = REGISTER.register("stegosaurus_skeleton", () -> EntityType.Builder.<StegosaurusSkeleton>of(StegosaurusSkeleton::new, MobCategory.MISC).sized(1.5F, 2.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "stegosaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<CoelophysisSkeleton>> COELOPHYSIS_SKELETON = REGISTER.register("coelophysis_skeleton", () -> EntityType.Builder.<CoelophysisSkeleton>of(CoelophysisSkeleton::new, MobCategory.MISC).sized(0.75F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "coelophysis_skeleton").toString()));
	public static final RegistryObject<EntityType<DesmatosuchusSkeleton>> DESMATOSUCHUS_SKELETON = REGISTER.register("desmatosuchus_skeleton", () -> EntityType.Builder.<DesmatosuchusSkeleton>of(DesmatosuchusSkeleton::new, MobCategory.MISC).sized(1.25F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "desmatosuchus_skeleton").toString()));
	public static final RegistryObject<EntityType<PostosuchusSkeleton>> POSTOSUCHUS_SKELETON = REGISTER.register("postosuchus_skeleton", () -> EntityType.Builder.<PostosuchusSkeleton>of(PostosuchusSkeleton::new, MobCategory.MISC).sized(1.0F, 1.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "postosuchus_skeleton").toString()));
	public static final RegistryObject<EntityType<HerrerasaurusSkeleton>> HERRERASAURUS_SKELETON = REGISTER.register("herrerasaurus_skeleton", () -> EntityType.Builder.<HerrerasaurusSkeleton>of(HerrerasaurusSkeleton::new, MobCategory.MISC).sized(0.625F, 1.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "herrerasaurus_skeleton").toString()));
	public static final RegistryObject<EntityType<IschigualastiaSkeleton>> ISCHIGUALASTIA_SKELETON = REGISTER.register("ischigualastia_skeleton", () -> EntityType.Builder.<IschigualastiaSkeleton>of(IschigualastiaSkeleton::new, MobCategory.MISC).sized(1.25F, 1.9375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ischigualastia_skeleton").toString()));
	public static final RegistryObject<EntityType<SaurosuchusSkeleton>> SAUROSUCHUS_SKELETON = REGISTER.register("saurosuchus_skeleton", () -> EntityType.Builder.<SaurosuchusSkeleton>of(SaurosuchusSkeleton::new, MobCategory.MISC).sized(0.75F, 1.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "saurosuchus_skeleton").toString()));
	
	//Fish
	public static final RegistryObject<EntityType<Acipenser>> ACIPENSER = REGISTER.register("acipenser", () -> EntityType.Builder.<Acipenser>of(Acipenser::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "acipenser").toString()));
	public static final RegistryObject<EntityType<Arganodus>> ARGANODUS = REGISTER.register("arganodus", () -> EntityType.Builder.<Arganodus>of(Arganodus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "arganodus").toString()));
	public static final RegistryObject<EntityType<Ceratodus>> CERATODUS = REGISTER.register("ceratodus", () -> EntityType.Builder.<Ceratodus>of(Ceratodus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ceratodus").toString()));
	public static final RegistryObject<EntityType<Chinlea>> CHINLEA = REGISTER.register("chinlea", () -> EntityType.Builder.<Chinlea>of(Chinlea::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "chinlea").toString()));
	public static final RegistryObject<EntityType<Cyclurus>> CYCLURUS = REGISTER.register("cyclurus", () -> EntityType.Builder.<Cyclurus>of(Cyclurus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "cyclurus").toString()));
	public static final RegistryObject<EntityType<Gar>> GAR = REGISTER.register("gar", () -> EntityType.Builder.<Gar>of(Gar::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "gar").toString()));
	public static final RegistryObject<EntityType<Lonchidion>> LONCHIDION = REGISTER.register("lonchidion", () -> EntityType.Builder.<Lonchidion>of(Lonchidion::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "lonchidion").toString()));
	public static final RegistryObject<EntityType<Melvius>> MELVIUS = REGISTER.register("melvius", () -> EntityType.Builder.<Melvius>of(Melvius::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "melvius").toString()));
	public static final RegistryObject<EntityType<Mooreodontus>> MOOREODONTUS = REGISTER.register("mooreodontus", () -> EntityType.Builder.<Mooreodontus>of(Mooreodontus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "mooreodontus").toString()));
	public static final RegistryObject<EntityType<Myledaphus>> MYLEDAPHUS = REGISTER.register("myledaphus", () -> EntityType.Builder.<Myledaphus>of(Myledaphus::new, MobCategory.WATER_AMBIENT).sized(0.6875F, 0.2F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "myledaphus").toString()));
	public static final RegistryObject<EntityType<Potamoceratodus>> POTAMOCERATODUS = REGISTER.register("potamoceratodus", () -> EntityType.Builder.<Potamoceratodus>of(Potamoceratodus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "potamoceratodus").toString()));
	public static final RegistryObject<EntityType<Saurichthys>> SAURICHTHYS = REGISTER.register("saurichthys", () -> EntityType.Builder.<Saurichthys>of(Saurichthys::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "saurichthys").toString()));
	public static final RegistryObject<EntityType<Harenaichthys>> HARENAICHTHYS = REGISTER.register("harenaichthys", () -> EntityType.Builder.<Harenaichthys>of(Harenaichthys::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "herenaichthys").toString()));
	public static final RegistryObject<EntityType<Protopsephurus>> PROTOPSEPHURUS = REGISTER.register("protopsephurus", () -> EntityType.Builder.<Protopsephurus>of(Protopsephurus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "protopsephurus").toString()));
	public static final RegistryObject<EntityType<Sinamia>> SINAMIA = REGISTER.register("sinamia", () -> EntityType.Builder.<Sinamia>of(Sinamia::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sinamia").toString()));
	public static final RegistryObject<EntityType<Yanosteus>> YANOSTEUS = REGISTER.register("yanosteus", () -> EntityType.Builder.<Yanosteus>of(Yanosteus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "yanosteus").toString()));
	public static final RegistryObject<EntityType<Parapsephurus>> PARAPSEPHURUS = REGISTER.register("parapsephurus", () -> EntityType.Builder.<Parapsephurus>of(Parapsephurus::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "parapsephurus").toString()));
	public static final RegistryObject<EntityType<Lepidotes>> LEPIDOTES = REGISTER.register("lepidotes", () -> EntityType.Builder.<Lepidotes>of(Lepidotes::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "lepidotes").toString()));
	public static final RegistryObject<EntityType<Chungkingichthys>> CHUNGKINGICHTHYS = REGISTER.register("chungkingichthys", () -> EntityType.Builder.<Chungkingichthys>of(Chungkingichthys::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "chungkingichthys").toString()));
	public static final RegistryObject<EntityType<Morrolepis>> MORROLEPIS = REGISTER.register("morrolepis", () -> EntityType.Builder.<Morrolepis>of(Morrolepis::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "morrolepis").toString()));
	public static final RegistryObject<EntityType<Ophiopsis>> OPHIOPSIS = REGISTER.register("ophiopsis", () -> EntityType.Builder.<Ophiopsis>of(Ophiopsis::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ophiopsis").toString()));
	
	public static final RegistryObject<EntityType<CeratodusCocoon>> CERATODUS_COCOON = REGISTER.register("ceratodus_cocoon", () -> EntityType.Builder.<CeratodusCocoon>of(CeratodusCocoon::new, MobCategory.AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ceratodus_cocoon").toString()));
	public static final RegistryObject<EntityType<PotamoceratodusCocoon>> POTAMOCERATODUS_COCOON = REGISTER.register("potamoceratodus_cocoon", () -> EntityType.Builder.<PotamoceratodusCocoon>of(PotamoceratodusCocoon::new, MobCategory.AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "potamoceratodus_cocoon").toString()));
	public static final RegistryObject<EntityType<ArganodusCocoon>> ARGANODUS_COCOON = REGISTER.register("arganodus_cocoon", () -> EntityType.Builder.<ArganodusCocoon>of(ArganodusCocoon::new, MobCategory.AMBIENT).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "arganodus_cocoon").toString()));
	
	//Hell Creek
	public static final RegistryObject<EntityType<Ankylosaurus>> ANKYLOSAURUS = REGISTER.register("ankylosaurus", () -> EntityType.Builder.<Ankylosaurus>of(Ankylosaurus::new, MobCategory.CREATURE).sized(2F, 2F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ankylosaurus").toString()));
	public static final RegistryObject<EntityType<Anzu>> ANZU = REGISTER.register("anzu", () -> EntityType.Builder.<Anzu>of(Anzu::new, MobCategory.CREATURE).sized(0.875F, 2.3125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "anzu").toString()));
	public static final RegistryObject<EntityType<Basilemys>> BASILEMYS = REGISTER.register("basilemys", () -> EntityType.Builder.<Basilemys>of(Basilemys::new, MobCategory.CREATURE).sized(0.75F, 0.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "basilemys").toString()));
	public static final RegistryObject<EntityType<Brachychampsa>> BRACHYCHAMPSA = REGISTER.register("brachychampsa", () -> EntityType.Builder.<Brachychampsa>of(Brachychampsa::new, MobCategory.CREATURE).sized(0.875F, 0.5625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "brachychampsa").toString()));
	public static final RegistryObject<EntityType<Dakotaraptor>> DAKOTARAPTOR = REGISTER.register("dakotaraptor", () -> EntityType.Builder.<Dakotaraptor>of(Dakotaraptor::new, MobCategory.CREATURE).sized(0.875F, 2.15F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dakotaraptor").toString()));
	public static final RegistryObject<EntityType<Didelphodon>> DIDELPHODON = REGISTER.register("didelphodon", () -> EntityType.Builder.<Didelphodon>of(Didelphodon::new, MobCategory.CREATURE).sized(0.35F, 0.4F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "didelphodon").toString()));
	public static final RegistryObject<EntityType<Edmontosaurus>> EDMONTOSAURUS = REGISTER.register("edmontosaurus", () -> EntityType.Builder.<Edmontosaurus>of(Edmontosaurus::new, MobCategory.CREATURE).sized(2.125F, 4.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "edmontosaurus").toString()));
	public static final RegistryObject<EntityType<Ornithomimus>> ORNITHOMIMUS = REGISTER.register("ornithomimus", () -> EntityType.Builder.<Ornithomimus>of(Ornithomimus::new, MobCategory.CREATURE).sized(0.75F, 2.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ornithomimus").toString()));
	public static final RegistryObject<EntityType<Pachycephalosaurus>> PACHYCEPHALOSAURUS = REGISTER.register("pachycephalosaurus", () -> EntityType.Builder.<Pachycephalosaurus>of(Pachycephalosaurus::new, MobCategory.CREATURE).sized(0.875F, 1.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "pachycephalosaurus").toString()));
	public static final RegistryObject<EntityType<Palaeosaniwa>> PALAEOSANIWA = REGISTER.register("palaeosaniwa", () -> EntityType.Builder.<Palaeosaniwa>of(Palaeosaniwa::new, MobCategory.CREATURE).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "palaeosaniwa").toString()));
	public static final RegistryObject<EntityType<Thescelosaurus>> THESCELOSAURUS = REGISTER.register("thescelosaurus", () -> EntityType.Builder.<Thescelosaurus>of(Thescelosaurus::new, MobCategory.CREATURE).sized(0.55F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "thescelosaurus").toString()));
//	public static final RegistryObject<EntityType<Thoracosaurus>> THORACOSAURUS = REGISTER.register("thoracosaurus", () -> EntityType.Builder.<Thoracosaurus>of(Thoracosaurus::new, MobCategory.CREATURE).sized(1, 1).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "thoracosaurus").toString()));
	public static final RegistryObject<EntityType<Triceratops>> TRICERATOPS = REGISTER.register("triceratops", () -> EntityType.Builder.<Triceratops>of(Triceratops::new, MobCategory.CREATURE).sized(2F, 2.6F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "triceratops").toString()));
	public static final RegistryObject<EntityType<Tyrannosaurus>> TYRANNOSAURUS = REGISTER.register("tyrannosaurus", () -> EntityType.Builder.<Tyrannosaurus>of(Tyrannosaurus::new, MobCategory.CREATURE).sized(2F, 4F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "tyrannosaurus").toString()));
	
	//Djadochta
	public static final RegistryObject<EntityType<Aepyornithomimus>> AEPYORNITHOMIMUS = REGISTER.register("aepyornithomimus", () -> EntityType.Builder.<Aepyornithomimus>of(Aepyornithomimus::new, MobCategory.CREATURE).sized(0.9375F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "aepyornithomimus").toString()));
	public static final RegistryObject<EntityType<Byronosaurus>> BYRONOSAURUS = REGISTER.register("byronosaurus", () -> EntityType.Builder.<Byronosaurus>of(Byronosaurus::new, MobCategory.CREATURE).sized(0.375F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "byronosaurus").toString()));
	public static final RegistryObject<EntityType<Citipati>> CITIPATI = REGISTER.register("citipati", () -> EntityType.Builder.<Citipati>of(Citipati::new, MobCategory.CREATURE).sized(0.5625F, 1.9F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "citipati").toString()));
	public static final RegistryObject<EntityType<Goyocephale>> GOYOCEPHALE = REGISTER.register("goyocephale", () -> EntityType.Builder.<Goyocephale>of(Goyocephale::new, MobCategory.CREATURE).sized(0.6F, 0.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "goyocephale").toString()));
	public static final RegistryObject<EntityType<Halszkaraptor>> HALSZKARAPTOR = REGISTER.register("halszkaraptor", () -> EntityType.Builder.<Halszkaraptor>of(Halszkaraptor::new, MobCategory.CREATURE).sized(0.35F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "halszkaraptor").toString()));
	public static final RegistryObject<EntityType<Kol>> KOL = REGISTER.register("kol", () -> EntityType.Builder.<Kol>of(Kol::new, MobCategory.CREATURE).sized(0.5F, 1.0625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "kol").toString()));
	public static final RegistryObject<EntityType<Oviraptor>> OVIRAPTOR = REGISTER.register("oviraptor", () -> EntityType.Builder.<Oviraptor>of(Oviraptor::new, MobCategory.CREATURE).sized(0.5F, 1.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "oviraptor").toString()));
	public static final RegistryObject<EntityType<Pinacosaurus>> PINACOSAURUS = REGISTER.register("pinacosaurus", () -> EntityType.Builder.<Pinacosaurus>of(Pinacosaurus::new, MobCategory.CREATURE).sized(2, 1.1F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "pinacosaurus").toString()));
	public static final RegistryObject<EntityType<Plesiohadros>> PLESIOHADROS = REGISTER.register("plesiohadros", () -> EntityType.Builder.<Plesiohadros>of(Plesiohadros::new, MobCategory.CREATURE).sized(1.25F, 2).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "plesiohadros").toString()));
	public static final RegistryObject<EntityType<Protoceratops>> PROTOCERATOPS = REGISTER.register("protoceratops", () -> EntityType.Builder.<Protoceratops>of(Protoceratops::new, MobCategory.CREATURE).sized(0.5F, 0.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "protoceratops").toString()));
	public static final RegistryObject<EntityType<Udanoceratops>> UDANOCERATOPS = REGISTER.register("udanoceratops", () -> EntityType.Builder.<Udanoceratops>of(Udanoceratops::new, MobCategory.CREATURE).sized(1.0F, 1.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "udanoceratops").toString()));
	public static final RegistryObject<EntityType<Telmasaurus>> TELMASAURUS = REGISTER.register("telmasaurus", () -> EntityType.Builder.<Telmasaurus>of(Telmasaurus::new, MobCategory.CREATURE).sized(1, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "telmasaurus").toString()));
	public static final RegistryObject<EntityType<Velociraptor>> VELOCIRAPTOR = REGISTER.register("velociraptor", () -> EntityType.Builder.<Velociraptor>of(Velociraptor::new, MobCategory.CREATURE).sized(0.3125F, 0.8F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "velociraptor").toString()));
	
	public static final RegistryObject<EntityType<DermestidBeetle>> DERMESTID_BEETLE = REGISTER.register("dermestid_beetle", () -> EntityType.Builder.<DermestidBeetle>of(DermestidBeetle::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dermestid_beetle").toString()));
	public static final RegistryObject<EntityType<Gobiulus>> GOBIULUS = REGISTER.register("gobiulus", () -> EntityType.Builder.<Gobiulus>of(Gobiulus::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "gobiulus").toString()));
	public static final RegistryObject<EntityType<Cephaloleichnites>> CEPHALOLEICHNITES = REGISTER.register("cephaloleichnites", () -> EntityType.Builder.<Cephaloleichnites>of(Cephaloleichnites::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "cephaloleichnites").toString()));
	public static final RegistryObject<EntityType<Apoclion>> APOCLION = REGISTER.register("apoclion", () -> EntityType.Builder.<Apoclion>of(Apoclion::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "apoclion").toString()));
	public static final RegistryObject<EntityType<Cretaraneus>> CRETARANEUS = REGISTER.register("cretaraneus", () -> EntityType.Builder.<Cretaraneus>of(Cretaraneus::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "cretaraneus").toString()));
	public static final RegistryObject<EntityType<Liaonemobius>> LIAONEMOBIUS = REGISTER.register("liaonemobius", () -> EntityType.Builder.<Liaonemobius>of(Liaonemobius::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "liaonemobius").toString()));
	public static final RegistryObject<EntityType<Parapleurites>> PARAPLEURITES = REGISTER.register("parapleurites", () -> EntityType.Builder.<Parapleurites>of(Parapleurites::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "parapleurites").toString()));
	public static final RegistryObject<EntityType<Eopolis>> EOPOLIS = REGISTER.register("eopolis", () -> EntityType.Builder.<Eopolis>of(Eopolis::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "eopolis").toString()));
	public static final RegistryObject<EntityType<Cylindricum>> CYLINDRICUM = REGISTER.register("cylindricum", () -> EntityType.Builder.<Cylindricum>of(Cylindricum::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "cylindricum").toString()));
	public static final RegistryObject<EntityType<Rhipidoblattina>> RHIPIDOBLATTINA = REGISTER.register("rhipidoblattina", () -> EntityType.Builder.<Rhipidoblattina>of(Rhipidoblattina::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "rhipidoblattina").toString()));
	public static final RegistryObject<EntityType<Cicadocoris>> CICADOCORIS = REGISTER.register("cicadocoris", () -> EntityType.Builder.<Cicadocoris>of(Cicadocoris::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "cicadocoris").toString()));
	public static final RegistryObject<EntityType<Mesoforficula>> MESOFORFICULA = REGISTER.register("mesoforficula", () -> EntityType.Builder.<Mesoforficula>of(Mesoforficula::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "mesoforficula").toString()));
	public static final RegistryObject<EntityType<Aboilus>> ABOILUS = REGISTER.register("aboilus", () -> EntityType.Builder.<Aboilus>of(Aboilus::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "aboilus").toString()));
	public static final RegistryObject<EntityType<Paleohelcura>> PALEOHELCURA = REGISTER.register("paleohelcura", () -> EntityType.Builder.<Paleohelcura>of(Paleohelcura::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "paleohelcura").toString()));
	public static final RegistryObject<EntityType<Octopodichnus>> OCTOPODICHNUS = REGISTER.register("octopodichnus", () -> EntityType.Builder.<Octopodichnus>of(Octopodichnus::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "octopodichnus").toString()));
	public static final RegistryObject<EntityType<Diplichnites>> DIPLICHNITES = REGISTER.register("diplichnites", () -> EntityType.Builder.<Diplichnites>of(Diplichnites::new, MobCategory.AMBIENT).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "diplichnites").toString()));
	
	//Yixian
	public static final RegistryObject<EntityType<Beipiaosaurus>> BEIPIAOSAURUS = REGISTER.register("beipiaosaurus", () -> EntityType.Builder.<Beipiaosaurus>of(Beipiaosaurus::new, MobCategory.CREATURE).sized(0.4375F, 1.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "beipiaosaurus").toString()));
	public static final RegistryObject<EntityType<Changyuraptor>> CHANGYURAPTOR = REGISTER.register("changyuraptor", () -> EntityType.Builder.<Changyuraptor>of(Changyuraptor::new, MobCategory.CREATURE).sized(0.3125F, 0.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "beipiaosaurus").toString()));
	public static final RegistryObject<EntityType<Dilong>> DILONG = REGISTER.register("dilong", () -> EntityType.Builder.<Dilong>of(Dilong::new, MobCategory.CREATURE).sized(0.375F, 0.625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dilong").toString()));
	public static final RegistryObject<EntityType<Dongbeititan>> DONGBEITITAN = REGISTER.register("dongbeititan", () -> EntityType.Builder.<Dongbeititan>of(Dongbeititan::new, MobCategory.CREATURE).sized(2.25F, 3.125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dongbeititan").toString()));
	public static final RegistryObject<EntityType<Incisivosaurus>> INCISIVOSAURUS = REGISTER.register("incisivosaurus", () -> EntityType.Builder.<Incisivosaurus>of(Incisivosaurus::new, MobCategory.CREATURE).sized(0.3125F, 0.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "incisivosaurus").toString()));
	public static final RegistryObject<EntityType<Jinzhousaurus>> JINZHOUSAURUS = REGISTER.register("jinzhousaurus", () -> EntityType.Builder.<Jinzhousaurus>of(Jinzhousaurus::new, MobCategory.CREATURE).sized(1.25F, 2.3125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "jinzhousaurus").toString()));
	public static final RegistryObject<EntityType<Liaoningosaurus>> LIAONINGOSAURUS = REGISTER.register("liaoningosaurus", () -> EntityType.Builder.<Liaoningosaurus>of(Liaoningosaurus::new, MobCategory.AMBIENT).sized(1, 0.875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "liaoningosaurus").toString()));
	public static final RegistryObject<EntityType<Psittacosaurus>> PSITTACOSAURUS = REGISTER.register("psittacosaurus", () -> EntityType.Builder.<Psittacosaurus>of(Psittacosaurus::new, MobCategory.CREATURE).sized(0.5F, 0.9375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "psittacosaurus").toString()));
	public static final RegistryObject<EntityType<Repenomamus>> REPENOMAMUS = REGISTER.register("repenomamus", () -> EntityType.Builder.<Repenomamus>of(Repenomamus::new, MobCategory.CREATURE).sized(0.3125F, 0.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "repenomamus").toString()));
	public static final RegistryObject<EntityType<Ruixinia>> RUIXINIA = REGISTER.register("ruixinia", () -> EntityType.Builder.<Ruixinia>of(Ruixinia::new, MobCategory.CREATURE).sized(1.5F, 2.625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ruixinia").toString()));
	public static final RegistryObject<EntityType<Sinosauropteryx>> SINOSAUROPTERYX = REGISTER.register("sinosauropteryx", () -> EntityType.Builder.<Sinosauropteryx>of(Sinosauropteryx::new, MobCategory.CREATURE).sized(0.25F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sinosauropteryx").toString()));
	public static final RegistryObject<EntityType<Yutyrannus>> YUTYRANNUS = REGISTER.register("yutyrannus", () -> EntityType.Builder.<Yutyrannus>of(Yutyrannus::new, MobCategory.CREATURE).sized(1.0F, 2.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "yutyrannus").toString()));
	public static final RegistryObject<EntityType<Zhenyuanlong>> ZHENYUANLONG = REGISTER.register("zhenyuanlong", () -> EntityType.Builder.<Zhenyuanlong>of(Zhenyuanlong::new, MobCategory.CREATURE).sized(0.375F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "zhenyuanlong").toString()));
	
	//Kayenta
	public static final RegistryObject<EntityType<Calsoyasuchus>> CALSOYASUCHUS = REGISTER.register("calsoyasuchus", () -> EntityType.Builder.<Calsoyasuchus>of(Calsoyasuchus::new, MobCategory.CREATURE).sized(0.5F, 0.3F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "calsoyasuchus").toString()));
	public static final RegistryObject<EntityType<Dilophosaurus>> DILOPHOSAURUS = REGISTER.register("dilophosaurus", () -> EntityType.Builder.<Dilophosaurus>of(Dilophosaurus::new, MobCategory.CREATURE).sized(1, 2.2F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dilophosaurus").toString()));
	public static final RegistryObject<EntityType<Kayentachelys>> KAYENTACHELYS = REGISTER.register("kayentachelys", () -> EntityType.Builder.<Kayentachelys>of(Kayentachelys::new, MobCategory.CREATURE).sized(0.75F, 0.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "kayentachelys").toString()));
	public static final RegistryObject<EntityType<Kayentasuchus>> KAYENTASUCHUS = REGISTER.register("kayentasuchus", () -> EntityType.Builder.<Kayentasuchus>of(Kayentasuchus::new, MobCategory.CREATURE).sized(0.3125F, 0.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "kayentasuchus").toString()));
	public static final RegistryObject<EntityType<Kayentatherium>> KAYENTATHERIUM = REGISTER.register("kayentatherium", () -> EntityType.Builder.<Kayentatherium>of(Kayentatherium::new, MobCategory.CREATURE).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "kayentatherium").toString()));
	public static final RegistryObject<EntityType<Kayentavenator>> KAYENTAVENATOR = REGISTER.register("kayentavenator", () -> EntityType.Builder.<Kayentavenator>of(Kayentavenator::new, MobCategory.CREATURE).sized(0.6875F, 1.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "kayentavenator").toString()));
	public static final RegistryObject<EntityType<Megapnosaurus>> MEGAPNOSAURUS = REGISTER.register("megapnosaurus", () -> EntityType.Builder.<Megapnosaurus>of(Megapnosaurus::new, MobCategory.CREATURE).sized(0.75F, 0.85F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "megapnosaurus").toString()));
	public static final RegistryObject<EntityType<Sarahsaurus>> SARAHSAURUS = REGISTER.register("sarahsaurus", () -> EntityType.Builder.<Sarahsaurus>of(Sarahsaurus::new, MobCategory.CREATURE).sized(1, 1.45F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sarahsaurus").toString()));
	public static final RegistryObject<EntityType<Scelidosaurus>> SCELIDOSAURUS = REGISTER.register("scelidosaurus", () -> EntityType.Builder.<Scelidosaurus>of(Scelidosaurus::new, MobCategory.CREATURE).sized(1, 1).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "scelidosaurus").toString()));
	public static final RegistryObject<EntityType<Scutellosaurus>> SCUTELLOSAURUS = REGISTER.register("scutellosaurus", () -> EntityType.Builder.<Scutellosaurus>of(Scutellosaurus::new, MobCategory.CREATURE).sized(0.6F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "scutellosaurus").toString()));
	
	//Morrison
	public static final RegistryObject<EntityType<Alcovasaurus>> ALCOVASAURUS = REGISTER.register("alcovasaurus", () -> EntityType.Builder.<Alcovasaurus>of(Alcovasaurus::new, MobCategory.CREATURE).sized(1.25F, 2.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "alcovasaurus").toString()));
	public static final RegistryObject<EntityType<Allosaurus>> ALLOSAURUS = REGISTER.register("allosaurus", () -> EntityType.Builder.<Allosaurus>of(Allosaurus::new, MobCategory.CREATURE).sized(1.25F, 3.0F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "allosaurus").toString()));
//	public static final RegistryObject<EntityType<Brachiosaurus>> BRACHIOSAURUS = REGISTER.register("brachiosaurus", () -> EntityType.Builder.<Brachiosaurus>of(Brachiosaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "brachiosaurus").toString()));
//	public static final RegistryObject<EntityType<Brontosaurus>> BRONTOSAURUS = REGISTER.register("brontosaurus", () -> EntityType.Builder.<Brontosaurus>of(Brontosaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "brontosaurus").toString()));
	public static final RegistryObject<EntityType<Camarasaurus>> CAMARASAURUS = REGISTER.register("camarasaurus", () -> EntityType.Builder.<Camarasaurus>of(Camarasaurus::new, MobCategory.CREATURE).sized(3.125F, 8.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "camarasaurus").toString()));
	public static final RegistryObject<EntityType<Camptosaurus>> CAMPTOSAURUS = REGISTER.register("camptosaurus", () -> EntityType.Builder.<Camptosaurus>of(Camptosaurus::new, MobCategory.CREATURE).sized(1, 2.1875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "camptosaurus").toString()));
	public static final RegistryObject<EntityType<Ceratosaurus>> CERATOSAURUS = REGISTER.register("ceratosaurus", () -> EntityType.Builder.<Ceratosaurus>of(Ceratosaurus::new, MobCategory.CREATURE).sized(0.875F, 2F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ceratosaurus").toString()));
	public static final RegistryObject<EntityType<Diablophis>> DIABLOPHIS = REGISTER.register("diablophis", () -> EntityType.Builder.<Diablophis>of(Diablophis::new, MobCategory.CREATURE).sized(0.4375F, 0.125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "diablophis").toString()));
//	public static final RegistryObject<EntityType<Diplodocus>> DIPLODOCUS = REGISTER.register("diplodocus", () -> EntityType.Builder.<Diplodocus>of(Diplodocus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "diplodocus").toString()));
	public static final RegistryObject<EntityType<Dryosaurus>> DRYOSAURUS = REGISTER.register("dryosaurus", () -> EntityType.Builder.<Dryosaurus>of(Dryosaurus::new, MobCategory.CREATURE).sized(0.875F, 2F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "dryosaurus").toString()));
	public static final RegistryObject<EntityType<Eilenodon>> EILENODON = REGISTER.register("eilenodon", () -> EntityType.Builder.<Eilenodon>of(Eilenodon::new, MobCategory.CREATURE).sized(0.25F, 0.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "eilenodon").toString()));
	public static final RegistryObject<EntityType<Gargoyleosaurus>> GARGOYLEOSAURUS = REGISTER.register("gargoyleosaurus", () -> EntityType.Builder.<Gargoyleosaurus>of(Gargoyleosaurus::new, MobCategory.CREATURE).sized(0.6875F, 0.8125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "gargoyleosaurus").toString()));
	public static final RegistryObject<EntityType<Hesperornithoides>> HESPERORNITHOIDES = REGISTER.register("hesperornithoides", () -> EntityType.Builder.<Hesperornithoides>of(Hesperornithoides::new, MobCategory.CREATURE).sized(0.375F, 0.55F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "hesperornithoides").toString()));
	public static final RegistryObject<EntityType<Macelognathus>> MACELOGNATHUS = REGISTER.register("macelognathus", () -> EntityType.Builder.<Macelognathus>of(Macelognathus::new, MobCategory.CREATURE).sized(0.3125F, 0.8F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "macelognathus").toString()));
//	public static final RegistryObject<EntityType<Maraapunisaurus>> MARAAPUNISAURUS = REGISTER.register("maraapunisaurus", () -> EntityType.Builder.<Maraapunisaurus>of(Maraapunisaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "maraapunisaurus").toString()));
	public static final RegistryObject<EntityType<Stegosaurus>> STEGOSAURUS = REGISTER.register("stegosaurus", () -> EntityType.Builder.<Stegosaurus>of(Stegosaurus::new, MobCategory.CREATURE).sized(1.5F, 2.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "stegosaurus").toString()));
	public static final RegistryObject<EntityType<Tanycolagreus>> TANYCOLAGREUS = REGISTER.register("tanycolagreus", () -> EntityType.Builder.<Tanycolagreus>of(Tanycolagreus::new, MobCategory.CREATURE).sized(0.5F, 1.375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "tanycolagreus").toString()));
	public static final RegistryObject<EntityType<Torvosaurus>> TORVOSAURUS = REGISTER.register("torvosaurus", () -> EntityType.Builder.<Torvosaurus>of(Torvosaurus::new, MobCategory.CREATURE).sized(1.25F, 2.9375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "torvosaurus").toString()));
	
	//Shaximiao
//	public static final RegistryObject<EntityType<Abrosaurus>> ABROSAURUS = REGISTER.register("abrosaurus", () -> EntityType.Builder.<Abrosaurus>of(Abrosaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "abrosaurus").toString()));
	public static final RegistryObject<EntityType<Agilisaurus>> AGILISAURUS = REGISTER.register("agilisaurus", () -> EntityType.Builder.<Agilisaurus>of(Agilisaurus::new, MobCategory.CREATURE).sized(0.375F, 0.625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "agilisaurus").toString()));
	public static final RegistryObject<EntityType<Bashanosaurus>> BASHANOSAURUS = REGISTER.register("bashanosaurus", () -> EntityType.Builder.<Bashanosaurus>of(Bashanosaurus::new, MobCategory.CREATURE).sized(0.75F, 0.9375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "bashanosaurus").toString()));
	public static final RegistryObject<EntityType<Chuandongocoelurus>> CHUANDONGOCOELURUS = REGISTER.register("chuandongocoelurus", () -> EntityType.Builder.<Chuandongocoelurus>of(Chuandongocoelurus::new, MobCategory.CREATURE).sized(0.5F, 1.125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "chuandongocoelurus").toString()));
	public static final RegistryObject<EntityType<Gigantspinosaurus>> GIGANTSPINOSAURUS = REGISTER.register("gigantspinosaurus", () -> EntityType.Builder.<Gigantspinosaurus>of(Gigantspinosaurus::new, MobCategory.CREATURE).sized(1.25F, 1.6875F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "gigantspinosaurus").toString()));
//	public static final RegistryObject<EntityType<Huayangosaurus>> HUAYANGOSAURUS = REGISTER.register("huayangosaurus", () -> EntityType.Builder.<Huayangosaurus>of(Huayangosaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "huayangosaurus").toString()));
//	public static final RegistryObject<EntityType<Mamenchisaurus>> MAMENCHISAURUS = REGISTER.register("mamenchisaurus", () -> EntityType.Builder.<Mamenchisaurus>of(Mamenchisaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "mamenchisaurus").toString()));
//	public static final RegistryObject<EntityType<Omeisaurus>> OMEISAURUS = REGISTER.register("omeisaurus", () -> EntityType.Builder.<Omeisaurus>of(Omeisaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "omeisaurus").toString()));
//	public static final RegistryObject<EntityType<Sinraptor>> SINRAPTOR = REGISTER.register("sinraptor", () -> EntityType.Builder.<Sinraptor>of(Sinraptor::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sinraptor").toString()));
//	public static final RegistryObject<EntityType<Shunosaurus>> SHUNOSAURUS = REGISTER.register("shunosaurus", () -> EntityType.Builder.<Shunosaurus>of(Shunosaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "shunosaurus").toString()));
//	public static final RegistryObject<EntityType<Tuojiangosaurus>> TUOJIANGOSAURUS = REGISTER.register("tuojiangosaurus", () -> EntityType.Builder.<Tuojiangosaurus>of(Tuojiangosaurus::new, MobCategory.CREATURE).sized().build(new ResourceLocation(PrehistoricFauna.MOD_ID, "tuojiangosaurus").toString()));
	public static final RegistryObject<EntityType<Yandusaurus>> YANDUSAURUS = REGISTER.register("yandusaurus", () -> EntityType.Builder.<Yandusaurus>of(Yandusaurus::new, MobCategory.CREATURE).sized(0.625F, 1.125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "yandusaurus").toString()));
	public static final RegistryObject<EntityType<Yangchuanosaurus>> YANGCHUANOSAURUS = REGISTER.register("yangchuanosaurus", () -> EntityType.Builder.<Yangchuanosaurus>of(Yangchuanosaurus::new, MobCategory.CREATURE).sized(1.4375F, 2.1825F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "yangchuanosaurus").toString()));
	
	//Chinle
	public static final RegistryObject<EntityType<Coelophysis>> COELOPHYSIS = REGISTER.register("coelophysis", () -> EntityType.Builder.<Coelophysis>of(Coelophysis::new, MobCategory.CREATURE).sized(0.75F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "coelophysis").toString()));
	public static final RegistryObject<EntityType<Desmatosuchus>> DESMATOSUCHUS = REGISTER.register("desmatosuchus", () -> EntityType.Builder.<Desmatosuchus>of(Desmatosuchus::new, MobCategory.CREATURE).sized(1.25F, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "desmatosuchus").toString()));
	public static final RegistryObject<EntityType<Placerias>> PLACERIAS = REGISTER.register("placerias", () -> EntityType.Builder.<Placerias>of(Placerias::new, MobCategory.CREATURE).sized(1, 1.25F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "placerias").toString()));
	public static final RegistryObject<EntityType<Poposaurus>> POPOSAURUS = REGISTER.register("poposaurus", () -> EntityType.Builder.<Poposaurus>of(Poposaurus::new, MobCategory.CREATURE).sized(1, 1.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "poposaurus").toString()));
	public static final RegistryObject<EntityType<Postosuchus>> POSTOSUCHUS = REGISTER.register("postosuchus", () -> EntityType.Builder.<Postosuchus>of(Postosuchus::new, MobCategory.CREATURE).sized(1, 1.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "postosuchus").toString()));
	public static final RegistryObject<EntityType<Trilophosaurus>> TRILOPHOSAURUS = REGISTER.register("trilophosaurus", () -> EntityType.Builder.<Trilophosaurus>of(Trilophosaurus::new, MobCategory.CREATURE).sized(0.5F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "trilophosaurus").toString()));
	public static final RegistryObject<EntityType<Typothorax>> TYPOTHORAX = REGISTER.register("typothorax", () -> EntityType.Builder.<Typothorax>of(Typothorax::new, MobCategory.CREATURE).sized(1, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "typothorax").toString()));
	
	//Ischigualasto
	public static final RegistryObject<EntityType<Chromogisaurus>> CHROMOGISAURUS = REGISTER.register("chromogisaurus", () -> EntityType.Builder.<Chromogisaurus>of(Chromogisaurus::new, MobCategory.CREATURE).sized(0.375F, 0.8F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "chromogisaurus").toString()));
	public static final RegistryObject<EntityType<Exaeretodon>> EXAERETODON = REGISTER.register("exaeretodon", () -> EntityType.Builder.<Exaeretodon>of(Exaeretodon::new, MobCategory.CREATURE).sized(0.75F, 0.5625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "exaeretodon").toString()));
	public static final RegistryObject<EntityType<Herrerasaurus>> HERRERASAURUS = REGISTER.register("herrerasaurus", () -> EntityType.Builder.<Herrerasaurus>of(Herrerasaurus::new, MobCategory.CREATURE).sized(0.625F, 1.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "herrerasaurus").toString()));
	public static final RegistryObject<EntityType<Hyperodapedon>> HYPERODAPEDON = REGISTER.register("hyperodapedon", () -> EntityType.Builder.<Hyperodapedon>of(Hyperodapedon::new, MobCategory.CREATURE).sized(0.375F, 0.3125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "hyperodapedon").toString()));
	public static final RegistryObject<EntityType<Ischigualastia>> ISCHIGUALASTIA = REGISTER.register("ischigualastia", () -> EntityType.Builder.<Ischigualastia>of(Ischigualastia::new, MobCategory.CREATURE).sized(1.25F, 1.9375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "ischigualastia").toString()));
	public static final RegistryObject<EntityType<Saurosuchus>> SAUROSUCHUS = REGISTER.register("saurosuchus", () -> EntityType.Builder.<Saurosuchus>of(Saurosuchus::new, MobCategory.CREATURE).sized(0.75F, 1.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "saurosuchus").toString()));
	public static final RegistryObject<EntityType<Sillosuchus>> SILLOSUCHUS = REGISTER.register("sillosuchus", () -> EntityType.Builder.<Sillosuchus>of(Sillosuchus::new, MobCategory.CREATURE).sized(1.5F, 3.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "sillosuchus").toString()));
	
	public static final RegistryObject<EntityType<Henos>> HENOS = REGISTER.register("henos", () -> EntityType.Builder.<Henos>of(Henos::new, MobCategory.MONSTER).sized(1.3125F, 3.125F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "henos").toString()));
	public static final RegistryObject<EntityType<CaveSentinel>> CAVE_SENTINEL = REGISTER.register("cave_sentinel", () -> EntityType.Builder.<CaveSentinel>of(CaveSentinel::new, MobCategory.MONSTER).sized(1.5F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "cave_sentinel").toString()));
	public static final RegistryObject<EntityType<LandSentinel>> LAND_SENTINEL = REGISTER.register("land_sentinel", () -> EntityType.Builder.<LandSentinel>of(LandSentinel::new, MobCategory.MONSTER).sized(2F, 0.75F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "land_sentinel").toString()));
	public static final RegistryObject<EntityType<CorruptedTheropod>> CORRUPTED_THEROPOD = REGISTER.register("corrupted_theropod", () -> EntityType.Builder.<CorruptedTheropod>of(CorruptedTheropod::new, MobCategory.MONSTER).sized(2.375F, 4.4375F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "corrupted_theropod").toString()));
	
	public static final RegistryObject<EntityType<PFBoat>> BOAT = REGISTER.register("boat", () -> EntityType.Builder.<PFBoat>of(PFBoat::new, MobCategory.MISC).sized(1.375F, 0.5625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "boat").toString()));
	public static final RegistryObject<EntityType<PFChestBoat>> CHEST_BOAT = REGISTER.register("chest_boat", () -> EntityType.Builder.<PFChestBoat>of(PFChestBoat::new, MobCategory.MISC).sized(1.375F, 0.5625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "chest_boat").toString()));
	public static final RegistryObject<EntityType<PFRaft>> RAFT = REGISTER.register("raft", () -> EntityType.Builder.<PFRaft>of(PFRaft::new, MobCategory.MISC).sized(1.375F, 0.5625F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "raft").toString()));
	public static final RegistryObject<EntityType<Paleopainting>> PALEOPAINTING = REGISTER.register("paleopainting", () -> EntityType.Builder.<Paleopainting>of(Paleopainting::new, MobCategory.MISC).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "paleopainting").toString()));
	public static final RegistryObject<EntityType<WallFossil>> WALL_FOSSIL = REGISTER.register("wall_fossil", () -> EntityType.Builder.<WallFossil>of(WallFossil::new, MobCategory.MISC).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "wall_fossil").toString()));
	public static final RegistryObject<EntityType<FermentedGinkgoBerry>> FERMENTED_GINKGO_BERRY = REGISTER.register("fermented_ginkgo_berry", () -> EntityType.Builder.<FermentedGinkgoBerry>of(FermentedGinkgoBerry::new, MobCategory.MISC).sized(0.5F, 0.5F).build(new ResourceLocation(PrehistoricFauna.MOD_ID, "fermented_ginkgo_berry").toString()));
	
}
