package superlord.prehistoricfauna.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class ServerConfig {
	//Hell Creek Redwoods
	public final ForgeConfigSpec.IntValue acipenserHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue anzuHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue didelphodonHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue edmontosaurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue lepisosteusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue lonchidionHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue melviusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue pachycephalosaurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue palaeosaniwaHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue thoracosaurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekRedwoodsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekRedwoodsSpawnWeight;
	//Hell Creek Hardwood Forest
	public final ForgeConfigSpec.IntValue acipenserHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue anzuHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue didelphodonHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue edmontosaurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue lepisosteusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue lonchidionHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue melviusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue pachycephalosaurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue palaeosaniwaHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue thoracosaurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekHardwoodForestSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekHardwoodForestSpawnWeight;
	//Hell Creek Clearing
	public final ForgeConfigSpec.IntValue acipenserHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue anzuHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue didelphodonHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue edmontosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue lepisosteusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue lonchidionHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue melviusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue pachycephalosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue palaeosaniwaHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue thoracosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekClearingSpawnWeight;
	//Hell Creek Liriodendrites Hills
	public final ForgeConfigSpec.IntValue acipenserHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue edmontosaurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue lonchidionHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue pachycephalosaurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue thoracosaurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue melviusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue dideldophodonHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue lepisosteusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue palaeosaniwaHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekLiriodendritesHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekLiriodendritesHillsSpawnWeight;
	//Hell Creek Swamp
	public final ForgeConfigSpec.IntValue acipenserHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue lepisosteusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue edmontosaurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue didelphodonHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue lonchidionHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue melviusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue thoracosaurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue pachycephalosaurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue palaeosaniwaHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekSwampSpawnWeight;
	//Hell Creek River
	public final ForgeConfigSpec.IntValue acipenserHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue anzuHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue didelphodonHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue edmontosaurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue lepisosteusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue lonchidionHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue melviusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue pachycephalosaurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue palaeosaniwaHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue thoracosaurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekRiverSpawnWeight;
	//Morrison Savanna
	public final ForgeConfigSpec.IntValue stegosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue dryosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue allosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue hesperornithoidesMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue eilenodonMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue camarasaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelMorrisonSavannahSpawnWeight;
	//Morrison Hills
	public final ForgeConfigSpec.IntValue stegosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue dryosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue allosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue hesperornithoidesMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue eilenodonMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue camarasaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelMorrisonHillsSpawnWeight;
	//Ischigualasto Forest
	public final ForgeConfigSpec.IntValue exaeretodonIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue chromogisaurusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue herrerasaurusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue hyperodapedonIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue sillosuchusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue saurosuchusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ischigualastiaIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoForestSpawnWeight;
	//Ischigualasto Clearing
	public final ForgeConfigSpec.IntValue exaeretodonIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue chromogisaurusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue herrerasaurusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue hyperodapedonIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue sillosuchusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue saurosuchusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue ischigualastiaIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoClearingSpawnWeight;
	//Ischigualasto Hills
	public final ForgeConfigSpec.IntValue exaeretodonIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue chromogisaurusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue herrerasaurusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue hyperodapedonIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue sillosuchusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue saurosuchusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ischigualastiaIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoHillsSpawnWeight;
	//Ischigualasto River
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoRiverSpawnWeight;
	//Djadochta Dunes
	public final ForgeConfigSpec.IntValue protoceratopsDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue citipatiDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue velociraptorDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue aepyornithomimusDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue telmasaurusDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue pinacosaurusDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue plesiohadrosDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue oviraptorDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelDjadochtaDunesSpawnWeight;
	//Djadochta Alluvial Plains
	public final ForgeConfigSpec.IntValue protoceratopsDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue citipatiDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue velociraptorDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue aepyornithomimusDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue telmasaurusDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue pinacosaurusDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue plesiohadrosDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue oviraptorDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelDjadochtaAlluvialPlainsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelDjadochtaAlluvialPlainsSpawnWeight;
	//Djadochta Arroyo
	public final ForgeConfigSpec.IntValue protoceratopsDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue velociraptorDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue citipatiDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue aepyornithomimusDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue telmasaurusDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue pinacosaurusDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue plesiohadrosDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue oviraptorDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelDjadochtaArroyoSpawnWeight;
	//Kayenta Buttes
	public final ForgeConfigSpec.IntValue dilophosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue sarahsaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue scelidosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue scutellosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue megapnosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue kayentatheriumKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue calsoyasuchusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelKayentaButtesSpawnWeight;
	//Kayenta Desert
	public final ForgeConfigSpec.IntValue dilophosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue sarahsaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue scelidosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue scutellosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue megapnosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue kayentatheriumKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue calsoyasuchusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelKayentaDesertSpawnWeight;
	//Kayenta Dry Forest
	public final ForgeConfigSpec.IntValue dilophosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue sarahsaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue scelidosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue scutellosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue megapnosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue kayentatheriumKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue calsoyasuchusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelKayentaDryForestSpawnWeight;
	//Chinle Swamp
	public final ForgeConfigSpec.IntValue coelophysisChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue desmatosuchusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue placeriasChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue poposaurusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue postosuchusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue trilophosaurusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue typothoraxChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue chinleaChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleSwampSpawnWeight;
	//Chinle Flats
	public final ForgeConfigSpec.IntValue coelophysisChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue desmatosuchusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue placeriasChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue poposaurusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue postosuchusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue trilophosaurusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue typothoraxChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue chinleaChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleFlatsSpawnWeight;
	//Chinle River
	public final ForgeConfigSpec.IntValue chinleaChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleRiverSpawnWeight;
	//Chinle Wooded Mountains
	public final ForgeConfigSpec.IntValue coelophysisChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue desmatosuchusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue placeriasChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue poposaurusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue postosuchusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue trilophosaurusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue typothoraxChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue chinleaChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleWoodedMountainsSpawnWeight;

	public final ForgeConfigSpec.BooleanValue superSecretSetting;
	public final ForgeConfigSpec.IntValue cretaceousDimensionID;
	public final ForgeConfigSpec.IntValue jurassicDimensionID;
	public final ForgeConfigSpec.IntValue triassicDimensionID;
	public final ForgeConfigSpec.IntValue hellCreekHutMinDistance;
	public final ForgeConfigSpec.IntValue hellCreekHutMaxDistance;
	public final ForgeConfigSpec.IntValue morrisonHutMinDistance;
	public final ForgeConfigSpec.IntValue morrisonHutMaxDistance;
	public final ForgeConfigSpec.IntValue ischigualastoHutMinDistance;
	public final ForgeConfigSpec.IntValue ischigualastoHutMaxDistance;
	public final ForgeConfigSpec.IntValue djadochtaHutMinDistance;
	public final ForgeConfigSpec.IntValue djadochtaHutMaxDistance;
	public final ForgeConfigSpec.IntValue kayentaHutMinDistance;
	public final ForgeConfigSpec.IntValue kayentaHutMaxDistance;
	public final ForgeConfigSpec.IntValue chinleHutMinDistance;
	public final ForgeConfigSpec.IntValue chinleHutMaxDistance;
	public final ForgeConfigSpec.IntValue geologistCampMinDistance;
	public final ForgeConfigSpec.IntValue geologistCampMaxDistance;
	public final ForgeConfigSpec.IntValue timeTempleMinDistance;
	public final ForgeConfigSpec.IntValue timeTempleMaxDistance;
	public final ForgeConfigSpec.IntValue portalHubMinDistance;
	public final ForgeConfigSpec.IntValue portalHubMaxDistance;
	public final ForgeConfigSpec.BooleanValue spaceTimeContinuumWarping;
	public final ForgeConfigSpec.BooleanValue geologyHammerMining;
	public final ForgeConfigSpec.IntValue baseStoneWeight;
	public final ForgeConfigSpec.IntValue fossilWeight;
	public final ForgeConfigSpec.BooleanValue sleeping;
	public final ForgeConfigSpec.BooleanValue advancedHunger;
	public final ForgeConfigSpec.BooleanValue hungerDamage;
	public final ForgeConfigSpec.BooleanValue naturalEggBlockLaying;
	public final ForgeConfigSpec.BooleanValue naturalEggItemLaying;
	public final ForgeConfigSpec.BooleanValue hostileCarnivores;
	public final ForgeConfigSpec.BooleanValue unscheduledSleeping;
	public final ForgeConfigSpec.BooleanValue sauropodTrampling;
	
	public ServerConfig(final ForgeConfigSpec.Builder builder) {
		builder.push("Djadochta Formation");
		builder.push("Djadochta Alluvial Plains");
		this.aepyornithomimusDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Aepyornithomimus Djadochta Alluvial Plains Spawn Rate", "all", 2, 0, 300, "The spawn rate of Aepyornithomimus in the Djadochta Alluvial Plains biome. Default is 3");
		this.citipatiDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Citipati Djadochta Alluvial Plains Spawn Rate", "all", 5, 0, 300, "The spawn rate of Citipati in the Djadochta Alluvial Plains biome. Default is 5");
		this.oviraptorDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Oviraptor Djadochta Alluvial Plains Spawn Rate", "all", 2, 0, 300, "The spawn rate of Oviraptor in the Djadochta Alluvial Plains biome. Default is 2");
		this.pinacosaurusDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Pinacosaurus Djadochta Alluvial Plains Spawn Rate", "all", 5, 0, 300, "The spawn rate of Pinacosaurus in the Djadochta Alluvial Plains biome. Default is 5");
		this.plesiohadrosDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Plesiohadros Djadochta Alluvial Plains Spawn Rate", "all", 0, 0, 300, "The spawn rate of Plesiohadros in the Djadochta Alluvial Plains biome. Default is 0");
		this.protoceratopsDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Protoceratops Djadochta Alluvial Plains Spawn Rate", "all", 7, 0, 300, "The spawn rate of Protoceratops in the Djadochta Alluvial Plains biome. Default is 7");
		this.telmasaurusDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Telmasaurus Djadochta Alluvial Plains Spawn Rate", "all", 3, 0, 300, "The spawn rate of Telmasaurus in the Djadochta Alluvial Plains biome. Default is 3");
		this.velociraptorDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Velociraptor Djadochta Alluvial Plains Spawn Rate", "all", 6, 0, 300, "The spawn rate of Velociraptor in the Djadochta Alluvial Plains biome. Default is 6");
		this.caveSentinelDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Cave Sentinel Djaodochta Alluvial Plains Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Djadochta Alluvial Plains biome. Default is 5");
		this.landSentinelDjadochtaAlluvialPlainsSpawnWeight = buildInt(builder, "Land Sentinel Djadochta Alluvial Plains Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Djadochta Alluvial Plains biome. Default is 2");
		builder.pop();
		builder.push("Djadochta Arroyo");
		this.aepyornithomimusDjadochtaArroyoSpawnWeight = buildInt(builder, "Aepyornithomimus Djadochta Arroyo Spawn Rate", "all", 12, 0, 300, "The spawn rate of Aepyornithomimus in the Djadochta Arroyo biome. Default is 12");
		this.citipatiDjadochtaArroyoSpawnWeight = buildInt(builder, "Citipati Djadochta Arroyo Spawn Rate", "all", 5, 0, 300, "The spawn rate of Citipati in the Djadochta Arroyo biome. Default is 5");
		this.oviraptorDjadochtaArroyoSpawnWeight = buildInt(builder, "Oviraptor Djadochta Arroyo Spawn Rate", "all", 7, 0, 300, "The spawn rate of Oviraptor in the Djadochta Arroyo biome. Default is 7");
		this.pinacosaurusDjadochtaArroyoSpawnWeight = buildInt(builder, "Pinacosaurus Djadochta Arroyo Spawn Rate", "all", 7, 0, 300, "The spawn rate of Pinacosaurus in the Djadochta Arroyo biome. Default is 7");
		this.plesiohadrosDjadochtaArroyoSpawnWeight = buildInt(builder, "Plesiohadros Djadochta Arroyo Spawn Rate", "all", 8, 0, 300, "The spawn rate of Plesiohadros in the Djadochta Arroyo biome. Default is 8");
		this.protoceratopsDjadochtaArroyoSpawnWeight = buildInt(builder, "Protoceratops Djadochta Arroyo Spawn Rate", "all", 4, 0, 300, "The spawn rate of Protoceratops in the Djadochta Arroyo biome. Default is 4");
		this.telmasaurusDjadochtaArroyoSpawnWeight = buildInt(builder, "Telmasaurus Djadochta Arroyo Spawn Rate", "all", 2, 0, 300, "The spawn rate of Telmasauru in the Djadochta Arroyo biome. Default is 2");
		this.velociraptorDjadochtaArroyoSpawnWeight = buildInt(builder, "Velociraptor Djadochta Arroyo Spawn Rate", "all", 3, 0, 300, "The spawn rate of Velociraptor in the Djadochta Arroyo biome. Default is 3");
		this.caveSentinelDjadochtaArroyoSpawnWeight = buildInt(builder, "Cave Sentinel Djaodochta Arroyo Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Djadochta Arroyo biome. Default is 5");
		this.landSentinelDjadochtaArroyoSpawnWeight = buildInt(builder, "Land Sentinel Djadochta Arroyo Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Djadochta Arroyo biome. Default is 2");
		builder.pop();
		builder.push("Djadochta Dunes");
		this.aepyornithomimusDjadochtaDunesSpawnWeight = buildInt(builder, "Aepyornithomimus Djadochta Dunes Spawn Rate", "all", 2, 0, 300, "The spawn rate of Aepyornithomimus in the Djadochta Dunes biome. Default is 3");
		this.citipatiDjadochtaDunesSpawnWeight = buildInt(builder, "Citipati Djadochta Dunes Spawn Rate", "all", 5, 0, 300, "The spawn rate of Citipati in the Djadochta Dunes biome. Default is 5");
		this.oviraptorDjadochtaDunesSpawnWeight = buildInt(builder, "Oviraptor Djadochta Dunes Spawn Rate", "all", 2, 0, 300, "The spawn rate of Oviraptor in the Djadochta Dunes biome. Default is 2");
		this.pinacosaurusDjadochtaDunesSpawnWeight = buildInt(builder, "Pinacosaurus Djadochta Dunes Spawn Rate", "all", 5, 0, 300, "The spawn rate of Pinacosaurus in the Djadochta Dunes biome. Default is 5");
		this.plesiohadrosDjadochtaDunesSpawnWeight = buildInt(builder, "Plesiohadros Djadochta Dunes Spawn Rate", "all", 0, 0, 300, "The spawn rate of Plesiohadros in the Djadochta Dunes biome. Default is 0");
		this.protoceratopsDjadochtaDunesSpawnWeight = buildInt(builder, "Protoceratops Djadochta Dunes Spawn Rate", "all", 7, 0, 300, "The spawn rate of Protoceratops in the Djadochta Dunes biome. Default is 7");
		this.telmasaurusDjadochtaDunesSpawnWeight = buildInt(builder, "Telmasaurus Djadochta Dunes Spawn Rate", "all", 3, 0, 300, "The spawn rate of Telmasaurus in the Djadochta Dunes biome. Default is 3");
		this.velociraptorDjadochtaDunesSpawnWeight = buildInt(builder, "Velociraptor Djadochta Dunes Spawn Rate", "all", 6, 0, 300, "The spawn rate of Velociraptor in the Djadochta Dunes biome. Default is 6");
		this.caveSentinelDjadochtaDunesSpawnWeight = buildInt(builder, "Cave Sentinel Djaodochta Dunes Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Djadochta Dunes biome. Default is 5");
		this.landSentinelDjadochtaDunesSpawnWeight = buildInt(builder, "Land Sentinel Djadochta Dunes Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Djadochta Dunes biome. Default is 2");
		builder.pop(2);
		builder.push("Hell Creek Formation");
		builder.push("Hell Creek Clearing");
		this.acipenserHellCreekClearingSpawnWeight = buildInt(builder, "Acipenser Hell Creek Clearing Spawn Rate", "all", 4, 0, 300, "The spawn rate of Acipenser in the Hell Creek Clearing biome. Default is 4");
		this.ankylosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Clearing Spawn Rate", "all", 1, 0, 300, "The spawn rate of Ankylosaurus in the Hell Creek Clearing biome. Default is 1");
		this.anzuHellCreekClearingSpawnWeight = buildInt(builder, "Anzu Hell Creek Clearing Spawn Weeight", "all", 3, 0, 300, "The spawn rate of Anzu in the Hell Creek Clearing biome. Default is 3");
		this.basilemysHellCreekClearingSpawnWeight = buildInt(builder, "Basilemys Hell Creek Clearing Spawn Rate", "all", 5, 0, 300, "The spawn rate of Basilemys in the Hell Creek Clearing biome. Default is 5");
		this.cyclurusHellCreekClearingSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Clearing Spawn Rate", "all", 7, 0, 300, "The spawn rate of Cyclurus in the Hell Creek Clearing biome. Default is 7");
		this.dakotaraptorHellCreekClearingSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Clearing Spawn Rate", "all", 2, 0, 300, "The spawn rate of Dakotaraptor in the Hell Creek Clearing biome. Default is 2");
		this.didelphodonHellCreekClearingSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Clearing Spawn Rate", "all" , 5, 0, 300, "The spawn rate of Didelphodon in the Hell Creek Clearing biome. Default is 5");
		this.edmontosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Edmontosaurus Hell Creek Clearing Spawn Rate", "all", 12, 0, 300, "The spawn rate of Edmontosaurus in the Hell Creek Clearing biome. Default is 12");
		this.lepisosteusHellCreekClearingSpawnWeight = buildInt(builder, "Lepisosteus Hell Creek Clearing Spawn Rate", "all", 11, 0, 300, "The spawn rate of Lepisosteus in the Hell Creek Clearing biome. Default is 11");
		this.lonchidionHellCreekClearingSpawnWeight = buildInt(builder, "Lonchidion Hell Creek Clearing Spawn Rate", "all", 6, 0, 300, "The spawn rate of Lonchidion in the Hell Creek Clearing biome. Default is 6");
		this.melviusHellCreekClearingSpawnWeight = buildInt(builder, "Melvius Hell Creek Clearing Spawn Rate", "all", 5, 0, 300, "The spawn rate of Melvius in the Hell Creek Clearing biome. Default is 5");
		this.myledaphusHellCreekClearingSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Clearing Spawn Rate", "all", 9, 0, 300, "The spawn rate of Myledaphus in the Hell Creek Clearing biome. Default is 9");
		this.pachycephalosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Pachycephalosaurus Hell Creek Clearing Spawn Rate", "all", 5, 0, 300, "The spawn rate of Pachycephalosaurus in the Hell Creek Clearing biome. Default is 5");
		this.palaeosaniwaHellCreekClearingSpawnWeight = buildInt(builder, "Palaeosaniwa Hell Creek Clearing Spawn Rate", "all", 2, 0, 300, "The spawn rate of Palaeosaniwa in the Hell Creek Clearing biome. Default is 2");
		this.thescelosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Clearing Spawn Rate", "all", 4, 0, 300, "The spawn rate of Thescelosaurus in the Hell Creek Clearing biome. Default is 4");
		this.thoracosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Thoracosaurus Hell Creek Clearing Spawn Rate", "all", 0, 0, 300, "The spawn rate of Thoracosaurus in the Hell Creek Clearing biome. Default is 0");
		this.triceratopsHellCreekClearingSpawnWeight = buildInt(builder, "Triceratops Hell Creek Clearing Spawn Rate", "all", 15, 0, 300, "The spawn rate of Triceratops in the Hell Creek Clearing biome. Default is 15");
		this.tyrannosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Clearing Spawn Rate", "all", 9, 0, 300, "The spawn rate of Tyrannosaurus in the Hell Creek Clearing biome. Default is 9");
		this.caveSentinelHellCreekClearingSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Clearing Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Hell Creek Clearing biome. Default is 5");
		this.landSentinelHellCreekClearingSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Clearing Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Hell Creek Clearing biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek Hardwood Forest");
		this.acipenserHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Accipenser Hell Creek Hardwood Forest Spawn Rate", "all", 0, 0, 300, "The spawn rate of Acipenser in the Hell Creek Hardwood Forest biome. Default is 0");
		this.ankylosaurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Hardwood Forest Spawn Rate", "all", 3, 0, 300, "The spawn rate of Ankylosaurus in the Hell Creek Hardwood Forest biome. Default is 3");
		this.anzuHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Anzu Hell Creek Hardwood Forest Spawn Rate", "all", 7, 0, 300, "The spawn rate of Anzu in the Hell Creek Hardwood Forest biome. Default is 7");
		this.basilemysHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Basilemys Hell Creek Hardwood Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Basilemys in the Hell Creek Hardwood Forest biome. Default is 2");
		this.cyclurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Hardwood Forest Spawn Rate", "all", 8, 0, 300, "The spawn rate of Cyclurus in the Hell Creek Hardwood Forest biome. Default is 8");
		this.dakotaraptorHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Hardwood Forest Spawn Rate", "all", 3, 0, 300, "The spawn rate of Dakotaraptor in the Hell Creek Hardwood Forest biome. Default is 3");
		this.didelphodonHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Hardwood Forest Spawn Rate", "all", 4, 0, 300, "The spawn rate of Didelphodon in the Hell Creek Hardwood Forest biome. Default is 4");
		this.edmontosaurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Edmontosaurus Hell Creek Hardwood Forest Spawn Rate", "all", 11, 0, 300, "The spawn rate of Edmontosaurus in the Hell Creek Hardwood Forest biome. Default is 11");
		this.lepisosteusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Lepisosteus Hell Creek Hardwood Forest Spawn Rate", "all", 12, 0, 300, "The spawn rate of Lepisosteus in the Hell Creek Hardwood Forest biome. Default is 12");
		this.lonchidionHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Lonchidion Hell Creek Hardwood Forest Spawn Rate", "all", 0, 0, 300, "The spawn rate of Lonchidion in the Hell Creek Hardwood Forest biome. Default is 0");
		this.melviusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Melvius Hell Creek Hardwood Forest Spawn Rate", "all", 3, 0, 300, "The spawn rate of Melvius in the Hell Creek Hardwood Forest biome. Default is 3");
		this.myledaphusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Hardwood Forest Spawn Rate", "all", 11, 0, 300, "The spawn rate of Myledaphus in the Hell Creek Hardwood Forest biome. Default is 11");
		this.pachycephalosaurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Pachycephalosaurus Hell Creek Hardwood Forest Spawn Rate", "all", 8, 0, 300, "The spawn rate of Pachycephalosaurus in the Hell Creek Hardwood Forest biome. Default is 8");
		this.palaeosaniwaHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Palaeosaniwa Hell Creek Hardwood Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Palaeosaniwa in the Hell Creek Hardwood Forest biome. Default is 2");
		this.thescelosaurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Hardwood Forest Spawn Rate", "all", 4, 0, 300, "The spawn rate of Thescelosaurus in the Hell Creek Hardwood Forest biome. Default is 4");
		this.thoracosaurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Thoracosaurus Hell Creek Hardwood Forest Spawn Rate", "all", 0, 0, 300, "The spawn rate of Thoracosaurus in the Hell Creek Hardwood Forest biome. Default is 0");
		this.triceratopsHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Triceratops Hell Creek Hardwood Forest Spawn Rate", "all", 12, 0, 300, "The spawn rate of Triceratops in the Hell Creek Hardwood Forest biome. Default is 12");
		this.tyrannosaurusHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Hardwood Forest Spawn Rate", "all", 8, 0, 300, "The spawn rate of Tyrannosaurus in the Hell Creek Hardwood Forest biome. Default is 8");
		this.caveSentinelHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Hardwood Forest Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Hell Creek Hardwood Forest biome. Default is 5");
		this.landSentinelHellCreekHardwoodForestSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Hardwood Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Hell Creek Hardwood Forest biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek Liriodendrites Hills");
		this.acipenserHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Acipenser Hell Creek Liriodendrites Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Acipenser in the Hell Creek Liriodendrites Hills biome. Default is 2");
		this.ankylosaurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 13, 0, 300, "The spawn rate of Ankylosaurus in the Hell Creek Liriodendrites Hills biome. Default is 13");
		this.basilemysHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Basilemys Hell Creek Liriodendrites Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Basilemys in the Hell Creek Liriodendrites Hills biome. Default is 8");
		this.cyclurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Cyclurus in the Hell Creek Liriodendrites Hills biome. Default is 8");
		this.dakotaraptorHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Liriodendrites Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Dakotaraptor in the Hell Creek Liriodendrites Hills biome. Default is 2");
		this.dideldophodonHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Liriodendrites Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Didelphodon in the Hell Creek Liriodendrites Hills biome. Default is 2");
		this.edmontosaurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Edmontosaurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 12, 0, 300, "The spawn rate of Edmontosaurus in the Hell Creek Liriodendrites Hills biome. Default is 12");
		this.lepisosteusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Lepisosteus Hell Creek Liriodendrites Hills Spawn Rate", "all", 10, 0, 300, "The spawn rate of Lepisosteus in the Hell Creek Liriodendrites Hills biome. Default is 10");
		this.lonchidionHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Lonchidion Hell Creek Liriodendrites Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Lonchidion in the Hell Creek Liriodendrites Hills biome. Default is 8");
		this.melviusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Melvius Hell Creek Liriodendrites Hills Spawn Rate", "all", 1, 0, 300, "The spawn rate of Melvius in the Hell Creek Liriodendrites Hills biome. Default is 1");
		this.myledaphusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Liriodendrites Hills Spawn Rate", "all", 10, 0, 300, "The spawn rate of Myledaphus in the Hell Creek Liriodendrites Hills biome. Default is 10");
		this.pachycephalosaurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Pachycephalosaurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 3, 0, 300, "The spawn rate of Pachycephalosaurus in the Hell Creek Liriodendrites Hills biome. Default is 3");
		this.palaeosaniwaHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Palaeosaniwa Hell Creek Liriodendrites Hills Spawn Rate", "all", 1, 0, 300, "The spawn rate of Palaeosaniwa in the Hell Creek Liriodendrites Hills biome. Default is 1");
		this.thescelosaurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 5, 0, 300, "The spawn rate of Thescelosaurus in the Hell Creek Liriodendrites Hills biome. Default is 5");
		this.thoracosaurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Thoracosaurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 0, 0, 300, "The spawn rate of Thoracosaurus in the Hell Creek Liriodendrites Hills biome. Default is 0");
		this.triceratopsHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Triceratops Hell Creek Liriodendrites Hills Spawn Rate", "all", 3, 0, 300, "The spawn rate of Triceratops in the Hell Creek Liriodendrites Hills biome. Default is 3");
		this.tyrannosaurusHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Liriodendrites Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Tyrannosaurus in the Hell Creek Liriodendrites Hills biome. Default is 8");
		this.caveSentinelHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Liriodendrites Hills Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Hell Creek Liriodendrites Hills biome. Default is 5");
		this.landSentinelHellCreekLiriodendritesHillsSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Liriodendrites Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Hell Creek Liriodendrites Hills biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek Redwoods");
		this.acipenserHellCreekRedwoodsSpawnWeight = buildInt(builder, "Acipenser Hell Creek Redwoods Spawn Rate", "all", 0, 0, 300, "The spawn rate of Acipenser in the Hell Creek Redwoods biome. Default is 0");
		this.ankylosaurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Redwoods Spawn Rate", "all", 1, 0, 300, "The spawn rate of Ankylosaurus in the Hell Creek Redwoods biome. Default is 1");
		this.anzuHellCreekRedwoodsSpawnWeight = buildInt(builder, "Anzu Hell Creek Redwoods Spawn Rate", "all", 7, 0, 300, "The spawn rate of Anzu in the Hell Creek Redwoods biome. Default is 7");
		this.basilemysHellCreekRedwoodsSpawnWeight = buildInt(builder, "Basilemys Hell Creek Redwoods Spawn Rate", "all", 4, 0, 300, "The spawn rate of Basilemys in the Hell Creek Redwoods biome. Default is 4");
		this.cyclurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Redwoods Spawn Rate", "all", 8, 0, 300, "The spawn rate of Cyclurus in the Hell Creek Redwoods biome. Default is 8");
		this.dakotaraptorHellCreekRedwoodsSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Redwoods Spawn Rate", "all", 4, 0, 300, "The spawn rate of Dakotaraptor in the Hell Creek Redwoods biome. Default is 4");
		this.didelphodonHellCreekRedwoodsSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Redwoods Spawn Rate", "all", 6, 0, 300, "The spawn rate of Didelphodon in the Hell Creek Redwoods biome. Default is 6");
		this.edmontosaurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Edmontosaurus Hell Creek Redwoods Spawn Rate", "all", 6, 0, 300, "The spawn rate of Edmontosaurus in the Hell Creek Redwoods biome. Default is 6");
		this.lepisosteusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Lepisosteus Hell Creek Redwoods Spawn Rate", "all", 12, 0, 300, "The spawn rate of Lepisosteus in the Hell Creek Redwoods biome. Default is 12");
		this.lonchidionHellCreekRedwoodsSpawnWeight = buildInt(builder, "Lonchidion Hell Creek Redwoods Spawn Rate", "all", 0, 0, 300, "The spawn rate of Lonchidion in the Hell Creek Redwoods biome. Default is 0");
		this.melviusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Melvius Hell Creek Redwoods Spawn Rate", "all", 3, 0, 300, "The spawn rate of Melvius in the Hell Creek Redwoods biome. Default is 3");
		this.myledaphusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Redwoods Spawn Rate", "all", 11, 0, 300, "The spawn rate of Myledaphus in the Hell Creek Redwoods biome. Default is 11");
		this.pachycephalosaurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Pachycephalosaurus Hell Creek Redwoods Spawn Rate", "all", 10, 0, 300, "The spawn rate of Pachycephalosaurus in the Hell Creek Redwoods biome. Default is 10");
		this.palaeosaniwaHellCreekRedwoodsSpawnWeight = buildInt(builder, "Palaeosaniwa Hell Creek Redwoods Spawn Rate", "all", 4, 0, 300, "The spawn rate of Palaeosaniwa in the Hell Creek Redwoods biome. Default is 4");
		this.thescelosaurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Redwoods Spawn Rate", "all", 11, 0, 300, "The spawn rate of Thescelosaurus in the Hell Creek Redwoods biome. Default is 11");
		this.thoracosaurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Thoracosaurus Hell Creek Redwoods Spawn Rate", "all", 0, 0, 300, "The spawn rate of Thoracosaurus in the Hell Creek Redwoods biome. Default is 0");
		this.triceratopsHellCreekRedwoodsSpawnWeight = buildInt(builder, "Triceratops Hell Creek Redwoods Spawn Rate", "all", 7, 0, 300, "The spawn rate of Triceratops in the Hell Creek Redwoods biome. Default is 7");
		this.tyrannosaurusHellCreekRedwoodsSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Redwoods Spawn Rate", "all", 5, 0, 300, "The spawn rate of Tyrannosaurus in the Hell Creek Redwoods biome. Default is 5");
		this.caveSentinelHellCreekRedwoodsSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Redwoods Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Hell Creek Redwoods biome. Default is 5");
		this.landSentinelHellCreekRedwoodsSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Redwoods Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Hell Creek Redwoods biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek River");
		this.acipenserHellCreekRiverSpawnWeight = buildInt(builder, "Acipenser Hell Creek River Spawn Rate", "all", 6, 0, 300, "The spawn rate of Acipenser in the Hell Creek River biome. Default is 6");
		this.ankylosaurusHellCreekRiverSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek River Spawn Rate", "all", 1, 0, 300, "The spawn rate of Ankylosaurus in the Hell Creek River biome. Default is 1");
		this.anzuHellCreekRiverSpawnWeight = buildInt(builder, "Anzu Hell Creek River Spawn Rate", "all", 2, 0, 300, "The spawn rate of Anzu in the Hell Creek River biome. Default is 2");
		this.basilemysHellCreekRiverSpawnWeight = buildInt(builder, "Basilemys Hell Creek River Spawn Rate", "all", 4, 0, 300, "The spawn rate of Basilemys in the Hell Creek River biome. Default is 4");
		this.cyclurusHellCreekRiverSpawnWeight = buildInt(builder, "Cyclurus Hell Creek River Spawn Rate", "all", 7, 0, 300, "The spawn rate of Cyclurus in the Hell Creek River biome. Default is 7");
		this.dakotaraptorHellCreekRiverSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek River Spawn Rate", "all", 6, 0, 300, "The spawn rate of Dakotaraptor in the Hell Creek River biome. Default is 6");
		this.didelphodonHellCreekRiverSpawnWeight = buildInt(builder, "Didelphodon Hell Creek River Spawn Rate", "all", 5, 0, 300, "The spawn rate of Didelphodon in the Hell Creek River biome. Default is 5");
		this.edmontosaurusHellCreekRiverSpawnWeight = buildInt(builder, "Edmontosaurus Hell Creek River Spawn Rate", "all", 10, 0, 300, "The spawn rate of Edmontosaurus in the Hell Creek River biome. Default is 10");
		this.lepisosteusHellCreekRiverSpawnWeight = buildInt(builder, "Lepisosteus Hell Creek River Spawn Rate", "all", 11, 0, 300, "The spawn rate of Lepisosteus in the Hell Creek River biome. Default is 11");
		this.lonchidionHellCreekRiverSpawnWeight = buildInt(builder, "Lonchidion Hell Creek River Spawn Rate", "all", 6, 0, 300, "The spawn rate of Lonchidion in the Hell Creek River biome. Default is 6");
		this.melviusHellCreekRiverSpawnWeight = buildInt(builder, "Melvius Hell Creek River Spawn Rate", "all", 4, 0, 300, "The spawn rate of Melvius in the Hell Creek River biome. Default is 4");
		this.myledaphusHellCreekRiverSpawnWeight = buildInt(builder, "Myledaphus Hell Creek River Spawn Rate", "all", 11, 0, 300, "The spawn rate of Myledaphus in the Hell Creek River biome. Default is 11");
		this.pachycephalosaurusHellCreekRiverSpawnWeight = buildInt(builder, "Pachycephalosaurus Hell Creek RIver Spawn Rate", "all", 2, 0, 300, "The spawn rate of Pachycephalosaurus in the Hell Creek River biome. Default is 2");
		this.palaeosaniwaHellCreekRiverSpawnWeight = buildInt(builder, "Palaeosaniwa Hell Creek River Spawn Rate", "all", 1, 0, 300, "The spawn rate of Palaeosaniwa in the Hell Creek River biome. Default is 1");
		this.thescelosaurusHellCreekRiverSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek River Spawn Rate", "all", 7, 0, 300, "The spawn rate of Thescelosaurus in the Hell Creek River biome. Default is 7");
		this.thoracosaurusHellCreekRiverSpawnWeight = buildInt(builder, "Thoracosaurus Hell Creek River Spawn Rate", "all", 3, 0, 300, "The spawn rate of Thoracosaurus in the Hell Creek River biome. Default is 3");
		this.triceratopsHellCreekRiverSpawnWeight = buildInt(builder, "Triceratops Hell Creek River Spawn Rate", "all", 11, 0, 300, "The spawn rate of Triceratops in the Hell Creek River biome. Default is 11");
		this.tyrannosaurusHellCreekRiverSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek River Spawn Rate", "all", 8, 0, 300, "The spawn rate of Tyrannosaurus in the Hell Creek River biome. Default is 8");
		this.caveSentinelHellCreekRiverSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek River Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Hell Creek River biome. Default is 5");
		this.landSentinelHellCreekRiverSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek River Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Hell Creek River biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek Swamp");
		this.acipenserHellCreekSwampSpawnWeight = buildInt(builder, "Acipenser Hell Creek Swamp Spawn Rate", "all", 7, 0, 300, "The spawn rate of Acipenser in the Hell Creek Swamp biome. Default is 7");
		this.ankylosaurusHellCreekSwampSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Swamp Spawn Rate", "all", 1, 0, 300, "The spawn rate of Ankylosaurus in the Hell Creek Swamp biome. Default is 1");
		this.basilemysHellCreekSwampSpawnWeight = buildInt(builder, "Basilemys Hell Creek Swamp Spawn Rate", "all", 3, 0, 300, "The spawn rate of Basilemys in the Hell Creek Swamp biome. Default is 3");
		this.cyclurusHellCreekSwampSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Swamp Spawn Rate", "all", 4, 0, 300, "The spawn rate of Cyclurus in the Hell Creek Swamp biome. Default is 4");
		this.dakotaraptorHellCreekSwampSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Swamp Spawn Rate", "all", 0, 0, 300, "The spawn rate of Dakotaraptor in the Hell Creek Swamp biome. Default is 0");
		this.didelphodonHellCreekSwampSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Swamp Spawn Rate", "all", 8, 0, 300, "The spawn rate of Didelphodon in the Hell Creek Swamp biome. Default is 8");
		this.edmontosaurusHellCreekSwampSpawnWeight = buildInt(builder, "Edmontosaurus Hell Creek Swamp Spawn Rate", "all", 9, 0, 300, "The spawn rate of Edmontosaurus in the Hell Creek Swamp biome. Default is 9");
		this.lepisosteusHellCreekSwampSpawnWeight = buildInt(builder, "Lepisosteus Hell Creek Swamp Spawn Rate", "all", 14, 0, 300, "The spawn rate of Lepisosteus in the Hell Creek Swamp biome. Default is 14");
		this.lonchidionHellCreekSwampSpawnWeight = buildInt(builder, "Lonchidion Hell Creek Swamp Spawn Rate", "all", 7, 0, 300, "The spawn rate of Lonchidion in the Hell Creek Swamp biome. Default is 7");
		this.melviusHellCreekSwampSpawnWeight = buildInt(builder, "Melvius Hell Creek Swamp Spawn Rate", "all", 6, 0, 300, "The spawn rate of Melvius in the Hell Creek Swamp biome. Default is 6");
		this.myledaphusHellCreekSwampSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Swamp Spawn Rate", "all", 12, 0, 300, "The spawn rate of Myledaphus in the Hell Creek Swamp biome. Default is 12");
		this.pachycephalosaurusHellCreekSwampSpawnWeight = buildInt(builder, "Pachycephalosaurus Hell Creek Swamp Spawn Rate", "all", 2, 0, 300, "The spawn rate of Pachycephalosaurus in the Hell Creek Swamp biome. Default is 2");
		this.palaeosaniwaHellCreekSwampSpawnWeight = buildInt(builder, "Palaeosaniwa Hell Creek Swamp Spawn Rate", "all", 0, 0, 300, "The spawn rate of Palaeosaniwa in th Hell Creek Swamp biome. Default is 0");
		this.thescelosaurusHellCreekSwampSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Swamp Spawn Rate", "all", 7, 0, 300, "The spawn rate of Thescelosaurus in the Hell Creek Swamp biome. Default is 7");
		this.thoracosaurusHellCreekSwampSpawnWeight = buildInt(builder, "Thoracosaurus Hell Creek Swamp Spawn Rate", "all", 3, 0, 300, "The spawn rate of Thoracosaurus in the Hell Creek Swamp biome. Default is 3");
		this.triceratopsHellCreekSwampSpawnWeight = buildInt(builder, "Triceratops Hell Creek Swamp Spawn Rate", "all", 10, 0, 300, "The spawn rate of Triceratops in the Hell Creek Swamp biome. Default is 10");
		this.tyrannosaurusHellCreekSwampSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Swamp Spawn Rate", "all", 8, 0, 300, "The spawn rate of Tyrannosaurus in the Hell Creek Swamp biome. Default is 8");
		this.caveSentinelHellCreekSwampSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Swamp Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Hell Creek Swamp biome. Default is 5");
		this.landSentinelHellCreekSwampSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Swamp Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Hell Creek Swamp biome. Default is 2");
		builder.pop(2);
		builder.push("Kayenta Formation");
		builder.push("Kayenta Canyon");
		this.calsoyasuchusKayentaButtesSpawnWeight = buildInt(builder, "Calsoyasuchus Kayenta Canyon Spawn Rate", "all", 2, 0, 300, "The spawn rate of Calsoyasuchus in the Kayenta Canyon biome. Default is 2");
		this.ceratodusKayentaButtesSpawnWeight = buildInt(builder, "Ceratodus Kayenta Canyon Spawn Rate", "all", 0, 0, 300, "The spawn rate of Ceratodus in the Kayenta Canyon biome. Default is 0");
		this.dilophosaurusKayentaButtesSpawnWeight = buildInt(builder, "Dilophosaurus Kayenta Canyon Spawn Rate", "all", 5, 0, 300, "The spawn rate of Dilophosaurus in the Kayenta Canyon biome. Default is 5");
		this.kayentatheriumKayentaButtesSpawnWeight = buildInt(builder, "Kayentatherium Kayenta Canyon Spawn Rate", "all", 1, 0, 300, "The spawn rate of Kayentatherium in the Kayenta Canyon biome. Default is 1");
		this.megapnosaurusKayentaButtesSpawnWeight = buildInt(builder, "Megapnosaurus Kayenta Canyon Spawn Rate", "all", 8, 1, 300, "The spawn rate of Megapnosaurus in the Kayenta Canyon biome. Default is 8");
		this.potamoceratodusKayentaButtesSpawnWeight = buildInt(builder, "Potamoceratodus Kayenta Canyon Spawn Rate", "all", 2, 0, 300, "The spawn rate of Potamoceratodus in the Kayenta Canyon biome. Default is 2");
		this.sarahsaurusKayentaButtesSpawnWeight = buildInt(builder, "Sarahsaurus Kayenta Canyon Spawn Rate", "all", 4, 0, 300, "The spawn rate of Sarahsaurus in the Kayenta Canyon biome. Default is 4");
		this.scelidosaurusKayentaButtesSpawnWeight = buildInt(builder, "Scelidosaurus Kayenta Canyon Spawn Rate", "all", 10, 0, 300, "The spawn rate of Scelidosaurus in the Kayenta Canyon biome. Default is 10");
		this.scutellosaurusKayentaButtesSpawnWeight = buildInt(builder, "Scutellosaurus Kayenta Canyon Spawn Rate", "all", 7, 0, 300, "The spawn rate of Scutellosaurus in the Kayenta Canyon biome. Default is 7");
		this.caveSentinelKayentaButtesSpawnWeight = buildInt(builder, "Cave Sentinel Kayenta Canyon Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Kayenta Canyon biome. Default is 5");
		this.landSentinelKayentaButtesSpawnWeight = buildInt(builder, "Land Sentinel Kayenta Canyon Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Kayenta Canyon biome. Default is 2");
		builder.pop();
		builder.push("Kayenta Desert");
		this.calsoyasuchusKayentaDesertSpawnWeight = buildInt(builder, "Calsoyasuchus Kayenta Desert Spawn Rate", "all", 1, 0, 300, "The spawn rate of Calsoyasuchus in the Kayenta Desert biome. Default is 1");
		this.ceratodusKayentaDesertSpawnWeight = buildInt(builder, "Ceratodus Kayenta Desert Spawn Rate", "all", 2, 0, 300, "The spawn rate of Ceratodus in the Kayenta Desert biome. Default is 2");
		this.dilophosaurusKayentaDesertSpawnWeight = buildInt(builder, "Dilophosaurus Kayenta Desert Spawn Rate", "all", 3, 0, 300, "The spawn rate of Dilophosaurus in the Kayenta Desert biome. Default is 3");
		this.kayentatheriumKayentaDesertSpawnWeight = buildInt(builder, "Kayentatherium Kayenta Desert Spawn Rate", "all", 2, 0, 300, "The spawn rate of Kayentatherium in the Kayenta Desert biome. Default is 2");
		this.megapnosaurusKayentaDesertSpawnWeight = buildInt(builder, "Megapnosaurus Kayenta Desert Spawn Rate", "all", 5, 1, 300, "The spawn rate of Megapnosaurus in the Kayenta Desert biome. Default is 5");
		this.potamoceratodusKayentaDesertSpawnWeight = buildInt(builder, "Potamoceratodus Kayenta Desert Spawn Rate", "all", 2, 0, 300, "The spawn rate of Potamoceratodus in the Kayenta Desert biome. Default is 2");
		this.sarahsaurusKayentaDesertSpawnWeight = buildInt(builder, "Sarahsaurus Kayenta Desert Spawn Rate", "all", 4, 0, 300, "The spawn rate of Sarahsaurus in the Kayenta Desert biome. Default is 4");
		this.scelidosaurusKayentaDesertSpawnWeight = buildInt(builder, "Scelidosaurus Kayenta Desert Spawn Rate", "all", 4, 0, 300, "The spawn rate of Scelidosaurus in the Kayenta Desert biome. Default is 4");
		this.scutellosaurusKayentaDesertSpawnWeight = buildInt(builder, "Scutellosaurus Kayenta Desert Spawn Rate", "all", 2, 0, 300, "The spawn rate of Scutellosaurus in the Kayenta Desert biome. Default is 2");
		this.caveSentinelKayentaDesertSpawnWeight = buildInt(builder, "Cave Sentinel Kayenta Desert Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Kayenta Desert biome. Default is 5");
		this.landSentinelKayentaDesertSpawnWeight = buildInt(builder, "Land Sentinel Kayenta Desert Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Kayenta Desert biome. Default is 2");
		builder.pop();
		builder.push("Kayenta Dry Forest");
		this.calsoyasuchusKayentaDryForestSpawnWeight = buildInt(builder, "Calsoyasuchus Kayenta Dry Forest Spawn Rate", "all", 5, 0, 300, "The spawn rate of Calsoyasuchus in the Kayenta Dry Forest biome. Default is 5");
		this.ceratodusKayentaDryForestSpawnWeight = buildInt(builder, "Ceratodus Kayenta Dry Forest Spawn Rate", "all", 3, 0, 300, "The spawn rate of Ceratodus in the Kayenta Dry Forest biome. Default is 3");
		this.dilophosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Dilophosaurus Kayenta Dry Forest Spawn Rate", "all", 4, 0, 300, "The spawn rate of Dilophosaurus in the Kayenta Dry Forest biome. Default is 4");
		this.kayentatheriumKayentaDryForestSpawnWeight = buildInt(builder, "Kayentatherium Kayenta Dry Forest Spawn Rate", "all", 7, 0, 300, "The spawn rate of Kayentatherium in the Kayenta Dry Forest biome. Default is 7");
		this.megapnosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Megapnosaurus Kayenta Dry Forest Spawn Rate", "all", 2, 1, 300, "The spawn rate of Megapnosaurus in the Kayenta Dry Forest biome. Default is 2");
		this.potamoceratodusKayentaDryForestSpawnWeight = buildInt(builder, "Potamoceratodus Kayenta Dry Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Potamoceratodus in the Kayenta Dry Forest biome. Default is 2");
		this.sarahsaurusKayentaDryForestSpawnWeight = buildInt(builder, "Sarahsaurus Kayenta Dry Forest Spawn Rate", "all", 6, 0, 300, "The spawn rate of Sarahsaurus in the Kayenta Dry Forest biome. Default is 6");
		this.scelidosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Scelidosaurus Kayenta Dry Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Scelidosaurus in the Kayenta Dry Forest biome. Default is 2");
		this.scutellosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Scutellosaurus Kayenta Dry Forest Spawn Rate", "all", 8, 0, 300, "The spawn rate of Scutellosaurus in the Kayenta Dry Forest biome. Default is 8");
		this.caveSentinelKayentaDryForestSpawnWeight = buildInt(builder, "Cave Sentinel Kayenta Dry Forest Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Kayenta Dry Forest biome. Default is 5");
		this.landSentinelKayentaDryForestSpawnWeight = buildInt(builder, "Land Sentinel Kayenta Dry Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Kayenta Dry Forest biome. Default is 2");
		builder.pop(2);
		builder.push("Morrison Formation");
		builder.push("Morrison Hills");
		this.allosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Allosaurus Morrison Hills Spawn Rate", "all", 3, 0, 300, "The spawn rate of Allosaurus in the Morrison Hills biome. Default is 3");
		this.camarasaurusMorrisonHillsSpawnWeight = buildInt(builder, "Camarasaurus Morrison Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Camarasaurus in the Morrison Hills biome. Default is 2");
		this.ceratodusMorrisonHillsSpawnWeight = buildInt(builder, "Ceratodus Morrison Hills Spawn Rate", "all", 1, 0, 300, "The spawn rate of Ceratodus in the Morrison Hills biome. Default is 1");
		this.ceratosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Ceratosaurus Morrison Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Ceratosaurus in the Morrison Hills biome. Default is 2");
		this.dryosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Dryosaurus Morrison Hills Spawn Rate", "all", 7, 0, 300, "The spawn rate of Dryosaurus in the Morrison Hills biome. Default is 7");
		this.eilenodonMorrisonHillsSpawnWeight = buildInt(builder, "Eilenodon Morrison Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Eilenodon in the Morrison Hills biome. Default is 5");
		this.hesperornithoidesMorrisonHillsSpawnWeight = buildInt(builder, "Hesperornithoides Morrison Hills Spawn Rate", "all", 7, 0, 300, "The spawn rate of Hesperornithoides in the Morrison Hills biome. Default is 4");
		this.potamoceratodusMorrisonHillsSpawnWeight = buildInt(builder, "Potamoceratodus Morrison Hills Spawn Rate", "all", 3, 0, 300, "The spawn rate of Potamoceratodus in the Morrison Hills biome. Default is 3");
		this.stegosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Stegosaurus Morrison Hills Spawn Rate", "all", 10, 0, 300, "The spawn rate of Stegosaurus in the Morrison Hills biome. Default is 10");
		this.caveSentinelMorrisonHillsSpawnWeight = buildInt(builder, "Cave Sentinel Morrison Hills Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Morrison Hills biome. Default is 5");
		this.landSentinelMorrisonHillsSpawnWeight = buildInt(builder, "Land Sentinel Morrison Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Morrison Hills biome. Default is 2");
		builder.pop();
		builder.push("Morrison Savanna");
		this.allosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Allosaurus Morrison Savanna Spawn Rate", "all", 3, 0, 300, "The spawn rate of Allosaurus in the Morrison Savanna biome. Default is 3");
		this.camarasaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Camarasaurus Morrison Savanna Spawn Rate", "all", 2, 0, 300, "The spawn rate of Camarasaurus in the Morrison Savanna biome. Default is 2");
		this.ceratodusMorrisonSavannahSpawnWeight = buildInt(builder, "Ceratodus Morrison Savanna Spawn Rate", "all", 1, 0, 300, "The spawn rate of Ceratodus in the Morrison Savanna biome. Default is 1");
		this.ceratosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Ceratosaurus Morrison Savanna Spawn Rate", "all", 2, 0, 300, "The spawn rate of Ceratosaurus in the Morrison Savanna biome. Default is 2");
		this.dryosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Dryosaurus Morrison Savanna Spawn Rate", "all", 7, 0, 300, "The spawn rate of Dryosaurus in the Morrison Savanna biome. Default is 7");
		this.eilenodonMorrisonSavannahSpawnWeight = buildInt(builder, "Eilenodon Morrison Savanna Spawn Rate", "all", 8, 0, 300, "The spawn rate of Eilenodon in the Morrison Savanna biome. Default is 5");
		this.hesperornithoidesMorrisonSavannahSpawnWeight = buildInt(builder, "Hesperornithoides Morrison Savanna Spawn Rate", "all", 7, 0, 300, "The spawn rate of Hesperornithoides in the Morrison Savanna biome. Default is 4");
		this.potamoceratodusMorrisonSavannahSpawnWeight = buildInt(builder, "Potamoceratodus Morrison Savanna Spawn Rate", "all", 3, 0, 300, "The spawn rate of Potamoceratodus in the Morrison Savanna biome. Default is 3");
		this.stegosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Stegosaurus Morrison Savanna Spawn Rate", "all", 10, 0, 300, "The spawn rate of Stegosaurus in the Morrison Savanna biome. Default is 10");
		this.caveSentinelMorrisonSavannahSpawnWeight = buildInt(builder, "Cave Sentinel Morrison Savanna Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Morrison Savanna biome. Default is 5");
		this.landSentinelMorrisonSavannahSpawnWeight = buildInt(builder, "Land Sentinel Morrison Savanna Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Morrison Savanna biome. Default is 2");
		builder.pop(2);
		builder.push("Chinle Formation");
		builder.push("Chinle Flats");
		this.arganodusChinleFlatsSpawnWeight = buildInt(builder, "Arganodus Chinle Flats Spawn Rate", "all", 3, 0, 300, "The spawn rate of Arganodus in the Chinle Flats biome. Default is 4");
		this.chinleaChinleFlatsSpawnWeight = buildInt(builder, "Chinlea Chinle Flats Spawn Rate", "all", 4, 0, 300, "The spawn rate of Chinlea in the Chinle Flats biome. Default is 4");
		this.coelophysisChinleFlatsSpawnWeight = buildInt(builder, "Coelophysis Chinle Flats Spawn Rate", "all", 10, 0, 300, "The spawn rate of Coelophysis in the Chinle Flats biome. Default is 10");
		this.desmatosuchusChinleFlatsSpawnWeight = buildInt(builder, "Desmatosuchus Chinle Flats Spawn Rate", "all", 4, 0, 300, "The spawn rate of Desmatosuchus in the Chinle Flats biome. Default is 4");
		this.mooreodontusChinleFlatsSpawnWeight = buildInt(builder, "Mooreodontus Chinle Flats Spawn Rate", "all", 1, 0, 300, "The spawn rate of Mooreodontus in the Chinle Flats biome. Default is 1");
		this.placeriasChinleFlatsSpawnWeight = buildInt(builder, "Placerias Chinle Flats Spawn Rate", "all", 0, 0, 300, "The spawn rate of Placerias in the Chinle Flats biome. Default is 0");
		this.poposaurusChinleFlatsSpawnWeight = buildInt(builder, "Poposaurus Chinle Flats Spawn Rate", "all", 0, 0, 300, "The spawn rate of Poposaurus in the Chinle Flats biomes. Default is 0");
		this.postosuchusChinleFlatsSpawnWeight = buildInt(builder, "Postosuchus Chinle Flats Spawn Rate", "all", 6, 0, 300, "The spawn rate of Postosuchus in the Chinle Flats biome. Default is 6");
		this.saurichthysChinleFlatsSpawnWeight = buildInt(builder, "Saurichthys Chinle Flats Spawn Rate", "all", 2, 0, 300, "The spawn rate of Saurichthys in the Chinle Flats biome. Default is 2");
		this.trilophosaurusChinleFlatsSpawnWeight = buildInt(builder, "Trilophosaurus Chinle Flats Spawn Rate", "all", 0, 0, 300, "The spawn rate of Trilophosaurus in the Chinle Flats biome. Default is 0");
		this.typothoraxChinleFlatsSpawnWeight = buildInt(builder, "Typothorax Chinle Flats Spawn Rate", "all", 8, 0, 300, "The spawn rate of Typothorax in the Chinle Flats biome. Default is 8");
		this.caveSentinelChinleFlatsSpawnWeight = buildInt(builder, "Cave Sentinel Chinle Flats Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Chinle Flats biome. Default is 5");
		this.landSentinelChinleFlatsSpawnWeight = buildInt(builder, "Land Sentinel Chinle Flats Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Chinle Flats biome. Default is 2");
		builder.pop();
		builder.push("Chinle River");
		this.arganodusChinleRiverSpawnWeight = buildInt(builder, "Arganodus Chinle River Spawn Rate", "all", 3, 0, 300, "The spawn rate of Arganodus in the Chinle River biome. Default is 4");
		this.chinleaChinleRiverSpawnWeight = buildInt(builder, "Chinlea Chinle River Spawn Rate", "all", 4, 0, 300, "The spawn rate of Chinlea in the Chinle River biome. Default is 4");
		this.mooreodontusChinleRiverSpawnWeight = buildInt(builder, "Mooreodontus Chinle River Spawn Rate", "all", 1, 0, 300, "The spawn rate of Mooreodontus in the Chinle River biome. Default is 1");
		this.saurichthysChinleRiverSpawnWeight = buildInt(builder, "Saurichthys Chinle River Spawn Rate", "all", 2, 0, 300, "The spawn rate of Saurichthys in the Chinle River biome. Default is 2");
		this.caveSentinelChinleRiverSpawnWeight = buildInt(builder, "Cave Sentinel Chinle River Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Chinle River biome. Default is 5");
		this.landSentinelChinleRiverSpawnWeight = buildInt(builder, "Land Sentinel Chinle River Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Chinle River biome. Default is 2");
		builder.pop();
		builder.push("Chinle Swamp");
		this.arganodusChinleSwampSpawnWeight = buildInt(builder, "Arganodus Chinle Swamp Spawn Rate", "all", 4, 0, 300, "The spawn rate of Arganodus in the Chinle Swamp biome. Default is 4");
		this.chinleaChinleSwampSpawnWeight = buildInt(builder, "Chinlea Chinle Swamp Spawn Rate", "all", 1, 0, 300, "The spawn rate of Chinlea in the Chinle Swamp biome. Default is 1");
		this.coelophysisChinleSwampSpawnWeight = buildInt(builder, "Coelophysis Chinle Swamp Spawn Rate", "all", 12, 0, 300, "The spawn rate of Coelophysis in the Chinle Swamp biome. Default is 12");
		this.desmatosuchusChinleSwampSpawnWeight = buildInt(builder, "Desmatosuchus Chinle Swamp Spawn Rate", "all", 9, 0, 300, "The spawn rate of Desmatosuchus in the Chinle Swamp biome. Default is 9");
		this.mooreodontusChinleSwampSpawnWeight = buildInt(builder, "Mooreodontus Chinle Swamp Spawn Rate", "all", 3, 0, 300, "The spawn rate of Mooreodontus in the Chinle Swamp biome. Default is 3");
		this.placeriasChinleSwampSpawnWeight = buildInt(builder, "Placerias Chinle Swamp Spawn Rate", "all", 6, 0, 300, "The spawn rate of Placerias in the Chinle Swamp biome. Default is 6");
		this.poposaurusChinleSwampSpawnWeight = buildInt(builder, "Poposaurus Chinle Swamp Spawn Rate", "all", 3, 0, 300, "The spawn rate of Poposaurus in the Chinle Swamp biome. Default is 3");
		this.postosuchusChinleSwampSpawnWeight = buildInt(builder, "Postosuchus Chinle Swamp Spawn Rate", "all", 5, 0, 300, "The spawn rate of Postosuchus in the Chinle Swamp biome. Default is 5");
		this.saurichthysChinleSwampSpawnWeight = buildInt(builder, "Saurichthys Chinle Swamp Spawn Rate", "all", 2, 0, 300, "The spawn rate of Saurichthys in the Chinle Swamp biome. Default is 2");
		this.trilophosaurusChinleSwampSpawnWeight = buildInt(builder, "Trilophosaurus Chinle Swamp Spawn Rate", "all", 10, 0, 300, "The spawn rate of Trilophosaurus in the Chinle Swamp biome. Default is 10");
		this.typothoraxChinleSwampSpawnWeight = buildInt(builder, "Typothorax Chinle Swamp Spawn Rate", "all", 7, 0, 300, "The spawn rate of Typothorax in the Chinle Swamp biome. Default is 7");
		this.caveSentinelChinleSwampSpawnWeight = buildInt(builder, "Cave Sentinel Chinle Swamp Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Chinle Swamp biome. Default is 5");
		this.landSentinelChinleSwampSpawnWeight = buildInt(builder, "Land Sentinel Chinle Swamp Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Chinle Swamp biome. Default is 2");
		builder.pop();
		builder.push("Chinle Wooded Mountains");
		this.arganodusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Arganodus Chinle Wooded Mountains Spawn Rate", "all", 0, 0, 300, "The spawn rate of Arganodus in the Chinle Wooded Mountains biome. Default is 0");
		this.chinleaChinleWoodedMountainsSpawnWeight = buildInt(builder, "Chinlea Chinle Wooded Mountains Spawn Rate", "all", 0, 0, 300, "The spawn rate of Chinlea in the Chinle Wooded Mountains biome. Default is 0");
		this.coelophysisChinleWoodedMountainsSpawnWeight = buildInt(builder, "Coelophysis Chinle Wooded Mountains Spawn Rate", "all", 0, 0, 300, "The spawn rate of Coelophysis in the Chinle Wooded Mountains biome. Default is 0");
		this.desmatosuchusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Desmatosuchus Chinle Wooded Mountains Spawn Rate", "all", 7, 0, 300, "The spawn rate of Desmatosuchus in the Chinle Wooded Mountains biome. Default is 7");
		this.mooreodontusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Mooreodontus Chinle Wooded Mountains Spawn Rate", "all", 0, 0, 300, "The spawn rate of Mooreodontus in the Chinle Wooded Mountains biome. Default is 0");
		this.placeriasChinleWoodedMountainsSpawnWeight = buildInt(builder, "Placerias Chinle Wooded Mountains Spawn Rate", "all", 11, 0, 300, "The spawn rate of Placerias in the Chinle Wooded Mountains biome. Default is 11");
		this.poposaurusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Poposaurus Chinle Wooded Mountains Spawn Rate", "all", 8, 0, 300, "The spawn rate of Poposaurus in the Chinle Wooded Mountains biome. Default is 8");
		this.postosuchusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Postosuchus Chinle Wooded Mountains Spawn Rate", "all", 3, 0, 300, "The spawn rate of Postosuchus in the Chinle Wooded Mountains biome. Default is 3");
		this.saurichthysChinleWoodedMountainsSpawnWeight = buildInt(builder, "Saurichthys Chinle Wooded Mountains Spawn Rate", "all", 0, 0, 300, "The spawn rate of Saurichthys in the Chinle Wooded Mountains biome. Default is 0");
		this.trilophosaurusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Trilophosaurus Chinle Wooded Mountains Spawn Rate", "all", 10, 0, 300, "The spawn rate of Trilophosaurus in the Chinle Wooded Mountains. Default is 10");
		this.typothoraxChinleWoodedMountainsSpawnWeight = buildInt(builder, "Typothorax Chinle Wooded Mountains Spawn Rate", "all", 5, 0, 300, "The spawn rate of Typothorax in the vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 5");
		this.caveSentinelChinleWoodedMountainsSpawnWeight = buildInt(builder, "Cave Sentinel Chinle Wooded Mountains Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Chinle Wooded Mountains biome. Default is 5");
		this.landSentinelChinleWoodedMountainsSpawnWeight = buildInt(builder, "Land Sentinel Chinle Wooded Mountains Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Chinle Wooded Mountains biome. Default is 2");
		builder.pop(2);
		builder.push("Ischigualasto Formation");
		builder.push("Ischigualasto Forest");
		this.ceratodusIschigualastoForestSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto Forest Spawn Rate", "all", 3, 0, 300, "The spawn rate of Ceratodus in the Ischigualasto Forest biome. Default is 3");
		this.chromogisaurusIschigualastoForestSpawnWeight = buildInt(builder, "Chromogisaurus Ischigualasto Forest Spawn Rate", "all", 10, 0, 300, "The spawn rate of Chromogisaurus in the Ischigualasto Forest biome. Default is 10");
		this.exaeretodonIschigualastoForestSpawnWeight = buildInt(builder, "Exaeretodon Ischigualasto Forest Spawn Rate", "all", 12, 0, 300, "The spawn rate of Exaeretodon in the Ischigualasto Forest biome. Default is 12");
		this.herrerasaurusIschigualastoForestSpawnWeight = buildInt(builder, "Herrerasaurus Ischigualasto Forest Spawn Rate", "all", 8, 0, 300, "The spawn rate of Herrerasaurus in the Ischigualasto Forest biome. Default is 8");
		this.hyperodapedonIschigualastoForestSpawnWeight = buildInt(builder, "Hyperodapedon Ischigualasto Forest Spawn Rate", "all", 15, 0, 300, "The spawn rate of Hyperodapedon in the Ischigualasto Forest biome. Default is 15");
		this.ischigualastiaIschigualastoForestSpawnWeight = buildInt(builder, "Ischigualastia Ischigualasto Forest Spawn Rate", "all", 8, 0, 300, "The spawn rate of Ischigualastia in the Ischigualasto Forest biome. Default is 8");
		this.saurosuchusIschigualastoForestSpawnWeight = buildInt(builder, "Saurosuchus Ischigualasto Forest Spawn Rate", "all", 4, 0, 300, "The spawn rate of Saurosuchus in the Ischigualasto Forest biome. Default is 4");
		this.sillosuchusIschigualastoForestSpawnWeight = buildInt(builder, "Sillosuchus Ischigualasto Forest Spawn Rate", "all", 6, 0, 300, "The spawn rate of Sillosuchus in the Ischigualasto Forest biome. Default is 6");
		this.caveSentinelIschigualastoForestSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto Forest Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Ischigualasto Forest biome. Default is 5");
		this.landSentinelIschigualastoForestSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto Forest Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Ischigualasto Forest biome. Default is 2");
		builder.pop();
		builder.push("Ischigualasto Clearing");
		this.ceratodusIschigualastoClearingSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto Clearing Spawn Rate", "all", 3, 0, 300, "The spawn rate of Ceratodus in the Ischigualasto Clearing biome. Default is 3");
		this.chromogisaurusIschigualastoClearingSpawnWeight = buildInt(builder, "Chromogisaurus Ischigualasto Clearing Spawn Rate", "all", 10, 0, 300, "The spawn rate of Chromogisaurus in the Ischigualasto Clearing biome. Default is 10");
		this.exaeretodonIschigualastoClearingSpawnWeight = buildInt(builder, "Exaeretodon Ischigualasto Clearing Spawn Rate", "all", 12, 0, 300, "The spawn rate of Exaeretodon in the Ischigualasto Clearing biome. Default is 12");
		this.herrerasaurusIschigualastoClearingSpawnWeight = buildInt(builder, "Herrerasaurus Ischigualasto Clearing Spawn Rate", "all", 8, 0, 300, "The spawn rate of Herrerasaurus in the Ischigualasto Clearing biome. Default is 8");
		this.hyperodapedonIschigualastoClearingSpawnWeight = buildInt(builder, "Hyperodapedon Ischigualasto Clearing Spawn Rate", "all", 15, 0, 300, "The spawn rate of Hyperodapedon in the Ischigualasto Clearing biome. Default is 15");
		this.ischigualastiaIschigualastoClearingSpawnWeight = buildInt(builder, "Ischigualastia Ischigualasto Clearing Spawn Rate", "all", 8, 0, 300, "The spawn rate of Ischigualastia in the Ischigualasto Clearing biome. Default is 8");
		this.saurosuchusIschigualastoClearingSpawnWeight = buildInt(builder, "Saurosuchus Ischigualasto Clearing Spawn Rate", "all", 4, 0, 300, "The spawn rate of Saurosuchus in the Ischigualasto Clearing biome. Default is 4");
		this.sillosuchusIschigualastoClearingSpawnWeight = buildInt(builder, "Sillosuchus Ischigualasto Clearing Spawn Rate", "all", 6, 0, 300, "The spawn rate of Sillosuchus in the Ischigualasto Clearing biome. Default is 6");
		this.caveSentinelIschigualastoClearingSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto Clearing Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Ischigualasto Clearing biome. Default is 5");
		this.landSentinelIschigualastoClearingSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto Clearing Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Ischigualasto Clearing biome. Default is 2");
		builder.pop();
		builder.push("Ischigualasto Hills");
		this.ceratodusIschigualastoHillsSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto Hills Spawn Rate", "all", 3, 0, 300, "The spawn rate of Ceratodus in the Ischigualasto Hills biome. Default is 3");
		this.chromogisaurusIschigualastoHillsSpawnWeight = buildInt(builder, "Chromogisaurus Ischigualasto Hills Spawn Rate", "all", 10, 0, 300, "The spawn rate of Chromogisaurus in the Ischigualasto Hills biome. Default is 10");
		this.exaeretodonIschigualastoHillsSpawnWeight = buildInt(builder, "Exaeretodon Ischigualasto Hills Spawn Rate", "all", 12, 0, 300, "The spawn rate of Exaeretodon in the Ischigualasto Hills biome. Default is 12");
		this.herrerasaurusIschigualastoHillsSpawnWeight = buildInt(builder, "Herrerasaurus Ischigualasto Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Herrerasaurus in the Ischigualasto Hills biome. Default is 8");
		this.hyperodapedonIschigualastoHillsSpawnWeight = buildInt(builder, "Hyperodapedon Ischigualasto Hills Spawn Rate", "all", 15, 0, 300, "The spawn rate of Hyperodapedon in the Ischigualasto Hills biome. Default is 15");
		this.ischigualastiaIschigualastoHillsSpawnWeight = buildInt(builder, "Ischigualastia Ischigualasto Hills Spawn Rate", "all", 8, 0, 300, "The spawn rate of Ischigualastia in the Ischigualasto Hills biome. Default is 8");
		this.sillosuchusIschigualastoHillsSpawnWeight = buildInt(builder, "Sillosuchus Ischigualasto Hills Spawn Rate", "all", 6, 0, 300, "The spawn rate of Sillosuchus in the Ischigualasto Hills biome. Default is 6");
		this.saurosuchusIschigualastoHillsSpawnWeight = buildInt(builder, "Saurosuchus Ischigualasto Hills Spawn Rate", "all", 4, 0, 300, "The spawn rate of Saurosuchus in the Ischigualasto Hills biome. Default is 4");
		this.caveSentinelIschigualastoHillsSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto Hills Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Ischigualasto Hills biome. Default is 5");
		this.landSentinelIschigualastoHillsSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto Hills Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Ischigualasto Hills biome. Default is 2");
		builder.pop();
		builder.push("Ischigualasto River");
		this.ceratodusIschigualastoRiverSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto River Spawn Rate", "all", 3, 0, 300, "The spawn rate of Ceratodus in the Ischigualasto River biome. Default is 3");
		this.caveSentinelIschigualastoRiverSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto River Spawn Rate", "all", 5, 0, 300, "The spawn rate of Cave Sentinels in the Ischigualasto River biome. Default is 5");
		this.landSentinelIschigualastoRiverSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto River Spawn Rate", "all", 2, 0, 300, "The spawn rate of Land Sentinels in the Ischigualasto River biome. Default is 2");
		builder.pop(2);
		builder.push("Misc Settings");
		this.superSecretSetting = buildBoolean(builder, "Super Secret Setting", "all", false, "Even I don't know what it does. Default is false");
		this.cretaceousDimensionID = buildInt(builder, "Cretaceous Dimension ID", "all", 9, Integer.MIN_VALUE, Integer.MAX_VALUE, "Cretaceous Dimension ID. Default is 9");
		this.jurassicDimensionID = buildInt(builder, "Jurassic Dimension ID", "all", 8, Integer.MIN_VALUE, Integer.MAX_VALUE, "Jurassic Dimension ID. Default is 8");
		this.triassicDimensionID = buildInt(builder, "Triassic Dimension ID", "all", 7, Integer.MIN_VALUE, Integer.MAX_VALUE, "Triassic Dimension ID. Default is 7");
		this.spaceTimeContinuumWarping = buildBoolean(builder, "Space Time Continuum Warping", "all", false, "Warning: Messing with the time space continuum may lead to unforseen consequences. Recommended to keep false for servers. Default is false");
		this.geologyHammerMining = buildBoolean(builder, "Geological Hammer Stone Breaking", "all", true, "Toggles whether stones can be broken down using the Geological Hammer. Default is true");
		builder.pop();
		builder.push("Structures");
		this.hellCreekHutMinDistance = buildInt(builder, "Hell Creek Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Hell Creek Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.hellCreekHutMaxDistance = buildInt(builder, "Hell Creek Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Hell Creek Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.morrisonHutMinDistance = buildInt(builder, "Morrison Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Morrison Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.morrisonHutMaxDistance = buildInt(builder, "Morrison Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Morrison Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.ischigualastoHutMinDistance = buildInt(builder, "Ischigualasto Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Ischigualasto Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.ischigualastoHutMaxDistance = buildInt(builder, "Ischigualasto Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Ischigualasto Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.djadochtaHutMinDistance = buildInt(builder, "Djadochta Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Djadochta Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.djadochtaHutMaxDistance = buildInt(builder, "Djadochta Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Djadochta Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.kayentaHutMinDistance = buildInt(builder, "Kayenta Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Kayenta Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.kayentaHutMaxDistance = buildInt(builder, "Kayenta Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Kayenta Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.chinleHutMinDistance = buildInt(builder, "Chinle Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Chinle Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.chinleHutMaxDistance = buildInt(builder, "Chinle Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Chinle Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.geologistCampMinDistance = buildInt(builder, "Geologist Camp Min Distance", "all", 25, 1, 300, "The closest two Geologist Camps can spawn from eachother. Keep this value lower than the max. Default is 25");
		this.geologistCampMaxDistance = buildInt(builder, "Geologist Camp Max Distance", "all", 50, 1, 300, "The farthest two Geologist Camps can spawn from eachother. Keep this value higher than the min. Default is 50");
		this.timeTempleMinDistance = buildInt(builder, "Time Temple Min Distance", "all", 75, 1, 300, "The closest two Time Temples can spawn from eachother. Keep this value lower than the max. Default is 75");
		this.timeTempleMaxDistance = buildInt(builder, "Time Temple Max Distance", "all", 100, 1, 300, "The farthest two Time Temples can spawn from eachother. Keep this value higher than the min. Default is 100");
		this.portalHubMinDistance = buildInt(builder, "Portal Hub Min Distance", "all", 40, 1, 300, "The closest two Portal Hubs can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.portalHubMaxDistance = buildInt(builder, "Portal Hub Hut Max Distance", "all", 60, 1, 300, "The farthest two Portal Hubs can spawn from eachother. Keep this value higher than the min. Default is 60");
		builder.pop();
		builder.push("World Generation");
		this.baseStoneWeight = buildInt(builder, "Base Stone Weight", "all", 97, 1, 300, "The probability of an ancient stone deposit is made up of the base stone. To find the percentage probability, add the base stone weight with the fossil weight, and then divide the base stone weight by the combined weights. Default is 97");
		this.fossilWeight = buildInt(builder, "Fossil Weight", "all", 3, 1, 300, "The probability of an ancient stone deposit is made up of the fossilized stone. To find the percentage probability, add the base stone weight with the fossil weight, and then divide the fossil stone weight by the combined weights. Default is 3");
		builder.pop();
		builder.push("AI Config");
		this.sleeping = buildBoolean(builder, "Sleeping AI", "all", true, "Toggles whether all prehistoric animals sleep or not. Default is true");
		this.advancedHunger = buildBoolean(builder, "Advanced Hunger AI", "all", true, "Toggles whether all prehistoric animals are affected by hunger. Default is true");
		this.hungerDamage = buildBoolean(builder, "Hunger Damage", "all", false, "Toggles whether entities take damage from being hungry. Default is false");
		this.naturalEggBlockLaying = buildBoolean(builder, "Natural Egg Laying AI - Blocks", "all", true, "Toggles whether entities lay their eggs as blocks naturally when full. Default is true");
		this.naturalEggItemLaying = buildBoolean(builder, "Natural Egg Laying AI - Items", "all", false, "Toggles whether entities lay their eggs as items naturally when full. Default is false");
		this.hostileCarnivores = buildBoolean(builder, "Hostile Carnivores", "all", false, "Toggles whether carnivorous entities will attack the player on sight or not, creating a more difficult environment. Default is false");
		this.unscheduledSleeping = buildBoolean(builder, "Unscheduled Sleeping", "all", false, "Toggles whether prehistoric entities sleep randomly, instead of being diurnal, nocturnal, crepuscular, or cathemeral. Default is false");
		this.sauropodTrampling = buildBoolean(builder, "Sauropod Trampling", "all", true, "Toggles whether large sauropods can trample smaller animals. Default is true");
		builder.pop();
	}
	
	private static ForgeConfigSpec.BooleanValue buildBoolean(ForgeConfigSpec.Builder builder, String name, String catagory, boolean defaultValue, String comment){
		return builder.comment(comment).translation(name).define(name, defaultValue);
	}

	private static ForgeConfigSpec.IntValue buildInt(ForgeConfigSpec.Builder builder, String name, String catagory, int defaultValue, int min, int max, String comment){
		return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
	}

	@SuppressWarnings("unused")
	private static ForgeConfigSpec.DoubleValue buildDouble(ForgeConfigSpec.Builder builder, String name, String catagory, double defaultValue, double min, double max, String comment){
		return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
	}
	
}
