package superlord.prehistoricfauna.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class ServerConfig {
	//Hell Creek Redwood Forest
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue dideldophodonHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue garHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekForestSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekForestSpawnWeight;
	//Hell Creek Fern Prairie
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue dideldophodonHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue garHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekClearingSpawnWeight;
	//Hell Creek Liriodendrites Hills
	public final ForgeConfigSpec.IntValue thescelosaurusHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue triceratopsHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ankylosaurusHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue tyrannosaurusHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue basilemysHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue dakotaraptorHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue dideldophodonHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue myledaphusHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue garHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekHillsSpawnWeight;
	//Hell Creek River
	public final ForgeConfigSpec.IntValue myledaphusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue garHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue cyclurusHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelHellCreekRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelHellCreekRiverSpawnWeight;
	//Morrison Savanna
	public final ForgeConfigSpec.IntValue stegosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue dryosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue allosaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue hesperornithoidesMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue eilenodonMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue camarasaurusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelMorrisonSavannahSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelMorrisonSavannahSpawnWeight;
	//Morrison Hills
	public final ForgeConfigSpec.IntValue stegosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue dryosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue allosaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue hesperornithoidesMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue eilenodonMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue camarasaurusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelMorrisonHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelMorrisonHillsSpawnWeight;
	//Ischigualasto Forest
	public final ForgeConfigSpec.IntValue exaeretodonIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue chromogisaurusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue herrerasaurusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue hyperodapedonIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue sillosuchusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue saurosuchusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ischigualastiaIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoForestSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoForestSpawnWeight;
	//Ischigualasto Clearing
	public final ForgeConfigSpec.IntValue exaeretodonIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue chromogisaurusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue herrerasaurusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue hyperodapedonIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue sillosuchusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue saurosuchusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue ischigualastiaIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoClearingSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoClearingSpawnWeight;
	//Ischigualasto Hills
	public final ForgeConfigSpec.IntValue exaeretodonIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue chromogisaurusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue herrerasaurusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue hyperodapedonIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue sillosuchusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue saurosuchusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ischigualastiaIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoHillsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoHillsSpawnWeight;
	//Ischigualasto River
	public final ForgeConfigSpec.IntValue ceratodusIschigualastoRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelIschigualastoRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelIschigualastoRiverSpawnWeight;
	//Djadochta Dunes
	public final ForgeConfigSpec.IntValue protoceratopsDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue citipatiDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue velociraptorDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue aepyornithomimusDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue telmasaurusDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue pinacosaurusDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue plesiohadrosDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelDjadochtaDunesSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelDjadochtaDunesSpawnWeight;
	//Djadochta Arroyo
	public final ForgeConfigSpec.IntValue protoceratopsDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue velociraptorDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue citipatiDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue aepyornithomimusDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue telmasaurusDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue pinacosaurusDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue plesiohadrosDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelDjadochtaArroyoSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelDjadochtaArroyoSpawnWeight;
	//Kayenta Buttes
	public final ForgeConfigSpec.IntValue dilophosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue sarahsaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue scelidosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue scutellosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue megapnosaurusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue kayentatheriumKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue calsoyasuchusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelKayentaButtesSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelKayentaButtesSpawnWeight;
	//Kayenta Desert
	public final ForgeConfigSpec.IntValue dilophosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue sarahsaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue scelidosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue scutellosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue megapnosaurusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue kayentatheriumKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue calsoyasuchusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelKayentaDesertSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelKayentaDesertSpawnWeight;
	//Kayenta Dry Forest
	public final ForgeConfigSpec.IntValue dilophosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue sarahsaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue scelidosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue scutellosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue megapnosaurusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue kayentatheriumKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue calsoyasuchusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue ceratodusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue potamoceratodusKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelKayentaDryForestSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelKayentaDryForestSpawnWeight;
	//Chinle Swamp
	public final ForgeConfigSpec.IntValue coelophysisChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue desmatosuchusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue placeriasChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue poposaurusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue postosuchusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue trilophosaurusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue typothoraxChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue chinleaChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleSwampSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleSwampSpawnWeight;
	//Chinle Flats
	public final ForgeConfigSpec.IntValue coelophysisChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue desmatosuchusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue placeriasChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue poposaurusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue postosuchusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue trilophosaurusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue typothoraxChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue chinleaChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleFlatsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleFlatsSpawnWeight;
	//Chinle River
	public final ForgeConfigSpec.IntValue chinleaChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleRiverSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleRiverSpawnWeight;
	//Chinle Wooded Mountains
	public final ForgeConfigSpec.IntValue coelophysisChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue desmatosuchusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue placeriasChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue poposaurusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue postosuchusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue trilophosaurusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue typothoraxChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue chinleaChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue arganodusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue mooreodontusChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue saurichthysChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue caveSentinelChinleWoodedMountainsSpawnWeight;
	public final ForgeConfigSpec.IntValue landSentinelChinleWoodedMountainsSpawnWeight;

	public final ForgeConfigSpec.BooleanValue superSecretSetting;
	public final ForgeConfigSpec.IntValue cretaceousDimensionID;
	public final ForgeConfigSpec.IntValue jurassicDimensionID;
	public final ForgeConfigSpec.IntValue triassicDimensionID;
	public final ForgeConfigSpec.IntValue hellCreekHutMinDistance;
	public final ForgeConfigSpec.IntValue hellCreekHutMaxDistance;
	public final ForgeConfigSpec.IntValue morrisonHutMinDistance;
	public final ForgeConfigSpec.IntValue morrisonHutMaxDistance;
	public final ForgeConfigSpec.IntValue ischigualastoHutMinDistance;
	public final ForgeConfigSpec.IntValue ischigualastoHutMaxDistance;
	public final ForgeConfigSpec.IntValue djadochtaHutMinDistance;
	public final ForgeConfigSpec.IntValue djadochtaHutMaxDistance;
	public final ForgeConfigSpec.IntValue kayentaHutMinDistance;
	public final ForgeConfigSpec.IntValue kayentaHutMaxDistance;
	public final ForgeConfigSpec.IntValue chinleHutMinDistance;
	public final ForgeConfigSpec.IntValue chinleHutMaxDistance;
	public final ForgeConfigSpec.IntValue geologistCampMinDistance;
	public final ForgeConfigSpec.IntValue geologistCampMaxDistance;
	public final ForgeConfigSpec.IntValue timeTempleMinDistance;
	public final ForgeConfigSpec.IntValue timeTempleMaxDistance;
	public final ForgeConfigSpec.IntValue portalHubMinDistance;
	public final ForgeConfigSpec.IntValue portalHubMaxDistance;
	public final ForgeConfigSpec.BooleanValue spaceTimeContinuumWarping;
	public final ForgeConfigSpec.BooleanValue geologyHammerMining;
	public final ForgeConfigSpec.IntValue baseStoneWeight;
	public final ForgeConfigSpec.IntValue fossilWeight;
	public final ForgeConfigSpec.BooleanValue sleeping;
	public final ForgeConfigSpec.BooleanValue advancedHunger;
	public final ForgeConfigSpec.BooleanValue hungerDamage;
	public final ForgeConfigSpec.BooleanValue naturalEggBlockLaying;
	public final ForgeConfigSpec.BooleanValue naturalEggItemLaying;
	public final ForgeConfigSpec.IntValue petrifiedForestWeight;
	
	public ServerConfig(final ForgeConfigSpec.Builder builder) {
		builder.push("Djadochta Formation");
		builder.push("Djadochta Arroyo");
		this.aepyornithomimusDjadochtaArroyoSpawnWeight = buildInt(builder, "Aepyornithomimus Djadochta Arroyo Spawn Weight", "all", 12, 0, 300, "The weight of Aepyornithomimus in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 12");
		this.citipatiDjadochtaArroyoSpawnWeight = buildInt(builder, "Citipati Djadochta Arroyo Spawn Weight", "all", 5, 0, 300, "The weight of Citipati in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 5");
		this.pinacosaurusDjadochtaArroyoSpawnWeight = buildInt(builder, "Pinacosaurus Djadochta Arroyo Spawn Weight", "all", 7, 0, 300, "The weight of Pinacosaurus in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 7");
		this.plesiohadrosDjadochtaArroyoSpawnWeight = buildInt(builder, "Plesiohadros Djadochta Arroyo Spawn Weight", "all", 8, 0, 300, "The weight of Plesiohadros in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 8");
		this.protoceratopsDjadochtaArroyoSpawnWeight = buildInt(builder, "Protoceratops Djadochta Arroyo Spawn Weight", "all", 4, 0, 300, "The weight of Protoceratops in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 4");
		this.telmasaurusDjadochtaArroyoSpawnWeight = buildInt(builder, "Telmasaurus Djadochta Arroyo Spawn Weight", "all", 2, 0, 300, "The weight of Telmasauru in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 2");
		this.velociraptorDjadochtaArroyoSpawnWeight = buildInt(builder, "Velociraptor Djadochta Arroyo Spawn Weight", "all", 3, 0, 300, "The weight of Velociraptor in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 3");
		this.caveSentinelDjadochtaArroyoSpawnWeight = buildInt(builder, "Cave Sentinel Djaodochta Arroyo Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 5");
		this.landSentinelDjadochtaArroyoSpawnWeight = buildInt(builder, "Land Sentinel Djadochta Arroyo Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Djadochta Arroyo biome. Default is 2");
		builder.pop();
		builder.push("Djadochta Dunes");
		this.aepyornithomimusDjadochtaDunesSpawnWeight = buildInt(builder, "Aepyornithomimus Djadochta Dunes Spawn Weight", "all", 2, 0, 300, "The weight of Aepyornithomimus in vanilla's spawn rate in the Djadochta Dunes biome. Default is 3");
		this.citipatiDjadochtaDunesSpawnWeight = buildInt(builder, "Citipati Djadochta Dunes Spawn Weight", "all", 5, 0, 300, "The weight of Citipati in vanilla's spawn rate in the Djadochta Dunes biome. Default is 5");
		this.pinacosaurusDjadochtaDunesSpawnWeight = buildInt(builder, "Pinacosaurus Djadochta Dunes Spawn Weight", "all", 5, 0, 300, "The weight of Pinacosaurus in vanilla's spawn rate in the Djadochta Dunes biome. Default is 5");
		this.plesiohadrosDjadochtaDunesSpawnWeight = buildInt(builder, "Plesiohadros Djadochta Dunes Spawn Weight", "all", 0, 0, 300, "The weight of Plesiohadros in vanilla's spawn rate in the Djadochta Dunes biome. Default is 0");
		this.protoceratopsDjadochtaDunesSpawnWeight = buildInt(builder, "Protoceratops Djadochta Dunes Spawn Weight", "all", 7, 0, 300, "The weight of Protoceratops in vanilla's spawn rate in the Djadochta Dunes biome. Default is 7");
		this.telmasaurusDjadochtaDunesSpawnWeight = buildInt(builder, "Telmasaurus Djadochta Dunes Spawn Weight", "all", 3, 0, 300, "The weight of Telmasaurus in vanilla's spawn rate in the Djadochta Dunes biome. Default is 3");
		this.velociraptorDjadochtaDunesSpawnWeight = buildInt(builder, "Velociraptor Djadochta Dunes Spawn Weight", "all", 6, 0, 300, "The weight of Velociraptor in vanilla's spawn rate in the Djadochta Dunes biome. Default is 6");
		this.caveSentinelDjadochtaDunesSpawnWeight = buildInt(builder, "Cave Sentinel Djaodochta Dunes Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Djadochta Dunes biome. Default is 5");
		this.landSentinelDjadochtaDunesSpawnWeight = buildInt(builder, "Land Sentinel Djadochta Dunes Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Djadochta Dunes biome. Default is 2");
		builder.pop(2);
		builder.push("Hell Creek Formation");
		builder.push("Hell Creek Forest");
		this.ankylosaurusHellCreekForestSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Forest Spawn Weight", "all", 14, 0, 300, "The weight of Ankylosaurus in vanilla's spawn rate in the Hell Creek Forest biome. Default is 14");
		this.basilemysHellCreekForestSpawnWeight = buildInt(builder, "Basilemys Hell Creek Forest Spawn Weight", "all", 7, 0, 300, "The weight of Basilemys in vanilla's spawn rate in the Hell Creek Forest biome. Default is 7");
		this.cyclurusHellCreekForestSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Forest Spawn Weight", "all", 1, 0, 300, "The weight of Cyclurus in vanilla's spawn rate in the Hell Creek Forest biome. Default is 1");
		this.dakotaraptorHellCreekForestSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Forest Spawn Weight", "all", 2, 0, 300, "The weight of Dakotaraptor in vanilla's spawn rate in the Hell Creek Forest biome. Default is 2");
		this.dideldophodonHellCreekForestSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Forest Spawn Weight", "all", 6, 0, 300, "The weight of Didelphodon in vanilla's spawn rate in the Hell Creek Forest biome. Default is 6");
		this.garHellCreekForestSpawnWeight = buildInt(builder, "Gar Hell Creek Forest Spawn Weight", "all", 4, 0, 300, "The weight of Gar in vanilla's spawn rate in the Hell Creek Forest biome. Default is 4");
		this.myledaphusHellCreekForestSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Forest Spawn Weight", "all", 0, 0, 300, "The weight of Myledaphus in vanilla's spawn rate in the Hell Creek Forest biome. Default is 0");
		this.thescelosaurusHellCreekForestSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Forest Spawn Weight", "all", 12, 0, 300, "The weight of Thescelosaurus in vanilla's spawn rate in the Hell Creek Forest biome. Default is 12");
		this.triceratopsHellCreekForestSpawnWeight = buildInt(builder, "Triceratops Hell Creek Forest Spawn Weight", "all", 7, 0, 300, "The weight of Triceratops in vanilla's spawn rate in the Hell Creek Forest biome. Default is 7");
		this.tyrannosaurusHellCreekForestSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Forest Spawn Weight", "all", 10, 0, 300, "The weight of Tyrannosaurus in vanilla's spawn rate in the Hell Creek Forest biome. Default is 10");
		this.caveSentinelHellCreekForestSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Forest Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Hell Creek Forest biome. Default is 5");
		this.landSentinelHellCreekForestSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Forest Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Hell Creek Forest biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek Fern Prairie");
		this.ankylosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Fern Prairie Spawn Weight", "all", 7, 0, 300, "The weight of Ankylosaurus in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 7");
		this.basilemysHellCreekClearingSpawnWeight = buildInt(builder, "Basilemys Hell Creek Fern Prairie Spawn Weight", "all", 9, 0, 300, "The weight of Basilemys in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 9");
		this.cyclurusHellCreekClearingSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Fern Prairie Spawn Weight", "all", 1, 0, 300, "The weight of Cyclurus in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 1");
		this.dakotaraptorHellCreekClearingSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Fern Prairie Spawn Weight", "all", 2, 0, 300, "The weight of Dakotaraptor in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 2");
		this.dideldophodonHellCreekClearingSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Fern Prairie Spawn Weight", "all", 6, 0, 300, "The weight of Didelphodon in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 6");
		this.garHellCreekClearingSpawnWeight = buildInt(builder, "Gar Hell Creek Fern Prairie Spawn Weight", "all", 4, 0, 300, "The weight of Gar in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 4");
		this.myledaphusHellCreekClearingSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Fern Prairie Spawn Weight", "all", 0, 0, 300, "The weight of Myledaphus in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 0");
		this.thescelosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Fern Prairie Spawn Weight", "all", 10, 0, 300, "The weight of Thescelosaurus in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 10");
		this.triceratopsHellCreekClearingSpawnWeight = buildInt(builder, "Triceratops Hell Creek Fern Prairie Spawn Weight", "all", 15, 0, 300, "The weight of Triceratops in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 15");
		this.tyrannosaurusHellCreekClearingSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Fern Prairie Spawn Weight", "all", 10, 0, 300, "The weight of Tyrannosaurus in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 10");
		this.caveSentinelHellCreekClearingSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Fern Prairie Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 5");
		this.landSentinelHellCreekClearingSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Fern Prairie Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Hell Creek Fern Prairie biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek Liriodendrites Forest");
		this.ankylosaurusHellCreekHillsSpawnWeight = buildInt(builder, "Ankylosaurus Hell Creek Liriodendrites Forest Spawn Weight", "all", 14, 0, 300, "The weight of Ankylosaurus in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 14");
		this.basilemysHellCreekHillsSpawnWeight = buildInt(builder, "Basilemys Hell Creek Liriodendrites Forest Spawn Weight", "all", 7, 0, 300, "The weight of Basilemys in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 7");
		this.cyclurusHellCreekHillsSpawnWeight = buildInt(builder, "Cyclurus Hell Creek Liriodendrites Forest Spawn Weight", "all", 1, 0, 300, "The weight of Cyclurus in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 1");
		this.dakotaraptorHellCreekHillsSpawnWeight = buildInt(builder, "Dakotaraptor Hell Creek Liriodendrites Forest Spawn Weight", "all", 2, 0, 300, "The weight of Dakotaraptor in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 2");
		this.dideldophodonHellCreekHillsSpawnWeight = buildInt(builder, "Didelphodon Hell Creek Liriodendrites Forest Spawn Weight", "all", 6, 0, 300, "The weight of Didelphodon in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 6");
		this.garHellCreekHillsSpawnWeight = buildInt(builder, "Gar Hell Creek Liriodendrites Forest Spawn Weight", "all", 4, 0, 300, "The weight of Gar in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 4");
		this.myledaphusHellCreekHillsSpawnWeight = buildInt(builder, "Myledaphus Hell Creek Liriodendrites Forest Spawn Weight", "all", 0, 0, 300, "The weight of Myledaphus in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 0");
		this.thescelosaurusHellCreekHillsSpawnWeight = buildInt(builder, "Thescelosaurus Hell Creek Liriodendrites Forest Spawn Weight", "all", 7, 0, 300, "The weight of Thescelosaurus in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 7");
		this.triceratopsHellCreekHillsSpawnWeight = buildInt(builder, "Triceratops Hell Creek Liriodendrites Forest Spawn Weight", "all", 7, 0, 300, "The weight of Triceratops in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 7");
		this.tyrannosaurusHellCreekHillsSpawnWeight = buildInt(builder, "Tyrannosaurus Hell Creek Forest Liriodendrites Spawn Weight", "all", 10, 0, 300, "The weight of Tyrannosaurus in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 10");
		this.caveSentinelHellCreekHillsSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek Liriodendrites Forest Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 5");
		this.landSentinelHellCreekHillsSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek Liriodendrites Forest Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Hell Creek Liriodendrites Forest biome. Default is 2");
		builder.pop();
		builder.push("Hell Creek River");
		this.cyclurusHellCreekRiverSpawnWeight = buildInt(builder, "Cyclurus Hell Creek River Spawn Weight", "all", 1, 0, 300, "The weight of Cyclurus in vanilla's spawn rate in the Hell Creek River biome. Default is 1");
		this.garHellCreekRiverSpawnWeight = buildInt(builder, "Gar Hell Creek River Spawn Weight", "all", 4, 0, 300, "The weight of Gar in vanilla's spawn rate in the Hell Creek River biome. Default is 4");
		this.myledaphusHellCreekRiverSpawnWeight = buildInt(builder, "Myledaphus Hell Creek River Spawn Weight", "all", 2, 0, 300, "The weight of Myledaphus in vanilla's spawn rate in the Hell Creek River biome. Default is 2");
		this.caveSentinelHellCreekRiverSpawnWeight = buildInt(builder, "Cave Sentinel Hell Creek River Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Hell Creek River biome. Default is 5");
		this.landSentinelHellCreekRiverSpawnWeight = buildInt(builder, "Land Sentinel Hell Creek River Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Hell Creek River biome. Default is 2");
		builder.pop(2);
		builder.push("Kayenta Formation");
		builder.push("Kayenta Canyon");
		this.calsoyasuchusKayentaButtesSpawnWeight = buildInt(builder, "Calsoyasuchus Kayenta Canyon Spawn Weight", "all", 2, 0, 300, "The weight of Calsoyasuchus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 2");
		this.ceratodusKayentaButtesSpawnWeight = buildInt(builder, "Ceratodus Kayenta Canyon Spawn Weight", "all", 0, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 0");
		this.dilophosaurusKayentaButtesSpawnWeight = buildInt(builder, "Dilophosaurus Kayenta Canyon Spawn Weight", "all", 5, 0, 300, "The weight of Dilophosaurus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 5");
		this.kayentatheriumKayentaButtesSpawnWeight = buildInt(builder, "Kayentatherium Kayenta Canyon Spawn Weight", "all", 1, 0, 300, "The weight of Kayentatherium in vanilla's spawn rate in the Kayenta Canyon biome. Default is 1");
		this.megapnosaurusKayentaButtesSpawnWeight = buildInt(builder, "Megapnosaurus Kayenta Canyon Spawn Weight", "all", 8, 1, 300, "The weight of Megapnosaurus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 8");
		this.potamoceratodusKayentaButtesSpawnWeight = buildInt(builder, "Potamoceratodus Kayenta Canyon Spawn Weight", "all", 2, 0, 300, "The weight of Potamoceratodus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 2");
		this.sarahsaurusKayentaButtesSpawnWeight = buildInt(builder, "Sarahsaurus Kayenta Canyon Spawn Weight", "all", 4, 0, 300, "The weight of Sarahsaurus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 4");
		this.scelidosaurusKayentaButtesSpawnWeight = buildInt(builder, "Scelidosaurus Kayenta Canyon Spawn Weight", "all", 10, 0, 300, "The weight of Scelidosaurus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 10");
		this.scutellosaurusKayentaButtesSpawnWeight = buildInt(builder, "Scutellosaurus Kayenta Canyon Spawn Weight", "all", 7, 0, 300, "The weight of Scutellosaurus in vanilla's spawn rate in the Kayenta Canyon biome. Default is 7");
		this.caveSentinelKayentaButtesSpawnWeight = buildInt(builder, "Cave Sentinel Kayenta Canyon Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Kayenta Canyon biome. Default is 5");
		this.landSentinelKayentaButtesSpawnWeight = buildInt(builder, "Land Sentinel Kayenta Canyon Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Kayenta Canyon biome. Default is 2");
		builder.pop();
		builder.push("Kayenta Desert");
		this.calsoyasuchusKayentaDesertSpawnWeight = buildInt(builder, "Calsoyasuchus Kayenta Desert Spawn Weight", "all", 1, 0, 300, "The weight of Calsoyasuchus in vanilla's spawn rate in the Kayenta Desert biome. Default is 1");
		this.ceratodusKayentaDesertSpawnWeight = buildInt(builder, "Ceratodus Kayenta Desert Spawn Weight", "all", 2, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Kayenta Desert biome. Default is 2");
		this.dilophosaurusKayentaDesertSpawnWeight = buildInt(builder, "Dilophosaurus Kayenta Desert Spawn Weight", "all", 3, 0, 300, "The weight of Dilophosaurus in vanilla's spawn rate in the Kayenta Desert biome. Default is 3");
		this.kayentatheriumKayentaDesertSpawnWeight = buildInt(builder, "Kayentatherium Kayenta Desert Spawn Weight", "all", 2, 0, 300, "The weight of Kayentatherium in vanilla's spawn rate in the Kayenta Desert biome. Default is 2");
		this.megapnosaurusKayentaDesertSpawnWeight = buildInt(builder, "Megapnosaurus Kayenta Desert Spawn Weight", "all", 5, 1, 300, "The weight of Megapnosaurus in vanilla's spawn rate in the Kayenta Desert biome. Default is 5");
		this.potamoceratodusKayentaDesertSpawnWeight = buildInt(builder, "Potamoceratodus Kayenta Desert Spawn Weight", "all", 2, 0, 300, "The weight of Potamoceratodus in vanilla's spawn rate in the Kayenta Desert biome. Default is 2");
		this.sarahsaurusKayentaDesertSpawnWeight = buildInt(builder, "Sarahsaurus Kayenta Desert Spawn Weight", "all", 4, 0, 300, "The weight of Sarahsaurus in vanilla's spawn rate in the Kayenta Desert biome. Default is 4");
		this.scelidosaurusKayentaDesertSpawnWeight = buildInt(builder, "Scelidosaurus Kayenta Desert Spawn Weight", "all", 4, 0, 300, "The weight of Scelidosaurus in vanilla's spawn rate in the Kayenta Desert biome. Default is 4");
		this.scutellosaurusKayentaDesertSpawnWeight = buildInt(builder, "Scutellosaurus Kayenta Desert Spawn Weight", "all", 2, 0, 300, "The weight of Scutellosaurus in vanilla's spawn rate in the Kayenta Desert biome. Default is 2");
		this.caveSentinelKayentaDesertSpawnWeight = buildInt(builder, "Cave Sentinel Kayenta Desert Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Kayenta Desert biome. Default is 5");
		this.landSentinelKayentaDesertSpawnWeight = buildInt(builder, "Land Sentinel Kayenta Desert Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Kayenta Desert biome. Default is 2");
		builder.pop();
		builder.push("Kayenta Dry Forest");
		this.calsoyasuchusKayentaDryForestSpawnWeight = buildInt(builder, "Calsoyasuchus Kayenta Dry Forest Spawn Weight", "all", 5, 0, 300, "The weight of Calsoyasuchus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 5");
		this.ceratodusKayentaDryForestSpawnWeight = buildInt(builder, "Ceratodus Kayenta Dry Forest Spawn Weight", "all", 3, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 3");
		this.dilophosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Dilophosaurus Kayenta Dry Forest Spawn Weight", "all", 4, 0, 300, "The weight of Dilophosaurus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 4");
		this.kayentatheriumKayentaDryForestSpawnWeight = buildInt(builder, "Kayentatherium Kayenta Dry Forest Spawn Weight", "all", 7, 0, 300, "The weight of Kayentatherium in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 7");
		this.megapnosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Megapnosaurus Kayenta Dry Forest Spawn Weight", "all", 2, 1, 300, "The weight of Megapnosaurus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 2");
		this.potamoceratodusKayentaDryForestSpawnWeight = buildInt(builder, "Potamoceratodus Kayenta Dry Forest Spawn Weight", "all", 2, 0, 300, "The weight of Potamoceratodus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 2");
		this.sarahsaurusKayentaDryForestSpawnWeight = buildInt(builder, "Sarahsaurus Kayenta Dry Forest Spawn Weight", "all", 6, 0, 300, "The weight of Sarahsaurus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 6");
		this.scelidosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Scelidosaurus Kayenta Dry Forest Spawn Weight", "all", 2, 0, 300, "The weight of Scelidosaurus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 2");
		this.scutellosaurusKayentaDryForestSpawnWeight = buildInt(builder, "Scutellosaurus Kayenta Dry Forest Spawn Weight", "all", 8, 0, 300, "The weight of Scutellosaurus in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 8");
		this.caveSentinelKayentaDryForestSpawnWeight = buildInt(builder, "Cave Sentinel Kayenta Dry Forest Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 5");
		this.landSentinelKayentaDryForestSpawnWeight = buildInt(builder, "Land Sentinel Kayenta Dry Forest Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Kayenta Dry Forest biome. Default is 2");
		builder.pop(2);
		builder.push("Morrison Formation");
		builder.push("Morrison Hills");
		this.allosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Allosaurus Morrison Hills Spawn Weight", "all", 3, 0, 300, "The weight of Allosaurus in vanilla's spawn rate in the Morrison Hills biome. Default is 3");
		this.camarasaurusMorrisonHillsSpawnWeight = buildInt(builder, "Camarasaurus Morrison Hills Spawn Weight", "all", 2, 0, 300, "The weight of Camarasaurus in vanilla's spawn rate in the Morrison Hills biome. Default is 2");
		this.ceratodusMorrisonHillsSpawnWeight = buildInt(builder, "Ceratodus Morrison Hills Spawn Weight", "all", 1, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Morrison Hills biome. Default is 1");
		this.ceratosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Ceratosaurus Morrison Hills Spawn Weight", "all", 2, 0, 300, "The weight of Ceratosaurus in vanilla's spawn rate in the Morrison Hills biome. Default is 2");
		this.dryosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Dryosaurus Morrison Hills Spawn Weight", "all", 7, 0, 300, "The weight of Dryosaurus in vanilla's spawn rate in the Morrison Hills biome. Default is 7");
		this.eilenodonMorrisonHillsSpawnWeight = buildInt(builder, "Eilenodon Morrison Hills Spawn Weight", "all", 8, 0, 300, "The weight of Eilenodon in vanilla's spawn rate in the Morrison Hills biome. Default is 5");
		this.hesperornithoidesMorrisonHillsSpawnWeight = buildInt(builder, "Hesperornithoides Morrison Hills Spawn Rate", "all", 7, 0, 300, "The weight of Hesperornithoides in vanilla's spawn rate in the Morrison Hills biome. Default is 4");
		this.potamoceratodusMorrisonHillsSpawnWeight = buildInt(builder, "Potamoceratodus Morrison Hills Spawn Weight", "all", 3, 0, 300, "The weight of Potamoceratodus in vanilla's spawn rate in the Morrison Hills biome. Default is 3");
		this.stegosaurusMorrisonHillsSpawnWeight = buildInt(builder, "Stegosaurus Morrison Hills Spawn Weight", "all", 10, 0, 300, "The weight of Stegosaurus in vanilla's spawn rate in the Morrison Hills biome. Default is 10");
		this.caveSentinelMorrisonHillsSpawnWeight = buildInt(builder, "Cave Sentinel Morrison Hills Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Morrison Hills biome. Default is 5");
		this.landSentinelMorrisonHillsSpawnWeight = buildInt(builder, "Land Sentinel Morrison Hills Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Morrison Hills biome. Default is 2");
		builder.pop();
		builder.push("Morrison Savanna");
		this.allosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Allosaurus Morrison Savanna Spawn Weight", "all", 3, 0, 300, "The weight of Allosaurus in vanilla's spawn rate in the Morrison Savanna biome. Default is 3");
		this.camarasaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Camarasaurus Morrison Savanna Spawn Weight", "all", 2, 0, 300, "The weight of Camarasaurus in vanilla's spawn rate in the Morrison Savanna biome. Default is 2");
		this.ceratodusMorrisonSavannahSpawnWeight = buildInt(builder, "Ceratodus Morrison Savanna Spawn Weight", "all", 1, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Morrison Savanna biome. Default is 1");
		this.ceratosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Ceratosaurus Morrison Savanna Spawn Weight", "all", 2, 0, 300, "The weight of Ceratosaurus in vanilla's spawn rate in the Morrison Savanna biome. Default is 2");
		this.dryosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Dryosaurus Morrison Savanna Spawn Weight", "all", 7, 0, 300, "The weight of Dryosaurus in vanilla's spawn rate in the Morrison Savanna biome. Default is 7");
		this.eilenodonMorrisonSavannahSpawnWeight = buildInt(builder, "Eilenodon Morrison Savanna Spawn Weight", "all", 8, 0, 300, "The weight of Eilenodon in vanilla's spawn rate in the Morrison Savanna biome. Default is 5");
		this.hesperornithoidesMorrisonSavannahSpawnWeight = buildInt(builder, "Hesperornithoides Morrison Savanna Spawn Rate", "all", 7, 0, 300, "The weight of Hesperornithoides in vanilla's spawn rate in the Morrison Savanna biome. Default is 4");
		this.potamoceratodusMorrisonSavannahSpawnWeight = buildInt(builder, "Potamoceratodus Morrison Savanna Spawn Weight", "all", 3, 0, 300, "The weight of Potamoceratodus in vanilla's spawn rate in the Morrison Savanna biome. Default is 3");
		this.stegosaurusMorrisonSavannahSpawnWeight = buildInt(builder, "Stegosaurus Morrison Savanna Spawn Weight", "all", 10, 0, 300, "The weight of Stegosaurus in vanilla's spawn rate in the Morrison Savanna biome. Default is 10");
		this.caveSentinelMorrisonSavannahSpawnWeight = buildInt(builder, "Cave Sentinel Morrison Savanna Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Morrison Savanna biome. Default is 5");
		this.landSentinelMorrisonSavannahSpawnWeight = buildInt(builder, "Land Sentinel Morrison Savanna Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Morrison Savanna biome. Default is 2");
		builder.pop(2);
		builder.push("Chinle Formation");
		builder.push("Chinle Flats");
		this.arganodusChinleFlatsSpawnWeight = buildInt(builder, "Arganodus Chinle Flats Spawn Weight", "all", 3, 0, 300, "The weight of Arganodus in vanilla's spawn rate in the Chinle Flats biome. Default is 4");
		this.chinleaChinleFlatsSpawnWeight = buildInt(builder, "Chinlea Chinle Flats Spawn Weight", "all", 4, 0, 300, "The weight of Chinlea in vanilla's spawn rate in the Chinle Flats biome. Default is 4");
		this.coelophysisChinleFlatsSpawnWeight = buildInt(builder, "Coelophysis Chinle Flats Spawn Weight", "all", 10, 0, 300, "The weight of Coelophysis in vanilla's spawn rate in the Chinle Flats biome. Default is 10");
		this.desmatosuchusChinleFlatsSpawnWeight = buildInt(builder, "Desmatosuchus Chinle Flats Spawn Weight", "all", 4, 0, 300, "The weight of Desmatosuchus in vanilla's spawn rate in the Chinle Flats biome. Default is 4");
		this.mooreodontusChinleFlatsSpawnWeight = buildInt(builder, "Mooreodontus Chinle Flats Spawn Weight", "all", 1, 0, 300, "The weight of Mooreodontus in vanilla's spawn rate in the Chinle Flats biome. Default is 1");
		this.placeriasChinleFlatsSpawnWeight = buildInt(builder, "Placerias Chinle Flats Spawn Weight", "all", 0, 0, 300, "The weight of Placerias in vanilla's spawn rate in the Chinle Flats biome. Default is 0");
		this.poposaurusChinleFlatsSpawnWeight = buildInt(builder, "Poposaurus Chinle Flats Spawn Weight", "all", 0, 0, 300, "The weight of Poposaurus in vanilla's spawn rate in the Chinle Flats biomes. Default is 0");
		this.postosuchusChinleFlatsSpawnWeight = buildInt(builder, "Postosuchus Chinle Flats Spawn Weight", "all", 6, 0, 300, "The weight of Postosuchus in vanilla's spawn rate in the Chinle Flats biome. Default is 6");
		this.saurichthysChinleFlatsSpawnWeight = buildInt(builder, "Saurichthys Chinle Flats Spawn Weight", "all", 2, 0, 300, "The weight of Saurichthys in vanilla's spawn rate in the Chinle Flats biome. Default is 2");
		this.trilophosaurusChinleFlatsSpawnWeight = buildInt(builder, "Trilophosaurus Chinle Flats Spawn Weight", "all", 0, 0, 300, "The weight of Trilophosaurus in vanilla's spawn rate in the Chinle Flats biome. Default is 0");
		this.typothoraxChinleFlatsSpawnWeight = buildInt(builder, "Typothorax Chinle Flats Spawn Weight", "all", 8, 0, 300, "The weight of Typothorax in vanilla's spawn rate in the Chinle Flats biome. Default is 8");
		this.caveSentinelChinleFlatsSpawnWeight = buildInt(builder, "Cave Sentinel Chinle Flats Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Chinle Flats biome. Default is 5");
		this.landSentinelChinleFlatsSpawnWeight = buildInt(builder, "Land Sentinel Chinle Flats Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Chinle Flats biome. Default is 2");
		builder.pop();
		builder.push("Chinle River");
		this.arganodusChinleRiverSpawnWeight = buildInt(builder, "Arganodus Chinle River Spawn Weight", "all", 3, 0, 300, "The weight of Arganodus in vanilla's spawn rate in the Chinle River biome. Default is 4");
		this.chinleaChinleRiverSpawnWeight = buildInt(builder, "Chinlea Chinle River Spawn Weight", "all", 4, 0, 300, "The weight of Chinlea in vanilla's spawn rate in the Chinle River biome. Default is 4");
		this.mooreodontusChinleRiverSpawnWeight = buildInt(builder, "Mooreodontus Chinle River Spawn Weight", "all", 1, 0, 300, "The weight of Mooreodontus in vanilla's spawn rate in the Chinle River biome. Default is 1");
		this.saurichthysChinleRiverSpawnWeight = buildInt(builder, "Saurichthys Chinle River Spawn Weight", "all", 2, 0, 300, "The weight of Saurichthys in vanilla's spawn rate in the Chinle River biome. Default is 2");
		this.caveSentinelChinleRiverSpawnWeight = buildInt(builder, "Cave Sentinel Chinle River Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Chinle River biome. Default is 5");
		this.landSentinelChinleRiverSpawnWeight = buildInt(builder, "Land Sentinel Chinle River Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Chinle River biome. Default is 2");
		builder.pop();
		builder.push("Chinle Swamp");
		this.arganodusChinleSwampSpawnWeight = buildInt(builder, "Arganodus Chinle Swamp Spawn Weight", "all", 4, 0, 300, "The weight of Arganodus in vanilla's spawn rate in the Chinle Swamp biome. Default is 4");
		this.chinleaChinleSwampSpawnWeight = buildInt(builder, "Chinlea Chinle Swamp Spawn Weight", "all", 1, 0, 300, "The weight of Chinlea in vanilla's spawn rate in the Chinle Swamp biome. Default is 1");
		this.coelophysisChinleSwampSpawnWeight = buildInt(builder, "Coelophysis Chinle Swamp Spawn Weight", "all", 12, 0, 300, "The weight of Coelophysis in vanilla's spawn rate in the Chinle Swamp biome. Default is 12");
		this.desmatosuchusChinleSwampSpawnWeight = buildInt(builder, "Desmatosuchus Chinle Swamp Spawn Weight", "all", 9, 0, 300, "The weight of Desmatosuchus in vanilla's spawn rate in the Chinle Swamp biome. Default is 9");
		this.mooreodontusChinleSwampSpawnWeight = buildInt(builder, "Mooreodontus Chinle Swamp Spawn Weight", "all", 3, 0, 300, "The weight of Mooreodontus in vanilla's spawn rate in the Chinle Swamp biome. Default is 3");
		this.placeriasChinleSwampSpawnWeight = buildInt(builder, "Placerias Chinle Swamp Spawn Weight", "all", 6, 0, 300, "The weight of Placerias in vanilla's spawn rate in the Chinle Swamp biome. Default is 6");
		this.poposaurusChinleSwampSpawnWeight = buildInt(builder, "Poposaurus Chinle Swamp Spawn Weight", "all", 3, 0, 300, "The weight of Poposaurus in vanilla's spawn rate in the Chinle Swamp biome. Default is 3");
		this.postosuchusChinleSwampSpawnWeight = buildInt(builder, "Postosuchus Chinle Swamp Spawn Weight", "all", 5, 0, 300, "The weight of Postosuchus in vanilla's spawn rate in the Chinle Swamp biome. Default is 5");
		this.saurichthysChinleSwampSpawnWeight = buildInt(builder, "Saurichthys Chinle Swamp Spawn Weight", "all", 2, 0, 300, "The weight of Saurichthys in vanilla's spawn rate in the Chinle Swamp biome. Default is 2");
		this.trilophosaurusChinleSwampSpawnWeight = buildInt(builder, "Trilophosaurus Chinle Swamp Spawn Weight", "all", 10, 0, 300, "The weight of Trilophosaurus in vanilla's spawn rate in the Chinle Swamp biome. Default is 10");
		this.typothoraxChinleSwampSpawnWeight = buildInt(builder, "Typothorax Chinle Swamp Spawn Weight", "all", 7, 0, 300, "The weight of Typothorax in vanilla's spawn rate in the Chinle Swamp biome. Default is 7");
		this.caveSentinelChinleSwampSpawnWeight = buildInt(builder, "Cave Sentinel Chinle Swamp Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Chinle Swamp biome. Default is 5");
		this.landSentinelChinleSwampSpawnWeight = buildInt(builder, "Land Sentinel Chinle Swamp Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Chinle Swamp biome. Default is 2");
		builder.pop();
		builder.push("Chinle Wooded Mountains");
		this.arganodusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Arganodus Chinle Wooded Mountains Spawn Weight", "all", 0, 0, 300, "The weight of Arganodus in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 0");
		this.chinleaChinleWoodedMountainsSpawnWeight = buildInt(builder, "Chinlea Chinle Wooded Mountains Spawn Weight", "all", 0, 0, 300, "The weight of Chinlea in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 0");
		this.coelophysisChinleWoodedMountainsSpawnWeight = buildInt(builder, "Coelophysis Chinle Wooded Mountains Spawn Weight", "all", 0, 0, 300, "The weight of Coelophysis in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 0");
		this.desmatosuchusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Desmatosuchus Chinle Wooded Mountains Spawn Weight", "all", 7, 0, 300, "The weight of Desmatosuchus in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 7");
		this.mooreodontusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Mooreodontus Chinle Wooded Mountains Spawn Weight", "all", 0, 0, 300, "The weight of Mooreodontus in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 0");
		this.placeriasChinleWoodedMountainsSpawnWeight = buildInt(builder, "Placerias Chinle Wooded Mountains Spawn Weight", "all", 11, 0, 300, "The weight of Placerias in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 11");
		this.poposaurusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Poposaurus Chinle Wooded Mountains Spawn Weight", "all", 8, 0, 300, "The weight of Poposaurus in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 8");
		this.postosuchusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Postosuchus Chinle Wooded Mountains Spawn Weight", "all", 3, 0, 300, "The weight of Postosuchus in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 3");
		this.saurichthysChinleWoodedMountainsSpawnWeight = buildInt(builder, "Saurichthys Chinle Wooded Mountains Spawn Weight", "all", 0, 0, 300, "The weight of Saurichthys in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 0");
		this.trilophosaurusChinleWoodedMountainsSpawnWeight = buildInt(builder, "Trilophosaurus Chinle Wooded Mountains Spawn Weight", "all", 10, 0, 300, "The weight of Trilophosaurus in vanilla's spawn rate in the Chinle Wooded Mountains. Default is 10");
		this.typothoraxChinleWoodedMountainsSpawnWeight = buildInt(builder, "Typothorax Chinle Wooded Mountains Spawn Weight", "all", 5, 0, 300, "The weight of Typothorax in the vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 5");
		this.caveSentinelChinleWoodedMountainsSpawnWeight = buildInt(builder, "Cave Sentinel Chinle Wooded Mountains Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 5");
		this.landSentinelChinleWoodedMountainsSpawnWeight = buildInt(builder, "Land Sentinel Chinle Wooded Mountains Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Chinle Wooded Mountains biome. Default is 2");
		builder.pop(2);
		builder.push("Ischigualasto Formation");
		builder.push("Ischigualasto Forest");
		this.ceratodusIschigualastoForestSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto Forest Spawn Weight", "all", 3, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 3");
		this.chromogisaurusIschigualastoForestSpawnWeight = buildInt(builder, "Chromogisaurus Ischigualasto Forest Spawn Weight", "all", 10, 0, 300, "The weight of Chromogisaurus in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 10");
		this.exaeretodonIschigualastoForestSpawnWeight = buildInt(builder, "Exaeretodon Ischigualasto Forest Spawn Weight", "all", 12, 0, 300, "The weight of Exaeretodon in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 12");
		this.herrerasaurusIschigualastoForestSpawnWeight = buildInt(builder, "Herrerasaurus Ischigualasto Forest Spawn Weight", "all", 8, 0, 300, "The weight of Herrerasaurus in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 8");
		this.hyperodapedonIschigualastoForestSpawnWeight = buildInt(builder, "Hyperodapedon Ischigualasto Forest Spawn Weight", "all", 15, 0, 300, "The weight of Hyperodapedon in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 15");
		this.ischigualastiaIschigualastoForestSpawnWeight = buildInt(builder, "Ischigualastia Ischigualasto Forest Spawn Weight", "all", 8, 0, 300, "The weight of Ischigualastia in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 8");
		this.saurosuchusIschigualastoForestSpawnWeight = buildInt(builder, "Saurosuchus Ischigualasto Forest Spawn Weight", "all", 4, 0, 300, "The weight of Saurosuchus in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 4");
		this.sillosuchusIschigualastoForestSpawnWeight = buildInt(builder, "Sillosuchus Ischigualasto Forest Spawn Weight", "all", 6, 0, 300, "The weight of Sillosuchus in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 6");
		this.caveSentinelIschigualastoForestSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto Forest Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 5");
		this.landSentinelIschigualastoForestSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto Forest Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Ischigualasto Forest biome. Default is 2");
		builder.pop();
		builder.push("Ischigualasto Clearing");
		this.ceratodusIschigualastoClearingSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto Clearing Spawn Weight", "all", 3, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 3");
		this.chromogisaurusIschigualastoClearingSpawnWeight = buildInt(builder, "Chromogisaurus Ischigualasto Clearing Spawn Weight", "all", 10, 0, 300, "The weight of Chromogisaurus in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 10");
		this.exaeretodonIschigualastoClearingSpawnWeight = buildInt(builder, "Exaeretodon Ischigualasto Clearing Spawn Weight", "all", 12, 0, 300, "The weight of Exaeretodon in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 12");
		this.herrerasaurusIschigualastoClearingSpawnWeight = buildInt(builder, "Herrerasaurus Ischigualasto Clearing Spawn Weight", "all", 8, 0, 300, "The weight of Herrerasaurus in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 8");
		this.hyperodapedonIschigualastoClearingSpawnWeight = buildInt(builder, "Hyperodapedon Ischigualasto Clearing Spawn Weight", "all", 15, 0, 300, "The weight of Hyperodapedon in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 15");
		this.ischigualastiaIschigualastoClearingSpawnWeight = buildInt(builder, "Ischigualastia Ischigualasto Clearing Spawn Weight", "all", 8, 0, 300, "The weight of Ischigualastia in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 8");
		this.saurosuchusIschigualastoClearingSpawnWeight = buildInt(builder, "Saurosuchus Ischigualasto Clearing Spawn Weight", "all", 4, 0, 300, "The weight of Saurosuchus in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 4");
		this.sillosuchusIschigualastoClearingSpawnWeight = buildInt(builder, "Sillosuchus Ischigualasto Clearing Spawn Weight", "all", 6, 0, 300, "The weight of Sillosuchus in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 6");
		this.caveSentinelIschigualastoClearingSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto Clearing Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 5");
		this.landSentinelIschigualastoClearingSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto Clearing Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Ischigualasto Clearing biome. Default is 2");
		builder.pop();
		builder.push("Ischigualasto Hills");
		this.ceratodusIschigualastoHillsSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto Hills Spawn Weight", "all", 3, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 3");
		this.chromogisaurusIschigualastoHillsSpawnWeight = buildInt(builder, "Chromogisaurus Ischigualasto Hills Spawn Weight", "all", 10, 0, 300, "The weight of Chromogisaurus in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 10");
		this.exaeretodonIschigualastoHillsSpawnWeight = buildInt(builder, "Exaeretodon Ischigualasto Hills Spawn Weight", "all", 12, 0, 300, "The weight of Exaeretodon in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 12");
		this.herrerasaurusIschigualastoHillsSpawnWeight = buildInt(builder, "Herrerasaurus Ischigualasto Hills Spawn Weight", "all", 8, 0, 300, "The weight of Herrerasaurus in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 8");
		this.hyperodapedonIschigualastoHillsSpawnWeight = buildInt(builder, "Hyperodapedon Ischigualasto Hills Spawn Weight", "all", 15, 0, 300, "The weight of Hyperodapedon in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 15");
		this.ischigualastiaIschigualastoHillsSpawnWeight = buildInt(builder, "Ischigualastia Ischigualasto Hills Spawn Weight", "all", 8, 0, 300, "The weight of Ischigualastia in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 8");
		this.sillosuchusIschigualastoHillsSpawnWeight = buildInt(builder, "Sillosuchus Ischigualasto Hills Spawn Weight", "all", 6, 0, 300, "The weight of Sillosuchus in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 6");
		this.saurosuchusIschigualastoHillsSpawnWeight = buildInt(builder, "Saurosuchus Ischigualasto Hills Spawn Weight", "all", 4, 0, 300, "The weight of Saurosuchus in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 4");
		this.caveSentinelIschigualastoHillsSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto Hills Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 5");
		this.landSentinelIschigualastoHillsSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto Hills Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Ischigualasto Hills biome. Default is 2");
		builder.pop();
		builder.push("Ischigualasto River");
		this.ceratodusIschigualastoRiverSpawnWeight = buildInt(builder, "Ceratodus Ischigualasto River Spawn Weight", "all", 3, 0, 300, "The weight of Ceratodus in vanilla's spawn rate in the Ischigualasto River biome. Default is 3");
		this.caveSentinelIschigualastoRiverSpawnWeight = buildInt(builder, "Cave Sentinel Ischigualasto River Spawn Weight", "all", 5, 0, 300, "The weight of Cave Sentinels in vanilla's spawn rate in the Ischigualasto River biome. Default is 5");
		this.landSentinelIschigualastoRiverSpawnWeight = buildInt(builder, "Land Sentinel Ischigualasto River Spawn Weight", "all", 2, 0, 300, "The weight of Land Sentinels in vanilla's spawn rate in the Ischigualasto River biome. Default is 2");
		builder.pop(2);
		builder.push("Misc Settings");
		this.superSecretSetting = buildBoolean(builder, "Super Secret Setting", "all", false, "Even I don't know what it does. Default is false");
		this.cretaceousDimensionID = buildInt(builder, "Cretaceous Dimension ID", "all", 9, Integer.MIN_VALUE, Integer.MAX_VALUE, "Cretaceous Dimension ID. Default is 9");
		this.jurassicDimensionID = buildInt(builder, "Jurassic Dimension ID", "all", 8, Integer.MIN_VALUE, Integer.MAX_VALUE, "Jurassic Dimension ID. Default is 8");
		this.triassicDimensionID = buildInt(builder, "Triassic Dimension ID", "all", 7, Integer.MIN_VALUE, Integer.MAX_VALUE, "Triassic Dimension ID. Default is 7");
		this.spaceTimeContinuumWarping = buildBoolean(builder, "Space Time Continuum Warping", "all", false, "Warning: Messing with the time space continuum may lead to unforseen consequences. Recommended to keep false for servers. Default is false");
		this.geologyHammerMining = buildBoolean(builder, "Geological Hammer Stone Breaking", "all", true, "Toggles whether stones can be broken down using the Geological Hammer. Default is true");
		builder.pop();
		builder.push("Structures");
		this.hellCreekHutMinDistance = buildInt(builder, "Hell Creek Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Hell Creek Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.hellCreekHutMaxDistance = buildInt(builder, "Hell Creek Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Hell Creek Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.morrisonHutMinDistance = buildInt(builder, "Morrison Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Morrison Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.morrisonHutMaxDistance = buildInt(builder, "Morrison Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Morrison Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.ischigualastoHutMinDistance = buildInt(builder, "Ischigualasto Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Ischigualasto Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.ischigualastoHutMaxDistance = buildInt(builder, "Ischigualasto Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Ischigualasto Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.djadochtaHutMinDistance = buildInt(builder, "Djadochta Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Djadochta Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.djadochtaHutMaxDistance = buildInt(builder, "Djadochta Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Djadochta Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.kayentaHutMinDistance = buildInt(builder, "Kayenta Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Kayenta Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.kayentaHutMaxDistance = buildInt(builder, "Kayenta Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Kayenta Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.chinleHutMinDistance = buildInt(builder, "Chinle Ruined Time Traveller's Hut Min Distance", "all", 40, 1, 300, "The closest two Chinle Ruined Time Traveller's Huts can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.chinleHutMaxDistance = buildInt(builder, "Chinle Ruined Time Traveller's Hut Max Distance", "all", 60, 1, 300, "The farthest two Chinle Ruined Time Traveller's Huts can spawn from eachother. Keep this value higher than the min. Default is 60");
		this.geologistCampMinDistance = buildInt(builder, "Geologist Camp Min Distance", "all", 25, 1, 300, "The closest two Geologist Camps can spawn from eachother. Keep this value lower than the max. Default is 25");
		this.geologistCampMaxDistance = buildInt(builder, "Geologist Camp Max Distance", "all", 50, 1, 300, "The farthest two Geologist Camps can spawn from eachother. Keep this value higher than the min. Default is 50");
		this.timeTempleMinDistance = buildInt(builder, "Time Temple Min Distance", "all", 75, 1, 300, "The closest two Time Temples can spawn from eachother. Keep this value lower than the max. Default is 75");
		this.timeTempleMaxDistance = buildInt(builder, "Time Temple Max Distance", "all", 100, 1, 300, "The farthest two Time Temples can spawn from eachother. Keep this value higher than the min. Default is 100");
		this.portalHubMinDistance = buildInt(builder, "Portal Hub Min Distance", "all", 40, 1, 300, "The closest two Portal Hubs can spawn from eachother. Keep this value lower than the max. Default is 40");
		this.portalHubMaxDistance = buildInt(builder, "Portal Hub Hut Max Distance", "all", 60, 1, 300, "The farthest two Portal Hubs can spawn from eachother. Keep this value higher than the min. Default is 60");
		builder.pop();
		builder.push("World Generation");
		this.baseStoneWeight = buildInt(builder, "Base Stone Weight", "all", 97, 1, 300, "The probability of an ancient stone deposit is made up of the base stone. To find the percentage probability, add the base stone weight with the fossil weight, and then divide the base stone weight by the combined weights. Default is 97");
		this.fossilWeight = buildInt(builder, "Fossil Weight", "all", 3, 1, 300, "The probability of an ancient stone deposit is made up of the fossilized stone. To find the percentage probability, add the base stone weight with the fossil weight, and then divide the fossil stone weight by the combined weights. Default is 3");
		this.petrifiedForestWeight = buildInt(builder, "Petrified Forest Weight", "all", 6, 0, 300, "The probability for the Petrified Forest biome to generate in the overworld. Default is 6");
		builder.pop();
		builder.push("AI Config");
		this.sleeping = buildBoolean(builder, "Sleeping AI", "all", true, "Toggles whether all prehistoric animals sleep or not. Default is true");
		this.advancedHunger = buildBoolean(builder, "Advanced Hunger AI", "all", true, "Toggles whether all prehistoric animals are affected by hunger. Default is true");
		this.hungerDamage = buildBoolean(builder, "Hunger Damage", "all", false, "Toggles whether entities take damage from being hungry. Default is false");
		this.naturalEggBlockLaying = buildBoolean(builder, "Natural Egg Laying AI - Blocks", "all", true, "Toggles whether entities lay their eggs as blocks naturally when full. Default is true");
		this.naturalEggItemLaying = buildBoolean(builder, "Natural Egg Laying AI - Items", "all", false, "Toggles whether entities lay their eggs as items naturally when full. Default is false");
		builder.pop();
	}
	
	private static ForgeConfigSpec.BooleanValue buildBoolean(ForgeConfigSpec.Builder builder, String name, String catagory, boolean defaultValue, String comment){
		return builder.comment(comment).translation(name).define(name, defaultValue);
	}

	private static ForgeConfigSpec.IntValue buildInt(ForgeConfigSpec.Builder builder, String name, String catagory, int defaultValue, int min, int max, String comment){
		return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
	}

	@SuppressWarnings("unused")
	private static ForgeConfigSpec.DoubleValue buildDouble(ForgeConfigSpec.Builder builder, String name, String catagory, double defaultValue, double min, double max, String comment){
		return builder.comment(comment).translation(name).defineInRange(name, defaultValue, min, max);
	}
	
}
