package superlord.prehistoricfauna.world.feature.cretaceous;

import java.util.Random;
import java.util.function.Function;

import com.mojang.datafixers.Dynamic;

import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.LeavesBlock;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.minecraft.world.gen.ChunkGenerator;
import net.minecraft.world.gen.GenerationSettings;
import net.minecraft.world.gen.Heightmap;
import net.minecraft.world.gen.feature.Feature;
import superlord.prehistoricfauna.init.BlockInit;
import superlord.prehistoricfauna.world.placement.AraucariaSmallConfig;

public class AraucariaSmallTreeGenerator extends Feature<AraucariaSmallConfig> {
	public AraucariaSmallTreeGenerator(Function<Dynamic<?>, ? extends AraucariaSmallConfig> p_i225808_1_) {
		super(p_i225808_1_);
	}

	@Override
	public boolean place(IWorld world, ChunkGenerator<? extends GenerationSettings> generator, Random rand, BlockPos pos, AraucariaSmallConfig config) {
		int i = 0;
		for(int j = 0; j < config.count; ++j) {
			int k = rand.nextInt(8) - rand.nextInt(8);
			int l = rand.nextInt(8) - rand.nextInt(8);
			int i1 = world.getHeight(Heightmap.Type.WORLD_SURFACE, pos.getX() + k, pos.getZ() + l);
			int j1 = rand.nextInt(4);
			BlockPos blockpos = new BlockPos(pos.getX() + k, i1, pos.getZ() + l);
			if (world.getBlockState(blockpos).getBlock() == Blocks.AIR && world.getBlockState(blockpos.down()).getBlock() == Blocks.COARSE_DIRT || world.getBlockState(blockpos).getBlock() == Blocks.AIR && world.getBlockState(blockpos.down()).getBlock() == Blocks.PODZOL || world.getBlockState(blockpos).getBlock() == Blocks.AIR && world.getBlockState(blockpos.down()).getBlock() == BlockInit.MOSSY_DIRT) {	
				BlockState log = BlockInit.ARAUCARIA_LOG.getDefaultState();
				BlockState leaves = BlockInit.ARAUCARIA_LEAVES.getDefaultState().with(LeavesBlock.PERSISTENT, false);
				int k1 = rand.nextInt(3);
				if (j1 == 0) {
					for (BlockPos basePos : BlockPos.Mutable.getAllInBoxMutable(pos.add(0, 0, 0), pos.add(0, 7 + k1, 0))) {
						world.setBlockState(basePos, log, 2);
					}
					world.setBlockState(pos.up(k1).north(), leaves, 2);
					world.setBlockState(pos.up(k1).east(), leaves, 2);
					world.setBlockState(pos.up(k1).south(), leaves, 2);
					world.setBlockState(pos.up(k1).west(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(3 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(3 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(3 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(3 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(7+ k1), leaves, 2);
					world.setBlockState(pos.up(7+ k1).north(), leaves, 2);
					world.setBlockState(pos.up(7+ k1).east(), leaves, 2);
					world.setBlockState(pos.up(7+ k1).south(), leaves, 2);
					world.setBlockState(pos.up(7+ k1).west(), leaves, 2);
					world.setBlockState(pos.up(8+ k1), leaves, 2);
				} else if (j1 == 1) {
					for (BlockPos basePos : BlockPos.Mutable.getAllInBoxMutable(pos.add(0, 0, 0), pos.add(0, 10 + k1, 0))) {
						world.setBlockState(basePos, log, 2);
					}
					world.setBlockState(pos.up(2 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(3 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).east(2).north(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).east(2).south(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).west(2).north(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).west(2).south(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(5 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(5 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(5 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(5 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).east(2).north(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).east(2).south(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).west(2).north(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).west(2).south(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).east(2).north(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).east(2).south(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).west(2).north(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).west(2).south(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1), leaves, 2);
					world.setBlockState(pos.up(12 + k1), leaves, 2);
				} else if(j1 == 2) {
					for (BlockPos basePos : BlockPos.Mutable.getAllInBoxMutable(pos.add(0, 0, 0), pos.add(0, 12 + k1, 0))) {
						world.setBlockState(basePos, log, 2);
					}
					world.setBlockState(pos.up(2 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(2 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(4 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(5 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(6 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).east(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).west(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north().west(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north().east(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south().west(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south().east(3), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(2).west(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(2).east(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(2).west(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(2).east(2), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(3).west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).north(3).east(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(3).west(), leaves, 2);
					world.setBlockState(pos.up(7 + k1).south(3).east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(8 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).east(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).west(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north().west(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north().east(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south().west(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south().east(3), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(2).west(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(2).east(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(2).west(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(2).east(2), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(3).west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).north(3).east(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(3).west(), leaves, 2);
					world.setBlockState(pos.up(9 + k1).south(3).east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(10 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(10 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(10 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north().west(2), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north().east(2), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south().west(2), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south().east(2), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(11 + k1).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(12 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(12 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(12 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(12 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(12 + k1).north(2), leaves, 2);
					world.setBlockState(pos.up(12 + k1).east(2), leaves, 2);
					world.setBlockState(pos.up(12 + k1).south(2), leaves, 2);
					world.setBlockState(pos.up(12 + k1).west(2), leaves, 2);
					world.setBlockState(pos.up(13 + k1), leaves, 2);
					world.setBlockState(pos.up(13 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).north().east(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).north().west(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).south().east(), leaves, 2);
					world.setBlockState(pos.up(13 + k1).south().west(), leaves, 2);
					world.setBlockState(pos.up(14 + k1), leaves, 2);
					world.setBlockState(pos.up(14 + k1).north(), leaves, 2);
					world.setBlockState(pos.up(14 + k1).east(), leaves, 2);
					world.setBlockState(pos.up(14 + k1).south(), leaves, 2);
					world.setBlockState(pos.up(14 + k1).west(), leaves, 2);
					world.setBlockState(pos.up(15 + k1), leaves, 2);
				} else {
					for (BlockPos basePos : BlockPos.Mutable.getAllInBoxMutable(pos.add(0, 0, 0), pos.add(0, 14 + k1, 0))) {
						world.setBlockState(basePos, log, 2);
					}
					world.setBlockState(pos.up(2).north(), leaves, 2);
					world.setBlockState(pos.up(2).east(), leaves, 2);
					world.setBlockState(pos.up(2).south(), leaves, 2);
					world.setBlockState(pos.up(2).west(), leaves, 2);
					world.setBlockState(pos.up(4).north(), leaves, 2);
					world.setBlockState(pos.up(4).east(), leaves, 2);
					world.setBlockState(pos.up(4).south(), leaves, 2);
					world.setBlockState(pos.up(4).west(), leaves, 2);
					world.setBlockState(pos.up(6).north(), leaves, 2);
					world.setBlockState(pos.up(6).east(), leaves, 2);
					world.setBlockState(pos.up(6).south(), leaves, 2);
					world.setBlockState(pos.up(6).west(), leaves, 2);
					world.setBlockState(pos.up(6).north().west(), leaves, 2);
					world.setBlockState(pos.up(6).north().east(), leaves, 2);
					world.setBlockState(pos.up(6).south().east(), leaves, 2);
					world.setBlockState(pos.up(6).south().west(), leaves, 2);
					world.setBlockState(pos.up(7).north(), leaves, 2);
					world.setBlockState(pos.up(7).east(), leaves, 2);
					world.setBlockState(pos.up(7).south(), leaves, 2);
					world.setBlockState(pos.up(7).west(), leaves, 2);
					world.setBlockState(pos.up(7).north().west(), leaves, 2);
					world.setBlockState(pos.up(7).north().east(), leaves, 2);
					world.setBlockState(pos.up(7).south().east(), leaves, 2);
					world.setBlockState(pos.up(7).south().west(), leaves, 2);
					world.setBlockState(pos.up(7).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(7).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(7).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(7).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(7).north().west(2), leaves, 2);
					world.setBlockState(pos.up(7).north().east(2), leaves, 2);
					world.setBlockState(pos.up(7).south().east(2), leaves, 2);
					world.setBlockState(pos.up(7).south().west(2), leaves, 2);
					world.setBlockState(pos.up(8).north(), leaves, 2);
					world.setBlockState(pos.up(8).east(), leaves, 2);
					world.setBlockState(pos.up(8).south(), leaves, 2);
					world.setBlockState(pos.up(8).west(), leaves, 2);
					world.setBlockState(pos.up(8).north(2), leaves, 2);
					world.setBlockState(pos.up(8).east(2), leaves, 2);
					world.setBlockState(pos.up(8).south(2), leaves, 2);
					world.setBlockState(pos.up(8).west(2), leaves, 2);
					world.setBlockState(pos.up(8).north().west(), leaves, 2);
					world.setBlockState(pos.up(8).north().east(), leaves, 2);
					world.setBlockState(pos.up(8).south().east(), leaves, 2);
					world.setBlockState(pos.up(8).south().west(), leaves, 2);
					world.setBlockState(pos.up(8).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(8).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(8).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(8).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(8).north().west(2), leaves, 2);
					world.setBlockState(pos.up(8).north().east(2), leaves, 2);
					world.setBlockState(pos.up(8).south().east(2), leaves, 2);
					world.setBlockState(pos.up(8).south().west(2), leaves, 2);
					world.setBlockState(pos.up(8).north(2).west(2), leaves, 2);
					world.setBlockState(pos.up(8).north(2).east(2), leaves, 2);
					world.setBlockState(pos.up(8).south(2).east(2), leaves, 2);
					world.setBlockState(pos.up(8).south(2).west(2), leaves, 2);
					world.setBlockState(pos.up(9).north(), leaves, 2);
					world.setBlockState(pos.up(9).east(), leaves, 2);
					world.setBlockState(pos.up(9).south(), leaves, 2);
					world.setBlockState(pos.up(9).west(), leaves, 2);
					world.setBlockState(pos.up(9).north(2), leaves, 2);
					world.setBlockState(pos.up(9).east(2), leaves, 2);
					world.setBlockState(pos.up(9).south(2), leaves, 2);
					world.setBlockState(pos.up(9).west(2), leaves, 2);
					world.setBlockState(pos.up(9).north(3), leaves, 2);
					world.setBlockState(pos.up(9).east(3), leaves, 2);
					world.setBlockState(pos.up(9).south(3), leaves, 2);
					world.setBlockState(pos.up(9).west(3), leaves, 2);
					world.setBlockState(pos.up(9).north().west(), leaves, 2);
					world.setBlockState(pos.up(9).north().east(), leaves, 2);
					world.setBlockState(pos.up(9).south().east(), leaves, 2);
					world.setBlockState(pos.up(9).south().west(), leaves, 2);
					world.setBlockState(pos.up(9).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(9).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(9).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(9).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(9).north().west(2), leaves, 2);
					world.setBlockState(pos.up(9).north().east(2), leaves, 2);
					world.setBlockState(pos.up(9).south().east(2), leaves, 2);
					world.setBlockState(pos.up(9).south().west(2), leaves, 2);
					world.setBlockState(pos.up(9).north(2).west(2), leaves, 2);
					world.setBlockState(pos.up(9).north(2).east(2), leaves, 2);
					world.setBlockState(pos.up(9).south(2).east(2), leaves, 2);
					world.setBlockState(pos.up(9).south(2).west(2), leaves, 2);
					world.setBlockState(pos.up(9).north(3).west(), leaves, 2);
					world.setBlockState(pos.up(9).north(3).east(), leaves, 2);
					world.setBlockState(pos.up(9).south(3).east(), leaves, 2);
					world.setBlockState(pos.up(9).south(3).west(), leaves, 2);
					world.setBlockState(pos.up(9).north().west(3), leaves, 2);
					world.setBlockState(pos.up(9).north().east(3), leaves, 2);
					world.setBlockState(pos.up(9).south().east(3), leaves, 2);
					world.setBlockState(pos.up(9).south().west(3), leaves, 2);
					world.setBlockState(pos.up(10).north(), leaves, 2);
					world.setBlockState(pos.up(10).east(), leaves, 2);
					world.setBlockState(pos.up(10).south(), leaves, 2);
					world.setBlockState(pos.up(10).west(), leaves, 2);
					world.setBlockState(pos.up(10).north(2), leaves, 2);
					world.setBlockState(pos.up(10).east(2), leaves, 2);
					world.setBlockState(pos.up(10).south(2), leaves, 2);
					world.setBlockState(pos.up(10).west(2), leaves, 2);
					world.setBlockState(pos.up(10).north().west(), leaves, 2);
					world.setBlockState(pos.up(10).north().east(), leaves, 2);
					world.setBlockState(pos.up(10).south().east(), leaves, 2);
					world.setBlockState(pos.up(10).south().west(), leaves, 2);
					world.setBlockState(pos.up(10).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(10).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(10).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(10).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(10).north().west(2), leaves, 2);
					world.setBlockState(pos.up(10).north().east(2), leaves, 2);
					world.setBlockState(pos.up(10).south().east(2), leaves, 2);
					world.setBlockState(pos.up(10).south().west(2), leaves, 2);
					world.setBlockState(pos.up(11).north(), leaves, 2);
					world.setBlockState(pos.up(11).east(), leaves, 2);
					world.setBlockState(pos.up(11).south(), leaves, 2);
					world.setBlockState(pos.up(11).west(), leaves, 2);
					world.setBlockState(pos.up(11).north(2), leaves, 2);
					world.setBlockState(pos.up(11).east(2), leaves, 2);
					world.setBlockState(pos.up(11).south(2), leaves, 2);
					world.setBlockState(pos.up(11).west(2), leaves, 2);
					world.setBlockState(pos.up(11).north(3), leaves, 2);
					world.setBlockState(pos.up(11).east(3), leaves, 2);
					world.setBlockState(pos.up(11).south(3), leaves, 2);
					world.setBlockState(pos.up(11).west(3), leaves, 2);
					world.setBlockState(pos.up(11).north().west(), leaves, 2);
					world.setBlockState(pos.up(11).north().east(), leaves, 2);
					world.setBlockState(pos.up(11).south().east(), leaves, 2);
					world.setBlockState(pos.up(11).south().west(), leaves, 2);
					world.setBlockState(pos.up(11).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(11).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(11).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(11).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(11).north().west(2), leaves, 2);
					world.setBlockState(pos.up(11).north().east(2), leaves, 2);
					world.setBlockState(pos.up(11).south().east(2), leaves, 2);
					world.setBlockState(pos.up(11).south().west(2), leaves, 2);
					world.setBlockState(pos.up(11).north(2).west(2), leaves, 2);
					world.setBlockState(pos.up(11).north(2).east(2), leaves, 2);
					world.setBlockState(pos.up(11).south(2).east(2), leaves, 2);
					world.setBlockState(pos.up(11).south(2).west(2), leaves, 2);
					world.setBlockState(pos.up(11).north(3).west(), leaves, 2);
					world.setBlockState(pos.up(11).north(3).east(), leaves, 2);
					world.setBlockState(pos.up(11).south(3).east(), leaves, 2);
					world.setBlockState(pos.up(11).south(3).west(), leaves, 2);
					world.setBlockState(pos.up(11).north().west(3), leaves, 2);
					world.setBlockState(pos.up(11).north().east(3), leaves, 2);
					world.setBlockState(pos.up(11).south().east(3), leaves, 2);
					world.setBlockState(pos.up(11).south().west(3), leaves, 2);
					world.setBlockState(pos.up(12).north(), leaves, 2);
					world.setBlockState(pos.up(12).east(), leaves, 2);
					world.setBlockState(pos.up(12).south(), leaves, 2);
					world.setBlockState(pos.up(12).west(), leaves, 2);
					world.setBlockState(pos.up(12).north(2), leaves, 2);
					world.setBlockState(pos.up(12).east(2), leaves, 2);
					world.setBlockState(pos.up(12).south(2), leaves, 2);
					world.setBlockState(pos.up(12).west(2), leaves, 2);
					world.setBlockState(pos.up(12).north().west(), leaves, 2);
					world.setBlockState(pos.up(12).north().east(), leaves, 2);
					world.setBlockState(pos.up(12).south().east(), leaves, 2);
					world.setBlockState(pos.up(12).south().west(), leaves, 2);
					world.setBlockState(pos.up(13).north(), leaves, 2);
					world.setBlockState(pos.up(13).east(), leaves, 2);
					world.setBlockState(pos.up(13).south(), leaves, 2);
					world.setBlockState(pos.up(13).west(), leaves, 2);
					world.setBlockState(pos.up(13).north().west(), leaves, 2);
					world.setBlockState(pos.up(13).north().east(), leaves, 2);
					world.setBlockState(pos.up(13).south().east(), leaves, 2);
					world.setBlockState(pos.up(13).south().west(), leaves, 2);
					world.setBlockState(pos.up(13).north(2).west(), leaves, 2);
					world.setBlockState(pos.up(13).north(2).east(), leaves, 2);
					world.setBlockState(pos.up(13).south(2).east(), leaves, 2);
					world.setBlockState(pos.up(13).south(2).west(), leaves, 2);
					world.setBlockState(pos.up(13).north().west(2), leaves, 2);
					world.setBlockState(pos.up(13).north().east(2), leaves, 2);
					world.setBlockState(pos.up(13).south().east(2), leaves, 2);
					world.setBlockState(pos.up(13).south().west(2), leaves, 2);
					world.setBlockState(pos.up(12).north(), leaves, 2);
					world.setBlockState(pos.up(12).east(), leaves, 2);
					world.setBlockState(pos.up(12).south(), leaves, 2);
					world.setBlockState(pos.up(12).west(), leaves, 2);
					world.setBlockState(pos.up(12).north(2), leaves, 2);
					world.setBlockState(pos.up(12).east(2), leaves, 2);
					world.setBlockState(pos.up(12).south(2), leaves, 2);
					world.setBlockState(pos.up(12).west(2), leaves, 2);
					world.setBlockState(pos.up(14).north(), leaves, 2);
					world.setBlockState(pos.up(14).east(), leaves, 2);
					world.setBlockState(pos.up(14).south(), leaves, 2);
					world.setBlockState(pos.up(14).west(), leaves, 2);
					world.setBlockState(pos.up(14).north().west(), leaves, 2);
					world.setBlockState(pos.up(14).north().east(), leaves, 2);
					world.setBlockState(pos.up(14).south().east(), leaves, 2);
					world.setBlockState(pos.up(14).south().west(), leaves, 2);
					world.setBlockState(pos.up(14), leaves, 2);
					world.setBlockState(pos.up(15).north(), leaves, 2);
					world.setBlockState(pos.up(15).east(), leaves, 2);
					world.setBlockState(pos.up(15).south(), leaves, 2);
					world.setBlockState(pos.up(15).west(), leaves, 2);
					world.setBlockState(pos.up(15), leaves, 2);
					world.setBlockState(pos.up(16), leaves, 2);
				}
			}
			++i;
		}
		return i>0;
	}

}
