package superlord.prehistoricfauna.world.feature.cretaceous;

import com.mojang.datafixers.Dynamic;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.LeavesBlock;
import net.minecraft.block.LogBlock;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.minecraft.world.gen.ChunkGenerator;
import net.minecraft.world.gen.GenerationSettings;
import net.minecraft.world.gen.Heightmap;
import net.minecraft.world.gen.feature.Feature;
import superlord.prehistoricfauna.init.BlockInit;
import superlord.prehistoricfauna.world.placement.AraucariaConfig;

import java.util.Random;
import java.util.function.Function;

public class AraucariaTreeGenerator extends Feature<AraucariaConfig> {
	public AraucariaTreeGenerator(Function<Dynamic<?>, ? extends AraucariaConfig> p_i225808_1_) {
		super(p_i225808_1_);
	}

	@Override
	public boolean place(IWorld world, ChunkGenerator<? extends GenerationSettings> generator, Random rand, BlockPos pos, AraucariaConfig config) {
		int i = 0;
		for(int j = 0; j < config.count; ++j) {
			int k = rand.nextInt(8) - rand.nextInt(8);
			int l = rand.nextInt(8) - rand.nextInt(8);
			int i1 = world.getHeight(Heightmap.Type.WORLD_SURFACE, pos.getX() + k, pos.getZ() + l);
			BlockPos blockpos = new BlockPos(pos.getX() + k, i1, pos.getZ() + l);
			if (world.getBlockState(blockpos).getBlock() == Blocks.AIR && world.getBlockState(blockpos.down()).getBlock() == Blocks.COARSE_DIRT || world.getBlockState(blockpos).getBlock() == Blocks.AIR && world.getBlockState(blockpos.down()).getBlock() == Blocks.PODZOL || world.getBlockState(blockpos).getBlock() == Blocks.AIR && world.getBlockState(blockpos.down()).getBlock() == BlockInit.MOSSY_DIRT) {	
				if (world.getBlockState(pos.down()).getBlock() == BlockInit.MOSSY_DIRT && world.getBlockState(pos.down().south()).getBlock() == BlockInit.MOSSY_DIRT && world.getBlockState(pos.down().south().east()).getBlock() == BlockInit.MOSSY_DIRT || world.getBlockState(pos.down().east()).getBlock() == BlockInit.MOSSY_DIRT) {
					BlockState logX = BlockInit.ARAUCARIA_LOG.getDefaultState().with(LogBlock.AXIS, Direction.Axis.X);
					BlockState logZ = BlockInit.ARAUCARIA_LOG.getDefaultState().with(LogBlock.AXIS, Direction.Axis.Z);
					BlockState leaves = BlockInit.ARAUCARIA_LEAVES.getDefaultState().with(LeavesBlock.PERSISTENT, false);
					int j1 = rand.nextInt(5);
					for (BlockPos basePos : BlockPos.Mutable.getAllInBoxMutable(pos.add(-1, 0, 0), pos.add(0, 35 + j1, 1))) {
						world.setBlockState(basePos, BlockInit.ARAUCARIA_LOG.getDefaultState(), 2);
						//Branch 1 - Front
						world.setBlockState(pos.up(8 + j1).east(), logX, 2);
						world.setBlockState(pos.up(8 + j1).east(2).north(), logX, 2);
						world.setBlockState(pos.up(8 + j1).east(3).north(2), logX, 2);
						world.setBlockState(pos.up(8 + j1).east(4).north(3), logX, 2);
						world.setBlockState(pos.up(8 + j1).east(5).north(4), logX, 2);
						world.setBlockState(pos.up(8 + j1).east(6).north(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(5).north(3), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(5).north(5), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(4).north(2), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(4).north(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(5).north(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(4).north(3), leaves, 2);
						world.setBlockState(pos.up(7 + j1).east(4).north(3), leaves, 2);
						world.setBlockState(pos.up(7 + j1).east(5).north(4), leaves, 2);
						//Branch 2 - Front
						world.setBlockState(pos.up(9 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(2).south(2), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(3).south(3), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(4).south(4), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(5).south(5), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(4).south(3), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(4).south(5), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(5).south(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(5).south(6), leaves, 2);
						world.setBlockState(pos.up(10 + j1).east(4).south(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(4).south(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(5).south(5), leaves, 2);
						world.setBlockState(pos.up(10 + j1).east(5).south(5), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(4).south(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(6).south(5), leaves, 2);
						//Branch 3 - Front
						world.setBlockState(pos.up(10 + j1).east(), logX, 2);
						world.setBlockState(pos.up(10 + j1).east(2), logX, 2);
						world.setBlockState(pos.up(10 + j1).east(3), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(4), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(5), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(6), logX, 2);
						world.setBlockState(pos.up(9 + j1).east(7), leaves, 2);
						world.setBlockState(pos.up(10 + j1).east(6), leaves, 2);
						world.setBlockState(pos.up(10 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(6), leaves, 2);
						world.setBlockState(pos.up(8 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(6).south(), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(6).north(), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(9 + j1).east(5).north(), leaves, 2);
						//Branch 4 - Front
						world.setBlockState(pos.up(12 + j1).east(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(2).north(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(3).north(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(4).north(2), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(5).north(2), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(4).north(), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(5).north(), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(4).north(3), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(5).north(3), leaves, 2);
						world.setBlockState(pos.up(13 + j1).east(4).north(2), leaves, 2);
						world.setBlockState(pos.up(13 + j1).east(5).north(2), leaves, 2);
						world.setBlockState(pos.up(11 + j1).east(4).north(2), leaves, 2);
						world.setBlockState(pos.up(11 + j1).east(5).north(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(6).north(2), leaves, 2);
						//Branch 5 - Front
						world.setBlockState(pos.up(13 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(13 + j1).east(2).south(), logX, 2);
						world.setBlockState(pos.up(13 + j1).east(3).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(4).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(5).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(6).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).east(7).south(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).east(6).south(), leaves, 2);
						world.setBlockState(pos.up(13 + j1).east(6).south(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(13 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(6), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(6).south(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).east(5).south(2), leaves, 2);
						//Branch 6 - Front
						world.setBlockState(pos.up(15 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(2).south(2), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(3).south(3), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(4).south(3), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(5).south(4), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(6).south(4), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(5).south(3), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(4).south(2), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(5).south(5), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(4).south(4), leaves, 2);
						world.setBlockState(pos.up(16 + j1).east(5).south(4), leaves, 2);
						world.setBlockState(pos.up(14 + j1).east(5).south(4), leaves, 2);
						world.setBlockState(pos.up(14 + j1).east(4).south(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).east(4).south(3), leaves, 2);
						//Branch 7 - Front
						world.setBlockState(pos.up(16 + j1).east(), logX, 2);
						world.setBlockState(pos.up(16 + j1).east(2), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(3), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(4), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(5), logX, 2);
						world.setBlockState(pos.up(15 + j1).east(6), leaves, 2);
						world.setBlockState(pos.up(14 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(14 + j1).east(4), leaves, 2);
						world.setBlockState(pos.up(16 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(16 + j1).east(4), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(5).north(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(4).north(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).east(4).south(), leaves, 2);
						//Branch 8 - Front
						world.setBlockState(pos.up(18 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(18 + j1).east(2).south(), logX, 2);
						world.setBlockState(pos.up(17 + j1).east(3).south(), logX, 2);
						world.setBlockState(pos.up(17 + j1).east(4).south(), logX, 2);
						world.setBlockState(pos.up(17 + j1).east(5).south(), logX, 2);
						world.setBlockState(pos.up(17 + j1).east(6).south(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).east(4).south(), leaves, 2);
						world.setBlockState(pos.up(16 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(16 + j1).east(4).south(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).east(5).south(2), leaves, 2);
						world.setBlockState(pos.up(17 + j1).east(4).south(2), leaves, 2);
						world.setBlockState(pos.up(17 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(17 + j1).east(4), leaves, 2);
						//Branch 9 - Front
						world.setBlockState(pos.up(19 + j1).east(), logX, 2);
						world.setBlockState(pos.up(19 + j1).east(2).north(), logX, 2);
						world.setBlockState(pos.up(19 + j1).east(3).north(2), logX, 2);
						world.setBlockState(pos.up(19 + j1).east(4).north(3), logX, 2);
						world.setBlockState(pos.up(19 + j1).east(3).north(), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(4).north(2), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(5).north(3), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(3).north(3), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(4).north(4), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(3).north(2), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(4).north(3), leaves, 2);
						world.setBlockState(pos.up(18 + j1).east(3).north(2), leaves, 2);
						world.setBlockState(pos.up(18 + j1).east(4).north(3), leaves, 2);
						//Branch 10 - Front
						world.setBlockState(pos.up(20 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(20 + j1).east(2).south(2), logX, 2);
						world.setBlockState(pos.up(20 + j1).east(3).south(3), logX, 2);
						world.setBlockState(pos.up(20 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(3).south(2), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(4).south(3), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(3).south(4), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(2).south(3), leaves, 2);
						world.setBlockState(pos.up(21 + j1).east(2).south(2), leaves, 2);
						world.setBlockState(pos.up(21 + j1).east(3).south(3), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(2).south(2), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(3).south(3), leaves, 2);
						//Branch 11 - Front
						world.setBlockState(pos.up(21 + j1).east(), logX, 2);
						world.setBlockState(pos.up(21 + j1).east(2), logX, 2);
						world.setBlockState(pos.up(20 + j1).east(3), logX, 2);
						world.setBlockState(pos.up(20 + j1).east(4), logX, 2);
						world.setBlockState(pos.up(20 + j1).east(5), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(3).north(), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(4).north(), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(3).south(), leaves, 2);
						world.setBlockState(pos.up(20 + j1).east(4).south(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).east(3), leaves, 2);
						world.setBlockState(pos.up(21 + j1).east(4), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(3), leaves, 2);
						world.setBlockState(pos.up(19 + j1).east(4), leaves, 2);
						//Branch 12 - Front
						world.setBlockState(pos.up(23 + j1).east(), logX, 2);
						world.setBlockState(pos.up(23 + j1).east(2).north(), logX, 2);
						world.setBlockState(pos.up(23 + j1).east(3).north(2), logX, 2);
						world.setBlockState(pos.up(23 + j1).east(2), leaves, 2);
						world.setBlockState(pos.up(23 + j1).east(3).north(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).east(2).north(2), leaves, 2);
						world.setBlockState(pos.up(23 + j1).east(3).north(3), leaves, 2);
						world.setBlockState(pos.up(23 + j1).east(4).north(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).east(2).north(), leaves, 2);
						world.setBlockState(pos.up(22 + j1).east(2).north(), leaves, 2);
						world.setBlockState(pos.up(24 + j1).east(3).north(2), leaves, 2);
						world.setBlockState(pos.up(22 + j1).east(3).north(2), leaves, 2);
						//Branch 13 - Front
						world.setBlockState(pos.up(25 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(25 + j1).east(2).south(), logX, 2);
						world.setBlockState(pos.up(24 + j1).east(3).south(), logX, 2);
						world.setBlockState(pos.up(24 + j1).east(4).south(), logX, 2);
						world.setBlockState(pos.up(24 + j1).east(5).south(), leaves, 2);
						world.setBlockState(pos.up(24 + j1).east(4), leaves, 2);
						world.setBlockState(pos.up(24 + j1).east(3), leaves, 2);
						world.setBlockState(pos.up(24 + j1).east(4).south(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).east(3).south(2), leaves, 2);
						world.setBlockState(pos.up(25 + j1).east(4).south(), leaves, 2);
						world.setBlockState(pos.up(25 + j1).east(3).south(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).east(4).south(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).east(3).south(), leaves, 2);
						//Branch 14 - Front
						world.setBlockState(pos.up(27 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(27 + j1).east(2).south(2), logX, 2);
						world.setBlockState(pos.up(27 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(27 + j1).east(2).south(3), leaves, 2);
						world.setBlockState(pos.up(27 + j1).east(3).south(2), leaves, 2);
						world.setBlockState(pos.up(28 + j1).east(2).south(2), leaves, 2);
						world.setBlockState(pos.up(26 + j1).east(2).south(2), leaves, 2);
						//Branch 15 - Front
						world.setBlockState(pos.up(29 + j1).east(), logX, 2);
						world.setBlockState(pos.up(28 + j1).east(2), logX, 2);
						world.setBlockState(pos.up(28 + j1).east(3), logX, 2);
						world.setBlockState(pos.up(28 + j1).east(4), leaves, 2);
						world.setBlockState(pos.up(27 + j1).east(2), leaves, 2);
						world.setBlockState(pos.up(27 + j1).east(3), leaves, 2);
						world.setBlockState(pos.up(29 + j1).east(2), leaves, 2);
						world.setBlockState(pos.up(29 + j1).east(3), leaves, 2);
						world.setBlockState(pos.up(28 + j1).east(2).north(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).east(3).north(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).east(3).south(), leaves, 2);
						//Branch 16 - Front
						world.setBlockState(pos.up(30 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(30 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).east(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).east().south(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).east().south(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).east().south(), leaves, 2);
						//Branch 17 - Front
						world.setBlockState(pos.up(31 + j1).east(), logX, 2);
						world.setBlockState(pos.up(31 + j1).east(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).east().north(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).east(), leaves, 2);
						//Branch 18 - Front
						world.setBlockState(pos.up(32 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(31 + j1).east(2).south(), logX, 2);
						world.setBlockState(pos.up(31 + j1).east(3).south(), logX, 2);
						world.setBlockState(pos.up(31 + j1).east(4).south(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).east(3).south(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).east(3).south(), leaves, 2);
						world.setBlockState(pos.up(31 + j1).east(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).east(3), leaves, 2);
						world.setBlockState(pos.up(31 + j1).east(2).south(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).east(3).south(2), leaves, 2);
						//Branch 19 = Front
						world.setBlockState(pos.up(34 + j1).east().south(), logX, 2);
						world.setBlockState(pos.up(34 + j1).east(2).south(), leaves, 2);
						world.setBlockState(pos.up(35 + j1).east().south(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).east().south(), leaves, 2);
						world.setBlockState(pos.up(34 + j1).east(), leaves, 2);
						world.setBlockState(pos.up(34 + j1).east().south(2), leaves, 2);
						//Top Leaves
						world.setBlockState(pos.up(36 + j1), leaves, 2);
						world.setBlockState(pos.up(36 + j1).south(), leaves, 2);
						world.setBlockState(pos.up(36 + j1).south().west(), BlockInit.ARAUCARIA_LOG.getDefaultState(), 2);
						world.setBlockState(pos.up(37 + j1).south().west(), leaves, 2);
						world.setBlockState(pos.up(36 + j1).west(), leaves, 2);
						//Branch 1 - North
						world.setBlockState(pos.up(9 + j1).west().north(), logZ, 2);
						world.setBlockState(pos.up(9 + j1).west().north(2), logZ, 2);
						world.setBlockState(pos.up(9 + j1).west().north(3), logZ, 2);
						world.setBlockState(pos.up(8 + j1).west().north(4), logZ, 2);
						world.setBlockState(pos.up(8 + j1).west().north(5), logZ, 2);
						world.setBlockState(pos.up(8 + j1).west().north(6), logZ, 2);
						world.setBlockState(pos.up(8 + j1).west().north(7), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west().north(5), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west().north(6), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west().north(5), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west().north(6), leaves, 2);
						world.setBlockState(pos.up(8 + j1).north(5), leaves, 2);
						world.setBlockState(pos.up(8 + j1).north(6), leaves, 2);
						world.setBlockState(pos.up(8 + j1).north(5).west(2), leaves, 2);
						world.setBlockState(pos.up(8 + j1).north(6).west(2), leaves, 2);
						//Branch 2 - North
						world.setBlockState(pos.up(10 + j1).west().north(), logZ, 2);
						world.setBlockState(pos.up(10 + j1).west(2).north(2), logZ, 2);
						world.setBlockState(pos.up(10 + j1).west(3).north(3), logZ, 2);
						world.setBlockState(pos.up(10 + j1).west(4).north(4), logZ, 2);
						world.setBlockState(pos.up(10 + j1).west(5).north(5), logZ, 2);
						world.setBlockState(pos.up(11 + j1).west(5).north(5), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(4).north(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(4).north(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(5).north(5), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(3).north(4), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(5).north(4), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(4).north(5), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(6).north(5), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(5).north(6), leaves, 2);
						//Branch 3 - North
						world.setBlockState(pos.up(10 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(10 + j1).north(2).east(), logZ, 2);
						world.setBlockState(pos.up(10 + j1).north(3).east(2), logZ, 2);
						world.setBlockState(pos.up(10 + j1).north(4).east(2), logZ, 2);
						world.setBlockState(pos.up(10 + j1).north(5).east(3), logZ, 2);
						world.setBlockState(pos.up(10 + j1).north(5).east(2), leaves, 2);
						world.setBlockState(pos.up(10 + j1).north(4).east(), leaves, 2);
						world.setBlockState(pos.up(10 + j1).north(4).east(3), leaves, 2);
						world.setBlockState(pos.up(11 + j1).north(4).east(2), leaves, 2);
						world.setBlockState(pos.up(9 + j1).north(4).east(2), leaves, 2);
						world.setBlockState(pos.up(10 + j1).north(6).east(3), leaves, 2);
						world.setBlockState(pos.up(11 + j1).north(5).east(3), leaves, 2);
						world.setBlockState(pos.up(9 + j1).north(5).east(3), leaves, 2);
						world.setBlockState(pos.up(10 + j1).north(5).east(4), leaves, 2);
						//Branch 4 - North
						world.setBlockState(pos.up(12 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(12 + j1).north(2), logZ, 2);
						world.setBlockState(pos.up(12 + j1).north(3), logZ, 2);
						world.setBlockState(pos.up(11 + j1).north(4), logZ, 2);
						world.setBlockState(pos.up(11 + j1).north(5), logZ, 2);
						world.setBlockState(pos.up(11 + j1).north(6), logZ, 2);
						world.setBlockState(pos.up(11 + j1).north(7), leaves, 2);
						world.setBlockState(pos.up(12 + j1).north(5), leaves, 2);
						world.setBlockState(pos.up(12 + j1).north(6), leaves, 2);
						world.setBlockState(pos.up(10 + j1).north(5), leaves, 2);
						world.setBlockState(pos.up(10 + j1).north(6), leaves, 2);
						world.setBlockState(pos.up(11 + j1).north(5).east(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).north(6).east(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).north(5).west(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).north(6).west(), leaves, 2);
						//Branch 5 - North
						world.setBlockState(pos.up(13 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(13 + j1).north(2).east(), logZ, 2);
						world.setBlockState(pos.up(13 + j1).north(3).east(2), logZ, 2);
						world.setBlockState(pos.up(13 + j1).north(4).east(3), logZ, 2);
						world.setBlockState(pos.up(13 + j1).north(5).east(4), logZ, 2);
						world.setBlockState(pos.up(13 + j1).north(4).east(2), leaves, 2);
						world.setBlockState(pos.up(14 + j1).north(4).east(3), leaves, 2);
						world.setBlockState(pos.up(12 + j1).north(4).east(3), leaves, 2);
						world.setBlockState(pos.up(13 + j1).north(4).east(4), leaves, 2);
						world.setBlockState(pos.up(13 + j1).north(5).east(3), leaves, 2);
						world.setBlockState(pos.up(13 + j1).north(6).east(4), leaves, 2);
						world.setBlockState(pos.up(14 + j1).north(5).east(4), leaves, 2);
						world.setBlockState(pos.up(12 + j1).north(5).east(4), leaves, 2);
						world.setBlockState(pos.up(13 + j1).north(5).east(5), leaves, 2);
						//Branch 6 - North
						world.setBlockState(pos.up(14 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(14 + j1).north(2).west(2), logZ, 2);
						world.setBlockState(pos.up(14 + j1).north(3).west(2), logZ, 2);
						world.setBlockState(pos.up(14 + j1).north(4).west(3), logZ, 2);
						world.setBlockState(pos.up(14 + j1).north(5).west(4), logZ, 2);
						world.setBlockState(pos.up(14 + j1).north(4).west(2), leaves, 2);
						world.setBlockState(pos.up(14 + j1).north(4).west(4), leaves, 2);
						world.setBlockState(pos.up(15 + j1).north(4).west(3), leaves, 2);
						world.setBlockState(pos.up(13 + j1).north(4).west(3), leaves, 2);
						world.setBlockState(pos.up(15 + j1).north(5).west(4), leaves, 2);
						world.setBlockState(pos.up(13 + j1).north(5).west(4), leaves, 2);
						world.setBlockState(pos.up(14 + j1).north(6).west(4), leaves, 2);
						world.setBlockState(pos.up(14 + j1).north(5).west(3), leaves, 2);
						world.setBlockState(pos.up(14 + j1).north(5).west(5), leaves, 2);
						//Branch 7 - North
						world.setBlockState(pos.up(16 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(2).east(), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(3).east(2), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(4).east(3), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(4).east(2), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(3).east(2), leaves, 2);
						world.setBlockState(pos.up(15 + j1).north(3).east(2), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(3).east(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(3).east(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(4).east(3), leaves, 2);
						world.setBlockState(pos.up(15 + j1).north(4).east(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(5).east(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(4).east(4), leaves, 2);
						//Branch 8 - North
						world.setBlockState(pos.up(17 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(17 + j1).north(2), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(3), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(4), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(5), logZ, 2);
						world.setBlockState(pos.up(16 + j1).north(4).east(), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(4).west(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(15 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(5).east(), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(5).west(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(5), leaves, 2);
						world.setBlockState(pos.up(15 + j1).north(5), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(6), leaves, 2);
						//Branch 9 - North
						world.setBlockState(pos.up(17 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(17 + j1).north(2).west(2), logZ, 2);
						world.setBlockState(pos.up(17 + j1).north(3).west(3), logZ, 2);
						world.setBlockState(pos.up(17 + j1).north(4).west(4), logZ, 2);
						world.setBlockState(pos.up(17 + j1).north(3).west(2), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(3).west(4), leaves, 2);
						world.setBlockState(pos.up(18 + j1).north(3).west(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(3).west(3), leaves, 2);
						world.setBlockState(pos.up(18 + j1).north(4).west(4), leaves, 2);
						world.setBlockState(pos.up(16 + j1).north(4).west(4), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(5).west(4), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(4).west(3), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(4).west(5), leaves, 2);
						//Branch 10 - North
						world.setBlockState(pos.up(19 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(19 + j1).north(2).west(), logZ, 2);
						world.setBlockState(pos.up(18 + j1).north(3).west(), logZ, 2);
						world.setBlockState(pos.up(18 + j1).north(4).west(), logZ, 2);
						world.setBlockState(pos.up(18 + j1).north(5).west(), logZ, 2);
						world.setBlockState(pos.up(18 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(18 + j1).north(4).west(2), leaves, 2);
						world.setBlockState(pos.up(19 + j1).north(4).west(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(4).west(), leaves, 2);
						world.setBlockState(pos.up(19 + j1).north(5).west(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).north(5).west(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).north(5).west(2), leaves, 2);
						world.setBlockState(pos.up(18 + j1).north(5), leaves, 2);
						world.setBlockState(pos.up(18 + j1).north(6).west(), leaves, 2);
						//Branch 11 - North
						world.setBlockState(pos.up(22 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(22 + j1).north(2), logZ, 2);
						world.setBlockState(pos.up(21 + j1).north(3), logZ, 2);
						world.setBlockState(pos.up(21 + j1).north(4), logZ, 2);
						world.setBlockState(pos.up(22 + j1).north(3), leaves, 2);
						world.setBlockState(pos.up(22 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(20 + j1).north(3), leaves, 2);
						world.setBlockState(pos.up(20 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(21 + j1).north(3).east(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).north(4).east(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).north(3).west(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).north(4).west(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).north(5), leaves, 2);
						//Branch 12 - North
						world.setBlockState(pos.up(23 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(23 + j1).north(2).west(2), logZ, 2);
						world.setBlockState(pos.up(23 + j1).north(3).west(3), logZ, 2);
						world.setBlockState(pos.up(24 + j1).north(2).west(2), leaves, 2);
						world.setBlockState(pos.up(22 + j1).north(2).west(2), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(2).west(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(2).west(3), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(3).west(2), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(3).west(4), leaves, 2);
						world.setBlockState(pos.up(24 + j1).north(3).west(3), leaves, 2);
						world.setBlockState(pos.up(22 + j1).north(3).west(3), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(4).west(3), leaves, 2);
						//Branch 13 - North
						world.setBlockState(pos.up(25 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(25 + j1).north(2).west(), logZ, 2);
						world.setBlockState(pos.up(24 + j1).north(3).west(), logZ, 2);
						world.setBlockState(pos.up(24 + j1).north(4).west(), logZ, 2);
						world.setBlockState(pos.up(25 + j1).north(3).west(), leaves, 2);
						world.setBlockState(pos.up(25 + j1).north(4).west(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(3).west(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).north(4).west(), leaves, 2);
						world.setBlockState(pos.up(24 + j1).north(3).west(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).north(4).west(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).north(3), leaves, 2);
						world.setBlockState(pos.up(24 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(24 + j1).north(5).west(), leaves, 2);
						//Branch 14 - North
						world.setBlockState(pos.up(26 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(26 + j1).north(2).east(), logZ, 2);
						world.setBlockState(pos.up(26 + j1).north(3).east(2), logZ, 2);
						world.setBlockState(pos.up(26 + j1).north(2), leaves, 2);
						world.setBlockState(pos.up(26 + j1).north(2).east(2), leaves, 2);
						world.setBlockState(pos.up(27 + j1).north(2).east(), leaves, 2);
						world.setBlockState(pos.up(25 + j1).north(2).east(), leaves, 2);
						world.setBlockState(pos.up(27 + j1).north(3).east(2), leaves, 2);
						world.setBlockState(pos.up(25 + j1).north(3).east(2), leaves, 2);
						world.setBlockState(pos.up(26 + j1).north(3).east(3), leaves, 2);
						world.setBlockState(pos.up(26 + j1).north(3).east(), leaves, 2);
						world.setBlockState(pos.up(26 + j1).north(4).east(2), leaves, 2);
						//Branch 15 - North
						world.setBlockState(pos.up(29 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(28 + j1).north(2).west(), logZ, 2);
						world.setBlockState(pos.up(28 + j1).north(3).west(), logZ, 2);
						world.setBlockState(pos.up(29 + j1).north(2).west(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).north(3).west(), leaves, 2);
						world.setBlockState(pos.up(27 + j1).north(2).west(), leaves, 2);
						world.setBlockState(pos.up(27 + j1).north(3).west(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).north(2).west(2), leaves, 2);
						world.setBlockState(pos.up(28 + j1).north(3).west(2), leaves, 2);
						world.setBlockState(pos.up(28 + j1).north(2), leaves, 2);
						world.setBlockState(pos.up(28 + j1).north(3), leaves, 2);
						world.setBlockState(pos.up(28 + j1).north(4).west(), leaves, 2);
						//Branch 16 - North
						world.setBlockState(pos.up(30 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(31 + j1).north().west(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north().west(2), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north(), leaves, 2);
						//Branch 17 - North
						world.setBlockState(pos.up(31 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(30 + j1).north(2), logZ, 2);
						world.setBlockState(pos.up(30 + j1).north(3), logZ, 2);
						world.setBlockState(pos.up(31 + j1).north(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).north(3), leaves, 2);
						world.setBlockState(pos.up(29 + j1).north(2), leaves, 2);
						world.setBlockState(pos.up(29 + j1).north(3), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north(2).east(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north(3).east(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north(2).west(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north(3).west(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).north(4), leaves, 2);
						world.setBlockState(pos.up(32 + j1).north(), leaves, 2);
						//Branch 18 - North
						world.setBlockState(pos.up(33 + j1).north(), logZ, 2);
						world.setBlockState(pos.up(33 + j1).north(2), leaves, 2);
						world.setBlockState(pos.up(34 + j1).north(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).north().west(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).north().east(), leaves, 2);
						//Branch 19 - North
						world.setBlockState(pos.up(35 + j1).north().west(), logZ, 2);
						world.setBlockState(pos.up(35 + j1).north(2).west(), leaves, 2);
						world.setBlockState(pos.up(35 + j1).north().west(2), leaves, 2);
						world.setBlockState(pos.up(35 + j1).north(), leaves, 2);
						world.setBlockState(pos.up(36 + j1).north().west(), leaves, 2);
						world.setBlockState(pos.up(34 + j1).north().west(), leaves, 2);
						//Branch 1 - South
						world.setBlockState(pos.up(7 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(7 + j1).south(3).east(), logZ, 2);
						world.setBlockState(pos.up(7 + j1).south(4).east(), logZ, 2);
						world.setBlockState(pos.up(7 + j1).south(5).east(2), logZ, 2);
						world.setBlockState(pos.up(7 + j1).south(6).east(3), logZ, 2);
						world.setBlockState(pos.up(7 + j1).south(5).east(), leaves, 2);
						world.setBlockState(pos.up(7 + j1).south(5).east(3), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(5).east(2), leaves, 2);
						world.setBlockState(pos.up(6 + j1).south(4).east(), leaves, 2);
						world.setBlockState(pos.up(7 + j1).south(6).east(2), leaves, 2);
						world.setBlockState(pos.up(7 + j1).south(6).east(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(6).east(3), leaves, 2);
						world.setBlockState(pos.up(6 + j1).south(6).east(3), leaves, 2);
						world.setBlockState(pos.up(7 + j1).south(7).east(3), leaves, 2);
						//Branch 2 - South
						world.setBlockState(pos.up(9 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(9 + j1).south(3).west(), logZ, 2);
						world.setBlockState(pos.up(9 + j1).south(4).west(), logZ, 2);
						world.setBlockState(pos.up(8 + j1).south(5).west(), logZ, 2);
						world.setBlockState(pos.up(8 + j1).south(6).west(), logZ, 2);
						world.setBlockState(pos.up(8 + j1).south(7).west(), logZ, 2);
						world.setBlockState(pos.up(9 + j1).south(6).west(), leaves, 2);
						world.setBlockState(pos.up(7 + j1).south(6).west(), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(6).west(2), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(6), leaves, 2);
						world.setBlockState(pos.up(9 + j1).south(7).west(), leaves, 2);
						world.setBlockState(pos.up(7 + j1).south(7).west(), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(7).west(2), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(7), leaves, 2);
						world.setBlockState(pos.up(8 + j1).south(8).west(), leaves, 2);
						//Branch 3 - South
						world.setBlockState(pos.up(10 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(3).west(2), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(4).west(3), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(5).west(3), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(6).west(4), logZ, 2);
						world.setBlockState(pos.up(11 + j1).south(5).west(3), leaves, 2);
						world.setBlockState(pos.up(9 + j1).south(5).west(3), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(5).west(2), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(5).west(4), leaves, 2);
						world.setBlockState(pos.up(11 + j1).south(6).west(4), leaves, 2);
						world.setBlockState(pos.up(9 + j1).south(6).west(4), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(6).west(3), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(6).west(5), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(7).west(4), leaves, 2);
						//Branch 4 - South
						world.setBlockState(pos.up(11 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(11 + j1).south(3), logZ, 2);
						world.setBlockState(pos.up(11 + j1).south(4), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(5), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(6), logZ, 2);
						world.setBlockState(pos.up(10 + j1).south(7), logZ, 2);
						world.setBlockState(pos.up(11 + j1).south(6), leaves, 2);
						world.setBlockState(pos.up(9 + j1).south(6), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(6).east(), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(6).west(), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(8), leaves, 2);
						world.setBlockState(pos.up(11 + j1).south(7), leaves, 2);
						world.setBlockState(pos.up(9 + j1).south(7), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(7).east(), leaves, 2);
						world.setBlockState(pos.up(10 + j1).south(7).west(), leaves, 2);
						//Branch 5 - South
						world.setBlockState(pos.up(13 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(13 + j1).south(3).west(2), logZ, 2);
						world.setBlockState(pos.up(13 + j1).south(4).west(3), logZ, 2);
						world.setBlockState(pos.up(13 + j1).south(5).west(4), logZ, 2);
						world.setBlockState(pos.up(13 + j1).south(6).west(5), logZ, 2);
						world.setBlockState(pos.up(14 + j1).south(5).west(4), leaves, 2);
						world.setBlockState(pos.up(12 + j1).south(5).west(4), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(5).west(5), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(5).west(3), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(6).west(5), leaves, 2);
						world.setBlockState(pos.up(12 + j1).south(6).west(5), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(6).west(6), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(6).west(4), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(7).west(5), leaves, 2);
						//Branch 6 - South
						world.setBlockState(pos.up(14 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(14 + j1).south(3).east(), logZ, 2);
						world.setBlockState(pos.up(14 + j1).south(4).east(), logZ, 2);
						world.setBlockState(pos.up(14 + j1).south(5).east(2), logZ, 2);
						world.setBlockState(pos.up(14 + j1).south(6).east(2), logZ, 2);
						world.setBlockState(pos.up(14 + j1).south(5).east(), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(6).east(), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(5).east(3), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(6).east(3), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(5).east(2), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(6).east(2), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(5).east(2), leaves, 2);
						world.setBlockState(pos.up(13 + j1).south(6).east(2), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(7).east(2), leaves, 2);
						//Branch 7 - South
						world.setBlockState(pos.up(16 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(16 + j1).south(3).west(), logZ, 2);
						world.setBlockState(pos.up(15 + j1).south(4).west(), logZ, 2);
						world.setBlockState(pos.up(15 + j1).south(5).west(), logZ, 2);
						world.setBlockState(pos.up(15 + j1).south(6).west(), logZ, 2);
						world.setBlockState(pos.up(16 + j1).south(5).west(), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(5).west(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(5).west(2), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(5), leaves, 2);
						world.setBlockState(pos.up(16 + j1).south(6).west(), leaves, 2);
						world.setBlockState(pos.up(14 + j1).south(6).west(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(6).west(2), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(6), leaves, 2);
						world.setBlockState(pos.up(15 + j1).south(7).west(), leaves, 2);
						//Branch 8 - South
						world.setBlockState(pos.up(17 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(17 + j1).south(3).east(), logZ, 2);
						world.setBlockState(pos.up(17 + j1).south(4).east(2), logZ, 2);
						world.setBlockState(pos.up(17 + j1).south(5).east(3), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(4).east(2), leaves, 2);
						world.setBlockState(pos.up(16 + j1).south(4).east(2), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(4).east(3), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(4).east(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(5).east(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).south(5).east(3), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(5).east(4), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(5).east(2), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(6).east(3), leaves, 2);
						//Branch 9 - South
						world.setBlockState(pos.up(18 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(3).west(2), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(4).west(3), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(5).west(4), logZ, 2);
						world.setBlockState(pos.up(17 + j1).south(4).west(3), leaves, 2);
						world.setBlockState(pos.up(19 + j1).south(4).west(3), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(4).west(4), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(4).west(2), leaves, 2);
						world.setBlockState(pos.up(19 + j1).south(5).west(4), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(5).west(4), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(5).west(5), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(5).west(3), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(6).west(4), leaves, 2);
						//Branch 10 - South
						world.setBlockState(pos.up(19 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(19 + j1).south(3), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(4), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(5), logZ, 2);
						world.setBlockState(pos.up(18 + j1).south(6), logZ, 2);
						world.setBlockState(pos.up(19 + j1).south(5), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(5), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(5).east(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(5).west(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).south(6), leaves, 2);
						world.setBlockState(pos.up(19 + j1).south(6), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(6).west(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(6).east(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).south(7), leaves, 2);
						//Branch 11 - South
						world.setBlockState(pos.up(23 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(23 + j1).south(3).east(), logZ, 2);
						world.setBlockState(pos.up(24 + j1).south(3).east(), leaves, 2);
						world.setBlockState(pos.up(22 + j1).south(3).east(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).south(3).east(2), leaves, 2);
						world.setBlockState(pos.up(23 + j1).south(3), leaves, 2);
						world.setBlockState(pos.up(23 + j1).south(4).east(), leaves, 2);
						//Branch 12 - South
						world.setBlockState(pos.up(23 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(23 + j1).south(3).west(), logZ, 2);
						world.setBlockState(pos.up(22 + j1).south(4).west(), logZ, 2);
						world.setBlockState(pos.up(22 + j1).south(5).west(), logZ, 2);
						world.setBlockState(pos.up(23 + j1).south(4).west(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).south(4).west(), leaves, 2);
						world.setBlockState(pos.up(22 + j1).south(4).west(2), leaves, 2);
						world.setBlockState(pos.up(22 + j1).south(4), leaves, 2);
						world.setBlockState(pos.up(23 + j1).south(5).west(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).south(5).west(), leaves, 2);
						world.setBlockState(pos.up(22 + j1).south(5).west(2), leaves, 2);
						world.setBlockState(pos.up(22 + j1).south(5), leaves, 2);
						world.setBlockState(pos.up(22 + j1).south(6).west(), leaves, 2);
						//Branch 13 - South
						world.setBlockState(pos.up(24 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(24 + j1).south(3).west(2), logZ, 2);
						world.setBlockState(pos.up(24 + j1).south(4).west(3), logZ, 2);
						world.setBlockState(pos.up(24 + j1).south(3).west(), leaves, 2);
						world.setBlockState(pos.up(24 + j1).south(3).west(3), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(3).west(2), leaves, 2);
						world.setBlockState(pos.up(23 + j1).south(3).west(2), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(4).west(3), leaves, 2);
						world.setBlockState(pos.up(23 + j1).south(4).west(3), leaves, 2);
						world.setBlockState(pos.up(24 + j1).south(4).west(4), leaves, 2);
						world.setBlockState(pos.up(24 + j1).south(4).west(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).south(5).west(3), leaves, 2);
						//Branch 14 - South
						world.setBlockState(pos.up(26 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(26 + j1).south(3), logZ, 2);
						world.setBlockState(pos.up(25 + j1).south(4), logZ, 2);
						world.setBlockState(pos.up(25 + j1).south(5), logZ, 2);
						world.setBlockState(pos.up(26 + j1).south(4), leaves, 2);
						world.setBlockState(pos.up(24 + j1).south(4), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(4).east(), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(4).west(), leaves, 2);
						world.setBlockState(pos.up(26 + j1).south(5), leaves, 2);
						world.setBlockState(pos.up(24 + j1).south(5), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(5).west(), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(5).east(), leaves, 2);
						world.setBlockState(pos.up(25 + j1).south(6), leaves, 2);
						//Branch 15 - South
						world.setBlockState(pos.up(28 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(27 + j1).south(2).west(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).south(2).west(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(2).west(2), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(2), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(3).west(), leaves, 2);
						//Branch 16 - South
						world.setBlockState(pos.up(29 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(28 + j1).south(3), logZ, 2);
						world.setBlockState(pos.up(28 + j1).south(4), logZ, 2);
						world.setBlockState(pos.up(29 + j1).south(3), leaves, 2);
						world.setBlockState(pos.up(27 + j1).south(3), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(3).east(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(3).west(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).south(4), leaves, 2);
						world.setBlockState(pos.up(27 + j1).south(4), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(4).east(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(4).west(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).south(5), leaves, 2);
						//Branch 17 - South
						world.setBlockState(pos.up(30 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(30 + j1).south(2), leaves, 2);
						world.setBlockState(pos.up(30 + j1).south(2).west(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).south(2).west(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).south(2).west(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).south(3).west(), leaves, 2);
						//Branch 18 - South
						world.setBlockState(pos.up(32 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(32 + j1).south(2).east(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).south(2).west(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).south(2), leaves, 2);
						world.setBlockState(pos.up(31 + j1).south(2), leaves, 2);
						world.setBlockState(pos.up(32 + j1).south(3), leaves, 2);
						//Branch 19 - South
						world.setBlockState(pos.up(34 + j1).south(2).west(), logZ, 2);
						world.setBlockState(pos.up(33 + j1).south(3).west(), logZ, 2);
						world.setBlockState(pos.up(33 + j1).south(4).west(), logZ, 2);
						world.setBlockState(pos.up(34 + j1).south(3).west(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).south(3).west(2), leaves, 2);
						world.setBlockState(pos.up(34 + j1).south(4).west(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).south(4).west(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).south(4).west(2), leaves, 2);
						world.setBlockState(pos.up(33 + j1).south(4), leaves, 2);
						world.setBlockState(pos.up(33 + j1).south(3), leaves, 2);
						world.setBlockState(pos.up(33 + j1).south(5).west(), leaves, 2);
						//Branch 20 - South
						world.setBlockState(pos.up(35 + j1).south(2), logZ, 2);
						world.setBlockState(pos.up(36 + j1).south(2), leaves, 2);
						world.setBlockState(pos.up(35 + j1).south(2).west(), leaves, 2);
						world.setBlockState(pos.up(35 + j1).south(2).east(), leaves, 2);
						world.setBlockState(pos.up(35 + j1).south(3), leaves, 2);
						world.setBlockState(pos.up(36 + j1).south(2).west(), leaves, 2);
						//Branch 1 - West
						world.setBlockState(pos.up(7 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(7 + j1).west(3).north(), logX, 2);
						world.setBlockState(pos.up(7 + j1).west(4).north(), logX, 2);
						world.setBlockState(pos.up(7 + j1).west(5).north(2), logX, 2);
						world.setBlockState(pos.up(7 + j1).west(6).north(3), logX, 2);
						world.setBlockState(pos.up(7 + j1).west(5).north(3), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west(5).north(), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(5).north(2), leaves, 2);
						world.setBlockState(pos.up(6 + j1).west(5).north(2), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west(6).north(4), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west(6).north(2), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(6).north(3), leaves, 2);
						world.setBlockState(pos.up(6 + j1).west(6).north(3), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west(7).north(3), leaves, 2);
						//Branch 2 - West
						world.setBlockState(pos.up(8 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(8 + j1).west(3).south(2), logX, 2);
						world.setBlockState(pos.up(8 + j1).west(4).south(3), logX, 2);
						world.setBlockState(pos.up(8 + j1).west(5).south(4), logX, 2);
						world.setBlockState(pos.up(8 + j1).west(6).south(5), logX, 2);
						world.setBlockState(pos.up(8 + j1).west(5).south(3), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(5).south(5), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(5).south(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(5).south(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(6).south(4), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(6).south(6), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(6).south(5), leaves, 2);
						world.setBlockState(pos.up(7 + j1).west(6).south(5), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(7).south(5), leaves, 2);
						//Bramch 3 - West
						world.setBlockState(pos.up(10 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(10 + j1).west(3), logX, 2);
						world.setBlockState(pos.up(10 + j1).west(4), logX, 2);
						world.setBlockState(pos.up(9 + j1).west(5), logX, 2);
						world.setBlockState(pos.up(9 + j1).west(6), logX, 2);
						world.setBlockState(pos.up(9 + j1).west(7), logX, 2);
						world.setBlockState(pos.up(8 + j1).west(6), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(6), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(6).north(), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(6).south(), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(7), leaves, 2);
						world.setBlockState(pos.up(8 + j1).west(7), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(7).north(), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(7).south(), leaves, 2);
						world.setBlockState(pos.up(9 + j1).west(8), leaves, 2);
						//Branch 4 - West
						world.setBlockState(pos.up(11 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(11 + j1).west(3).south(2), logX, 2);
						world.setBlockState(pos.up(11 + j1).west(4).south(2), logX, 2);
						world.setBlockState(pos.up(11 + j1).west(5).south(3), logX, 2);
						world.setBlockState(pos.up(11 + j1).west(6).south(3), logX, 2);
						world.setBlockState(pos.up(11 + j1).west(5).south(2), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(5).south(4), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(5).south(3), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(5).south(3), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(6).south(4), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(6).south(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(6).south(3), leaves, 2);
						world.setBlockState(pos.up(10 + j1).west(6).south(3), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(7).south(3), leaves, 2);
						//Branch 5 - West
						world.setBlockState(pos.up(12 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(3).north(), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(4).north(), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(5).north(2), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(6).north(2), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(5).north(), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(5).north(3), leaves, 2);
						world.setBlockState(pos.up(13 + j1).west(5).north(2), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(5).north(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(6).north(3), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(6).north(), leaves, 2);
						world.setBlockState(pos.up(13 + j1).west(6).north(2), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(6).north(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(7).north(2), leaves, 2);
						//Branch 6 - West
						world.setBlockState(pos.up(13 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(13 + j1).west(3).south(), logX, 2);
						world.setBlockState(pos.up(13 + j1).west(4).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(5).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(6).south(), logX, 2);
						world.setBlockState(pos.up(12 + j1).west(7).south(), logX, 2);
						world.setBlockState(pos.up(13 + j1).west(6).south(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(6).south(), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(6).south(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(6), leaves, 2);
						world.setBlockState(pos.up(13 + j1).west(7).south(), leaves, 2);
						world.setBlockState(pos.up(11 + j1).west(7).south(), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(7).south(2), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(7), leaves, 2);
						world.setBlockState(pos.up(12 + j1).west(8).south(), leaves, 2);
						//Branch 7 - West
						world.setBlockState(pos.up(16 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(16 + j1).west(3), logX, 2);
						world.setBlockState(pos.up(15 + j1).west(4), logX, 2);
						world.setBlockState(pos.up(15 + j1).west(5), logX, 2);
						world.setBlockState(pos.up(15 + j1).west(6), logX, 2);
						world.setBlockState(pos.up(16 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(14 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(5).north(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(14 + j1).west(6), leaves, 2);
						world.setBlockState(pos.up(16 + j1).west(6), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(6).north(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(6).south(), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(7), leaves, 2);
						//Branch 8 - West
						world.setBlockState(pos.up(16 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(16 + j1).west(3).south(2), logX, 2);
						world.setBlockState(pos.up(16 + j1).west(4).south(3), logX, 2);
						world.setBlockState(pos.up(16 + j1).west(5).south(4), logX, 2);
						world.setBlockState(pos.up(16 + j1).west(4).south(2), leaves, 2);
						world.setBlockState(pos.up(16 + j1).west(4).south(4), leaves, 2);
						world.setBlockState(pos.up(17 + j1).west(4).south(3), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(4).south(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).west(5).south(3), leaves, 2);
						world.setBlockState(pos.up(16 + j1).west(5).south(5), leaves, 2);
						world.setBlockState(pos.up(17 + j1).west(5).south(4), leaves, 2);
						world.setBlockState(pos.up(15 + j1).west(5).south(4), leaves, 2);
						world.setBlockState(pos.up(16 + j1).west(6).south(4), leaves, 2);
						//Branch 9 - Nest
						world.setBlockState(pos.up(19 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(19 + j1).west(3).south(), logX, 2);
						world.setBlockState(pos.up(18 + j1).west(4).south(), logX, 2);
						world.setBlockState(pos.up(18 + j1).west(5).south(), logX, 2);
						world.setBlockState(pos.up(18 + j1).west(6).south(), logX, 2);
						world.setBlockState(pos.up(19 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).west(5).south(2), leaves, 2);
						world.setBlockState(pos.up(18 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(18 + j1).west(6).south(2), leaves, 2);
						world.setBlockState(pos.up(18 + j1).west(6), leaves, 2);
						world.setBlockState(pos.up(19 + j1).west(6).south(), leaves, 2);
						world.setBlockState(pos.up(17 + j1).west(6).south(), leaves, 2);
						world.setBlockState(pos.up(18 + j1).west(7).south(), leaves, 2);
						//Branch 10 - West
						world.setBlockState(pos.up(20 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(20 + j1).west(3).north(), logX, 2);
						world.setBlockState(pos.up(20 + j1).west(4).north(2), logX, 2);
						world.setBlockState(pos.up(20 + j1).west(5).north(3), logX, 2);
						world.setBlockState(pos.up(21 + j1).west(4).north(2), leaves, 2);
						world.setBlockState(pos.up(19 + j1).west(4).north(2), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(4).north(3), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(4).north(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(5).north(3), leaves, 2);
						world.setBlockState(pos.up(19 + j1).west(5).north(3), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(5).north(4), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(5).north(2), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(6).north(3), leaves, 2);
						//Branch 11 - West
						world.setBlockState(pos.up(21 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(21 + j1).west(3).south(2), logX, 2);
						world.setBlockState(pos.up(21 + j1).west(4).south(3), logX, 2);
						world.setBlockState(pos.up(21 + j1).west(3).south(3), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(3).south(), leaves, 2);
						world.setBlockState(pos.up(22 + j1).west(3).south(2), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(3).south(2), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(4).south(4), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(4).south(2), leaves, 2);
						world.setBlockState(pos.up(22 + j1).west(4).south(3), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(4).south(3), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(5).south(3), leaves, 2);
						//Branch 12 - West
						world.setBlockState(pos.up(22 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(22 + j1).west(3), logX, 2);
						world.setBlockState(pos.up(21 + j1).west(4), logX, 2);
						world.setBlockState(pos.up(21 + j1).west(5), logX, 2);
						world.setBlockState(pos.up(22 + j1).west(4), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(4), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(4).north(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(4).south(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(5).north(), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(22 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(20 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(21 + j1).west(6), leaves, 2);
						//Branch 13 - West
						world.setBlockState(pos.up(25 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(25 + j1).west(3).south(), logX, 2);
						world.setBlockState(pos.up(24 + j1).west(4).south(), logX, 2);
						world.setBlockState(pos.up(24 + j1).west(5).south(), logX, 2);
						world.setBlockState(pos.up(25 + j1).west(4).south(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).west(4).south(), leaves, 2);
						world.setBlockState(pos.up(24 + j1).west(4).south(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).west(4), leaves, 2);
						world.setBlockState(pos.up(24 + j1).west(5).south(2), leaves, 2);
						world.setBlockState(pos.up(24 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(25 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(23 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(24 + j1).west(6).south(), leaves, 2);
						//Branch 14 - West
						world.setBlockState(pos.up(27 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(27 + j1).west(3).south(2), logX, 2);
						world.setBlockState(pos.up(27 + j1).west(3).south(), leaves, 2);
						world.setBlockState(pos.up(27 + j1).west(3).south(3), leaves, 2);
						world.setBlockState(pos.up(28 + j1).west(3).south(2), leaves, 2);
						world.setBlockState(pos.up(26 + j1).west(3).south(2), leaves, 2);
						world.setBlockState(pos.up(27 + j1).west(4).south(2), leaves, 2);
						//Branch 15 - West
						world.setBlockState(pos.up(27 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(27 + j1).west(3).north(), logX, 2);
						world.setBlockState(pos.up(27 + j1).west(4).north(2), logX, 2);
						world.setBlockState(pos.up(27 + j1).west(3).north(2), leaves, 2);
						world.setBlockState(pos.up(27 + j1).west(3), leaves, 2);
						world.setBlockState(pos.up(28 + j1).west(3).north(), leaves, 2);
						world.setBlockState(pos.up(26 + j1).west(3).north(), leaves, 2);
						world.setBlockState(pos.up(27 + j1).west(5).north(2), leaves, 2);
						world.setBlockState(pos.up(27 + j1).west(4).north(3), leaves, 2);
						world.setBlockState(pos.up(27 + j1).west(4).north(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).west(4).north(2), leaves, 2);
						world.setBlockState(pos.up(26 + j1).west(4).north(2), leaves, 2);
						//Branch 16 - West
						world.setBlockState(pos.up(30 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(29 + j1).west(3).south(), logX, 2);
						world.setBlockState(pos.up(29 + j1).west(4).south(), logX, 2);
						world.setBlockState(pos.up(30 + j1).west(3).south(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).west(3).south(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).west(3).south(2), leaves, 2);
						world.setBlockState(pos.up(29 + j1).west(3), leaves, 2);
						world.setBlockState(pos.up(29 + j1).west(5).south(), leaves, 2);
						world.setBlockState(pos.up(30 + j1).west(4).south(), leaves, 2);
						world.setBlockState(pos.up(28 + j1).west(4).south(), leaves, 2);
						world.setBlockState(pos.up(29 + j1).west(4).south(2), leaves, 2);
						world.setBlockState(pos.up(29 + j1).west(4), leaves, 2);
						//Branch 17 - West
						world.setBlockState(pos.up(32 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(31 + j1).west(3), logX, 2);
						world.setBlockState(pos.up(31 + j1).west(4), logX, 2);
						world.setBlockState(pos.up(32 + j1).west(3), leaves, 2);
						world.setBlockState(pos.up(30 + j1).west(3), leaves, 2);
						world.setBlockState(pos.up(31 + j1).west(3).north(), leaves, 2);
						world.setBlockState(pos.up(31 + j1).west(3).south(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).west(2).north(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).west(4), leaves, 2);
						world.setBlockState(pos.up(30 + j1).west(4), leaves, 2);
						world.setBlockState(pos.up(31 + j1).west(4).north(), leaves, 2);
						world.setBlockState(pos.up(31 + j1).west(4).south(), leaves, 2);
						world.setBlockState(pos.up(31 + j1).west(5), leaves, 2);
						world.setBlockState(pos.up(33 + j1).west(2), leaves, 2);
						//Branch 18 - West
						world.setBlockState(pos.up(33 + j1).west(2).south(), logX, 2);
						world.setBlockState(pos.up(33 + j1).west(3).south(), leaves, 2);
						world.setBlockState(pos.up(33 + j1).west(2).south(2), leaves, 2);
						world.setBlockState(pos.up(33 + j1).west(2), leaves, 2);
						world.setBlockState(pos.up(34 + j1).west(2).south(), leaves, 2);
						world.setBlockState(pos.up(32 + j1).west(2).south(), leaves, 2);
						//Branch 19 - West
						world.setBlockState(pos.up(35 + j1).west(2), logX, 2);
						world.setBlockState(pos.up(36 + j1).west(2), leaves, 2);
						world.setBlockState(pos.up(36 + j1).west(2).south(), leaves, 2);
						world.setBlockState(pos.up(35 + j1).west(2).south(), leaves, 2);
						world.setBlockState(pos.up(34 + j1).west(2), leaves, 2);
						world.setBlockState(pos.up(35 + j1).west(3), leaves, 2);
					}
				} 
			}
			++i;
		}
		return i>0;
	}

}
