package superlord.prehistoricfauna.common.world;

import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.level.biome.MobSpawnSettings;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraftforge.common.world.BiomeGenerationSettingsBuilder;
import net.minecraftforge.event.world.BiomeLoadingEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import superlord.prehistoricfauna.PrehistoricFauna;
import superlord.prehistoricfauna.config.PrehistoricFaunaConfig;
import superlord.prehistoricfauna.init.PFEntities;
import superlord.prehistoricfauna.init.PFPlacedFeatures;

@Mod.EventBusSubscriber(modid = PrehistoricFauna.MOD_ID)
public class CretaceousBiomeDecorator {
	
	@SubscribeEvent
	public static void onBiomeLoad(BiomeLoadingEvent event) {
		BiomeGenerationSettingsBuilder builder = event.getGeneration();
		String name = event.getName().getPath();
		if (name.equals("djadochta_dunes")) {
			builder.addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PFPlacedFeatures.DEAD_OSMUNDACAULIS.getHolder().orElseThrow());
			PFPlacedFeatures.withDjadochtaRocks(builder);
			if (PrehistoricFaunaConfig.caveSentinelDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelDjadochtaDunesSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelDjadochtaDunesSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.protoceratopsDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PROTOCERATOPS.get(), PrehistoricFaunaConfig.protoceratopsDjadochtaDunesSpawnWeight, 2, 5));
			if (PrehistoricFaunaConfig.velociraptorDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.VELOCIRAPTOR.get(), PrehistoricFaunaConfig.velociraptorDjadochtaDunesSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.citipatiDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CITIPATI.get(), PrehistoricFaunaConfig.citipatiDjadochtaDunesSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.aepyornithomimusDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.AEPYORNITHOMIMUS.get(), PrehistoricFaunaConfig.aepyornithomimusDjadochtaDunesSpawnWeight, 2, 3));
			if (PrehistoricFaunaConfig.telmasaurusDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TELMASAURUS.get(), PrehistoricFaunaConfig.telmasaurusDjadochtaDunesSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.pinacosaurusDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PINACOSAURUS.get(), PrehistoricFaunaConfig.pinacosaurusDjadochtaDunesSpawnWeight, 3, 4));
			if (PrehistoricFaunaConfig.plesiohadrosDjadochtaDunesSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PLESIOHADROS.get(), PrehistoricFaunaConfig.plesiohadrosDjadochtaDunesSpawnWeight, 3, 5));
		}
		if (name.equals("djadochta_alluvial_plains")) {
			builder.addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PFPlacedFeatures.DEAD_OSMUNDACAULIS.getHolder().orElseThrow());
			PFPlacedFeatures.withDjadochtaRocks(builder);
			if (PrehistoricFaunaConfig.caveSentinelDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelDjadochtaAlluvialPlainsSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelDjadochtaAlluvialPlainsSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.protoceratopsDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PROTOCERATOPS.get(), PrehistoricFaunaConfig.protoceratopsDjadochtaAlluvialPlainsSpawnWeight, 2, 5));
			if (PrehistoricFaunaConfig.velociraptorDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.VELOCIRAPTOR.get(), PrehistoricFaunaConfig.velociraptorDjadochtaAlluvialPlainsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.citipatiDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CITIPATI.get(), PrehistoricFaunaConfig.citipatiDjadochtaAlluvialPlainsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.aepyornithomimusDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.AEPYORNITHOMIMUS.get(), PrehistoricFaunaConfig.aepyornithomimusDjadochtaAlluvialPlainsSpawnWeight, 2, 3));
			if (PrehistoricFaunaConfig.telmasaurusDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TELMASAURUS.get(), PrehistoricFaunaConfig.telmasaurusDjadochtaAlluvialPlainsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.pinacosaurusDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PINACOSAURUS.get(), PrehistoricFaunaConfig.pinacosaurusDjadochtaAlluvialPlainsSpawnWeight, 3, 4));
			if (PrehistoricFaunaConfig.plesiohadrosDjadochtaAlluvialPlainsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PLESIOHADROS.get(), PrehistoricFaunaConfig.plesiohadrosDjadochtaAlluvialPlainsSpawnWeight, 3, 5));
		}
		if (name.equals("djadochta_arroyo")) {
			builder.addFeature(GenerationStep.Decoration.VEGETAL_DECORATION, PFPlacedFeatures.DEAD_OSMUNDACAULIS.getHolder().orElseThrow());
			PFPlacedFeatures.withDjadochtaPlants(builder);
			PFPlacedFeatures.withDjadochtaRocks(builder);
			if (PrehistoricFaunaConfig.caveSentinelDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelDjadochtaArroyoSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelDjadochtaArroyoSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.protoceratopsDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PROTOCERATOPS.get(), PrehistoricFaunaConfig.protoceratopsDjadochtaArroyoSpawnWeight, 2, 5));
			if (PrehistoricFaunaConfig.velociraptorDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.VELOCIRAPTOR.get(), PrehistoricFaunaConfig.velociraptorDjadochtaArroyoSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.citipatiDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CITIPATI.get(), PrehistoricFaunaConfig.citipatiDjadochtaArroyoSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.aepyornithomimusDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.AEPYORNITHOMIMUS.get(), PrehistoricFaunaConfig.aepyornithomimusDjadochtaArroyoSpawnWeight, 3, 5));
			if (PrehistoricFaunaConfig.telmasaurusDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TELMASAURUS.get(), PrehistoricFaunaConfig.telmasaurusDjadochtaArroyoSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.pinacosaurusDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PINACOSAURUS.get(), PrehistoricFaunaConfig.pinacosaurusDjadochtaArroyoSpawnWeight, 4, 5));
			if (PrehistoricFaunaConfig.plesiohadrosDjadochtaArroyoSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PLESIOHADROS.get(), PrehistoricFaunaConfig.plesiohadrosDjadochtaArroyoSpawnWeight, 3, 5));
		}
		if (name.equals("hell_creek_swamp")) {
			PFPlacedFeatures.withHellCreekSwampPlants(builder);
			if (PrehistoricFaunaConfig.caveSentinelHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelHellCreekSwampSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelHellCreekSwampSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.acipenserHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ACIPENSER.get(), PrehistoricFaunaConfig.acipenserHellCreekSwampSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.ankylosaurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANKYLOSAURUS.get(), PrehistoricFaunaConfig.ankylosaurusHellCreekSwampSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.basilemysHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.BASILEMYS.get(), PrehistoricFaunaConfig.basilemysHellCreekSwampSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.cyclurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CYCLURUS.get(), PrehistoricFaunaConfig.cyclurusHellCreekSwampSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.dakotaraptorHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DAKOTARAPTOR.get(), PrehistoricFaunaConfig.dakotaraptorHellCreekSwampSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.didelphodonHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DIDELPHODON.get(), PrehistoricFaunaConfig.didelphodonHellCreekSwampSpawnWeight, 1, 3));
			//if (PrehistoricFaunaConfig.edmontosaurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.EDMONTOSAURUS.get(), PrehistoricFaunaConfig.edmontosaurusHellCreekSwampSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.lepisosteusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.GAR.get(), PrehistoricFaunaConfig.lepisosteusHellCreekSwampSpawnWeight, 1, 4));
			if (PrehistoricFaunaConfig.lonchidionHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.LONCHIDION.get(), PrehistoricFaunaConfig.lonchidionHellCreekSwampSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.melviusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MELVIUS.get(), PrehistoricFaunaConfig.melviusHellCreekSwampSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.myledaphusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MYLEDAPHUS.get(), PrehistoricFaunaConfig.myledaphusHellCreekSwampSpawnWeight, 1, 2));
			//if (PrehistoricFaunaConfig.pachycephalosaurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PACHYCEPHALOSAURUS.get(), PrehistoricFaunaConfig.pachycephalosaurusHellCreekSwampSpawnWeight, 2, 3));
			if (PrehistoricFaunaConfig.thescelosaurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THESCELOSAURUS.get(), PrehistoricFaunaConfig.thescelosaurusHellCreekSwampSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.thoracosaurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THORACOSAURUS.get(), PrehistoricFaunaConfig.thoracosaurusHellCreekSwampSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.triceratopsHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TRICERATOPS.get(), PrehistoricFaunaConfig.triceratopsHellCreekSwampSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.tyrannosaurusHellCreekSwampSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TYRANNOSAURUS.get(), PrehistoricFaunaConfig.tyrannosaurusHellCreekSwampSpawnWeight, 1, 2));
		}
		if (name.equals("hell_creek_liriodendrites_hills")) {
			PFPlacedFeatures.withHellCreekLiriodendritesHillsPlants(builder);
			if (PrehistoricFaunaConfig.caveSentinelHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelHellCreekLiriodendritesHillsSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelHellCreekLiriodendritesHillsSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.acipenserHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ACIPENSER.get(), PrehistoricFaunaConfig.acipenserHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.ankylosaurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANKYLOSAURUS.get(), PrehistoricFaunaConfig.ankylosaurusHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.basilemysHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.BASILEMYS.get(), PrehistoricFaunaConfig.basilemysHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.cyclurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CYCLURUS.get(), PrehistoricFaunaConfig.cyclurusHellCreekLiriodendritesHillsSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.dakotaraptorHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DAKOTARAPTOR.get(), PrehistoricFaunaConfig.dakotaraptorHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.didelphodonHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DIDELPHODON.get(), PrehistoricFaunaConfig.didelphodonHellCreekLiriodendritesHillsSpawnWeight, 1, 3));
			//if (PrehistoricFaunaConfig.edmontosaurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.EDMONTOSAURUS.get(), PrehistoricFaunaConfig.edmontosaurusHellCreekLiriodendritesHillsSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.lepisosteusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.GAR.get(), PrehistoricFaunaConfig.lepisosteusHellCreekLiriodendritesHillsSpawnWeight, 1, 4));
			if (PrehistoricFaunaConfig.lonchidionHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.LONCHIDION.get(), PrehistoricFaunaConfig.lonchidionHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.melviusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MELVIUS.get(), PrehistoricFaunaConfig.melviusHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.myledaphusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MYLEDAPHUS.get(), PrehistoricFaunaConfig.myledaphusHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			//if (PrehistoricFaunaConfig.pachycephalosaurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PACHYCEPHALOSAURUS.get(), PrehistoricFaunaConfig.pachycephalosaurusHellCreekLiriodendritesHillsSpawnWeight, 2, 3));
			if (PrehistoricFaunaConfig.thescelosaurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THESCELOSAURUS.get(), PrehistoricFaunaConfig.thescelosaurusHellCreekLiriodendritesHillsSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.thoracosaurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THORACOSAURUS.get(), PrehistoricFaunaConfig.thoracosaurusHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.triceratopsHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TRICERATOPS.get(), PrehistoricFaunaConfig.triceratopsHellCreekLiriodendritesHillsSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.tyrannosaurusHellCreekLiriodendritesHillsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TYRANNOSAURUS.get(), PrehistoricFaunaConfig.tyrannosaurusHellCreekLiriodendritesHillsSpawnWeight, 1, 2));
		}
		if (name.equals("hell_creek_clearing")) {
			PFPlacedFeatures.withHellCreekClearingPlants(builder);
			if (PrehistoricFaunaConfig.caveSentinelHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelHellCreekClearingSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelHellCreekClearingSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.acipenserHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ACIPENSER.get(), PrehistoricFaunaConfig.acipenserHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.ankylosaurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANKYLOSAURUS.get(), PrehistoricFaunaConfig.ankylosaurusHellCreekClearingSpawnWeight, 1, 2));
//			if (PrehistoricFaunaConfig.anzuHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANZU.get(), PrehistoricFaunaConfig.anzuHellCreekClearingSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.basilemysHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.BASILEMYS.get(), PrehistoricFaunaConfig.basilemysHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.cyclurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CYCLURUS.get(), PrehistoricFaunaConfig.cyclurusHellCreekClearingSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.dakotaraptorHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DAKOTARAPTOR.get(), PrehistoricFaunaConfig.dakotaraptorHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.didelphodonHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DIDELPHODON.get(), PrehistoricFaunaConfig.didelphodonHellCreekClearingSpawnWeight, 1, 3));
			//if (PrehistoricFaunaConfig.edmontosaurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.EDMONTOSAURUS.get(), PrehistoricFaunaConfig.edmontosaurusHellCreekClearingSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.lepisosteusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.GAR.get(), PrehistoricFaunaConfig.lepisosteusHellCreekClearingSpawnWeight, 1, 4));
			if (PrehistoricFaunaConfig.lonchidionHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.LONCHIDION.get(), PrehistoricFaunaConfig.lonchidionHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.melviusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MELVIUS.get(), PrehistoricFaunaConfig.melviusHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.myledaphusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MYLEDAPHUS.get(), PrehistoricFaunaConfig.myledaphusHellCreekClearingSpawnWeight, 1, 2));
			//if (PrehistoricFaunaConfig.pachycephalosaurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PACHYCEPHALOSAURUS.get(), PrehistoricFaunaConfig.pachycephalosaurusHellCreekClearingSpawnWeight, 2, 3));
			//if (PrehistoricFaunaConfig.palaeosaniwaHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PALAEOSANIWA.get(), PrehistoricFaunaConfig.palaeosaniwaHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.thescelosaurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THESCELOSAURUS.get(), PrehistoricFaunaConfig.thescelosaurusHellCreekClearingSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.thoracosaurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THORACOSAURUS.get(), PrehistoricFaunaConfig.thoracosaurusHellCreekClearingSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.triceratopsHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TRICERATOPS.get(), PrehistoricFaunaConfig.triceratopsHellCreekClearingSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.tyrannosaurusHellCreekClearingSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TYRANNOSAURUS.get(), PrehistoricFaunaConfig.tyrannosaurusHellCreekClearingSpawnWeight, 1, 2));
		}
		if (name.equals("hell_creek_redwoods")) {
			PFPlacedFeatures.withHellCreekRedwoodsPlants(builder);
			if (PrehistoricFaunaConfig.caveSentinelHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelHellCreekRedwoodsSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelHellCreekRedwoodsSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.acipenserHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ACIPENSER.get(), PrehistoricFaunaConfig.acipenserHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.ankylosaurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANKYLOSAURUS.get(), PrehistoricFaunaConfig.ankylosaurusHellCreekRedwoodsSpawnWeight, 1, 2));
//			if (PrehistoricFaunaConfig.anzuHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANZU.get(), PrehistoricFaunaConfig.anzuHellCreekRedwoodsSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.basilemysHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.BASILEMYS.get(), PrehistoricFaunaConfig.basilemysHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.cyclurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CYCLURUS.get(), PrehistoricFaunaConfig.cyclurusHellCreekRedwoodsSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.dakotaraptorHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DAKOTARAPTOR.get(), PrehistoricFaunaConfig.dakotaraptorHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.didelphodonHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DIDELPHODON.get(), PrehistoricFaunaConfig.didelphodonHellCreekRedwoodsSpawnWeight, 1, 3));
			//if (PrehistoricFaunaConfig.edmontosaurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.EDMONTOSAURUS.get(), PrehistoricFaunaConfig.edmontosaurusHellCreekRedwoodsSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.lepisosteusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.GAR.get(), PrehistoricFaunaConfig.lepisosteusHellCreekRedwoodsSpawnWeight, 1, 4));
			if (PrehistoricFaunaConfig.lonchidionHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.LONCHIDION.get(), PrehistoricFaunaConfig.lonchidionHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.melviusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MELVIUS.get(), PrehistoricFaunaConfig.melviusHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.myledaphusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MYLEDAPHUS.get(), PrehistoricFaunaConfig.myledaphusHellCreekRedwoodsSpawnWeight, 1, 2));
			//if (PrehistoricFaunaConfig.pachycephalosaurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PACHYCEPHALOSAURUS.get(), PrehistoricFaunaConfig.pachycephalosaurusHellCreekRedwoodsSpawnWeight, 2, 3));
			//if (PrehistoricFaunaConfig.palaeosaniwaHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PALAEOSANIWA.get(), PrehistoricFaunaConfig.palaeosaniwaHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.thescelosaurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THESCELOSAURUS.get(), PrehistoricFaunaConfig.thescelosaurusHellCreekRedwoodsSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.thoracosaurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THORACOSAURUS.get(), PrehistoricFaunaConfig.thoracosaurusHellCreekRedwoodsSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.triceratopsHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TRICERATOPS.get(), PrehistoricFaunaConfig.triceratopsHellCreekRedwoodsSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.tyrannosaurusHellCreekRedwoodsSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TYRANNOSAURUS.get(), PrehistoricFaunaConfig.tyrannosaurusHellCreekRedwoodsSpawnWeight, 1, 2));
		}
		if (name.equals("hell_creek_river")) {
			PFPlacedFeatures.withHellCreekRiverPlants(builder);
			if (PrehistoricFaunaConfig.caveSentinelHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelHellCreekRiverSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelHellCreekRiverSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.acipenserHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ACIPENSER.get(), PrehistoricFaunaConfig.acipenserHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.ankylosaurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANKYLOSAURUS.get(), PrehistoricFaunaConfig.ankylosaurusHellCreekRiverSpawnWeight, 1, 2));
//			if (PrehistoricFaunaConfig.anzuHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANZU.get(), PrehistoricFaunaConfig.anzuHellCreekRiverSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.basilemysHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.BASILEMYS.get(), PrehistoricFaunaConfig.basilemysHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.cyclurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CYCLURUS.get(), PrehistoricFaunaConfig.cyclurusHellCreekRiverSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.dakotaraptorHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DAKOTARAPTOR.get(), PrehistoricFaunaConfig.dakotaraptorHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.didelphodonHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DIDELPHODON.get(), PrehistoricFaunaConfig.didelphodonHellCreekRiverSpawnWeight, 1, 3));
			//if (PrehistoricFaunaConfig.edmontosaurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.EDMONTOSAURUS.get(), PrehistoricFaunaConfig.edmontosaurusHellCreekRiverSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.lepisosteusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.GAR.get(), PrehistoricFaunaConfig.lepisosteusHellCreekRiverSpawnWeight, 1, 4));
			if (PrehistoricFaunaConfig.lonchidionHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.LONCHIDION.get(), PrehistoricFaunaConfig.lonchidionHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.melviusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MELVIUS.get(), PrehistoricFaunaConfig.melviusHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.myledaphusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MYLEDAPHUS.get(), PrehistoricFaunaConfig.myledaphusHellCreekRiverSpawnWeight, 1, 2));
			//if (PrehistoricFaunaConfig.pachycephalosaurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PACHYCEPHALOSAURUS.get(), PrehistoricFaunaConfig.pachycephalosaurusHellCreekRiverSpawnWeight, 2, 3));
			//if (PrehistoricFaunaConfig.palaeosaniwaHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PALAEOSANIWA.get(), PrehistoricFaunaConfig.palaeosaniwaHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.thescelosaurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THESCELOSAURUS.get(), PrehistoricFaunaConfig.thescelosaurusHellCreekRiverSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.thoracosaurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THORACOSAURUS.get(), PrehistoricFaunaConfig.thoracosaurusHellCreekRiverSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.triceratopsHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TRICERATOPS.get(), PrehistoricFaunaConfig.triceratopsHellCreekRiverSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.tyrannosaurusHellCreekRiverSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TYRANNOSAURUS.get(), PrehistoricFaunaConfig.tyrannosaurusHellCreekRiverSpawnWeight, 1, 2));
		}
		if (name.equals("hell_creek_hardwood_forest")) {
			PFPlacedFeatures.withHellCreekHardwoodForestPlants(builder);
			if (PrehistoricFaunaConfig.caveSentinelHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.CAVE_SENTINEL.get(), PrehistoricFaunaConfig.caveSentinelHellCreekHardwoodForestSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.landSentinelHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.MONSTER, new MobSpawnSettings.SpawnerData(PFEntities.LAND_SENTINEL.get(), PrehistoricFaunaConfig.landSentinelHellCreekHardwoodForestSpawnWeight, 1, 1));
			if (PrehistoricFaunaConfig.acipenserHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ACIPENSER.get(), PrehistoricFaunaConfig.acipenserHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.ankylosaurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANKYLOSAURUS.get(), PrehistoricFaunaConfig.ankylosaurusHellCreekHardwoodForestSpawnWeight, 1, 2));
//			if (PrehistoricFaunaConfig.anzuHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.ANZU.get(), PrehistoricFaunaConfig.anzuHellCreekHardwoodForestSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.basilemysHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.BASILEMYS.get(), PrehistoricFaunaConfig.basilemysHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.cyclurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.CYCLURUS.get(), PrehistoricFaunaConfig.cyclurusHellCreekHardwoodForestSpawnWeight, 1, 3));
			if (PrehistoricFaunaConfig.dakotaraptorHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DAKOTARAPTOR.get(), PrehistoricFaunaConfig.dakotaraptorHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.didelphodonHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.DIDELPHODON.get(), PrehistoricFaunaConfig.didelphodonHellCreekHardwoodForestSpawnWeight, 1, 3));
			//if (PrehistoricFaunaConfig.edmontosaurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.EDMONTOSAURUS.get(), PrehistoricFaunaConfig.edmontosaurusHellCreekHardwoodForestSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.lepisosteusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.GAR.get(), PrehistoricFaunaConfig.lepisosteusHellCreekHardwoodForestSpawnWeight, 1, 4));
			if (PrehistoricFaunaConfig.lonchidionHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.LONCHIDION.get(), PrehistoricFaunaConfig.lonchidionHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.melviusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MELVIUS.get(), PrehistoricFaunaConfig.melviusHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.myledaphusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.WATER_CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.MYLEDAPHUS.get(), PrehistoricFaunaConfig.myledaphusHellCreekHardwoodForestSpawnWeight, 1, 2));
			//if (PrehistoricFaunaConfig.pachycephalosaurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PACHYCEPHALOSAURUS.get(), PrehistoricFaunaConfig.pachycephalosaurusHellCreekHardwoodForestSpawnWeight, 2, 3));
			//if (PrehistoricFaunaConfig.palaeosaniwaHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.PALAEOSANIWA.get(), PrehistoricFaunaConfig.palaeosaniwaHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.thescelosaurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THESCELOSAURUS.get(), PrehistoricFaunaConfig.thescelosaurusHellCreekHardwoodForestSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.thoracosaurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.THORACOSAURUS.get(), PrehistoricFaunaConfig.thoracosaurusHellCreekHardwoodForestSpawnWeight, 1, 2));
			if (PrehistoricFaunaConfig.triceratopsHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TRICERATOPS.get(), PrehistoricFaunaConfig.triceratopsHellCreekHardwoodForestSpawnWeight, 2, 4));
			if (PrehistoricFaunaConfig.tyrannosaurusHellCreekHardwoodForestSpawnWeight != 0) event.getSpawns().addSpawn(MobCategory.CREATURE, new MobSpawnSettings.SpawnerData(PFEntities.TYRANNOSAURUS.get(), PrehistoricFaunaConfig.tyrannosaurusHellCreekHardwoodForestSpawnWeight, 1, 2));
		}
	}

}
